// Generated by pegc — do not edit
#pragma once

#include "PegRuntime.h"
#include "CalcAST.h"

#include <string>
   #include <cstdint>


class Parser : public peg::PegCursor {
public:
    Parser() = default;

    void init(const char* input, int length);
    bool parse();

    calc::Program* ast = nullptr;


private:
    void setup_skip();


    bool parse_Calc();
    bool parse_Expr(calc::Expr* * result);
    bool parse_AddExpr(calc::Expr* * result);
    bool parse_MulExpr(calc::Expr* * result);
    bool parse_UnaryExpr(calc::Expr* * result);
    bool parse_Atom(calc::Expr* * result);

};

