// Generated by pegc — do not edit
#pragma once

#include "PegRuntime.h"
#include "BBQ_AST.h"

#include <string>
   #include <vector>
   #include <optional>
   #include <cstdlib>
   #include "PegRuntime.h"

using namespace BBQ;


class Parser : public peg::PegCursor {
public:
    Parser() = default;

    void init(const char* input, int length);
    bool parse();

    Grammar* ast = nullptr;


private:
    void setup_skip();

    SourceLoc Loc() {
        return SourceLoc{nullptr, line(), col()};
    }

    PrimitiveKind* DecodePrimitive(const std::string &s, SourceLoc loc) {
        if (s == "bool")   { auto* n = new BoolKind();   n->loc = loc; return n; }
        if (s == "bytes")  { auto* n = new BytesKind();  n->loc = loc; return n; }
        if (s == "string") { auto* n = new StringKind(); n->loc = loc; return n; }

        // Float types
        if (s.substr(0, 5) == "float") {
            Width w = (s.find("64") != std::string::npos) ? Width::W64 : Width::W32;
            Endianness e = Endianness::Default;
            if (s.size() > 7) {
                std::string suf = s.substr(s.size() - 2);
                if (suf == "le") e = Endianness::Little;
                else if (suf == "be") e = Endianness::Big;
            }
            auto* n = new FloatKind(w, e); n->loc = loc; return n;
        }

        // LEB128 varints: uleb128/uleb32 → u32, uleb64 → u64;
        //                 sleb128/sleb32 → i32, sleb64 → i64. No endianness.
        if (s == "uleb128" || s == "uleb32" || s == "uleb64" ||
            s == "sleb128" || s == "sleb32" || s == "sleb64") {
            Encoding enc = (s[0] == 'u') ? Encoding::Uleb : Encoding::Sleb;
            Signedness sign = (s[0] == 'u') ? Signedness::Unsigned : Signedness::Signed;
            Width w = (s.find("64") != std::string::npos) ? Width::W64 : Width::W32;
            auto* n = new IntegerKind(w, sign, Endianness::Default, enc); n->loc = loc; return n;
        }

        // Integer types (uint* / int*)
        if (s.substr(0, 4) == "uint" || s.substr(0, 3) == "int") {
            Signedness sign = Signedness::Signed;
            std::string rest = s;
            if (s.substr(0, 4) == "uint") { sign = Signedness::Unsigned; rest = s.substr(4); }
            else if (s.substr(0, 3) == "int") { rest = s.substr(3); }

            Width w = Width::W8;
            if (rest.find("64") != std::string::npos) w = Width::W64;
            else if (rest.find("32") != std::string::npos) w = Width::W32;
            else if (rest.find("16") != std::string::npos) w = Width::W16;

            Endianness e = Endianness::Default;
            if (s.size() > 5) {
                std::string suf = s.substr(s.size() - 2);
                if (suf == "le") e = Endianness::Little;
                else if (suf == "be") e = Endianness::Big;
            }

            auto* n = new IntegerKind(w, sign, e, Encoding::Fixed); n->loc = loc; return n;
        }

        return nullptr;
    }


    bool parse_BBQ();
    bool parse_Directive(std::vector<EndianDirective*> * dirs);
    bool parse_CodeDirective(std::vector<CodeBlock*> * codes);
    bool parse_Rule_(std::vector<Rule*> * rules);
    bool parse_TypeBody(TypeExpr* * result);
    bool parse_TypeTerm(TypeExpr* * result);
    bool parse_TypePrimary(TypeExpr* * result);
    bool parse_StructBody(TypeExpr* * result);
    bool parse_StructElement(std::vector<Field*> * fields);
    bool parse_EndianDirectiveField(std::vector<Field*> * fields);
    bool parse_FieldDecl(std::vector<Field*> * fields);
    bool parse_UnionBody(TypeExpr* * result);
    bool parse_VariantDecl(std::vector<Variant*> * variants);
    bool parse_ArrayBody(TypeExpr* * result);
    bool parse_ArraySpecRule(ArraySpec* * result);
    bool parse_SepSpec(Separator* * result);
    bool parse_TermSpec(Terminator* * result);
    bool parse_OptionalBody(TypeExpr* * result);
    bool parse_SwitchBody(TypeExpr* * result);
    bool parse_SwitchCaseRule(std::vector<SwitchCase*> * cases);
    bool parse_DefaultCaseRule(SwitchDefault* * result);
    bool parse_CaseValueRule(CaseValue* * result);
    bool parse_DottedRef(CaseValue* * result);
    bool parse_ComputeBody(TypeExpr* * result);
    bool parse_ExternBody(TypeExpr* * result);
    bool parse_BitfieldBody(TypeExpr* * result);
    bool parse_BitfieldEntryRule(std::vector<BitfieldEntry*> * entries);
    bool parse_PrimitiveType(TypeExpr* * result);
    bool parse_PrimKeyword(PrimitiveKind* * result);
    bool parse_RuleRefType(TypeExpr* * result);
    bool parse_ConstraintBlock(Expr* * result);
    bool parse_IntervalSpec(Interval* * result);
    bool parse_ElementIntervalSpec(Interval* * result);
    bool parse_Expr_(Expr* * result);
    bool parse_TernaryExpr(Expr* * result);
    bool parse_LogicalOr(Expr* * result);
    bool parse_LogicalAnd(Expr* * result);
    bool parse_BitwiseOr(Expr* * result);
    bool parse_BitwiseXor(Expr* * result);
    bool parse_BitwiseAnd(Expr* * result);
    bool parse_Equality(Expr* * result);
    bool parse_Relational(Expr* * result);
    bool parse_Shift(Expr* * result);
    bool parse_Additive(Expr* * result);
    bool parse_Multiplicative(Expr* * result);
    bool parse_Unary(Expr* * result);
    bool parse_Postfix(Expr* * result);
    bool parse_PrimaryExpr(Expr* * result);
    bool parse_FloatLitExpr(Expr* * result);
    bool parse_CallExpr(Expr* * result);
    bool ident(peg::Span& out);
    bool ident() { peg::Span _d; return ident(_d); }
    bool integer(peg::Span& out);
    bool integer() { peg::Span _d; return integer(_d); }
    bool floating(peg::Span& out);
    bool floating() { peg::Span _d; return floating(_d); }
    bool string_lit(peg::Span& out);
    bool string_lit() { peg::Span _d; return string_lit(_d); }

};

