// Generated by pegc — do not edit
#pragma once

#include "PegRuntime.h"
#include "opgen_ast.h"

#include "opgen_ast.h"
#include <cstring>
#include <cstdlib>

// ── Helpers ─────────────────────────────────────────────────
//
// Strings live as `const char*` interned in the AST arena (so the
// salvaged emitters keep `fprintf("%s", node->field)`). `dup` is a
// verbatim span copy — matching the C `odup`, string-literal quotes
// preserved; do NOT unescape (that would change emitted bytes).

static inline const char* opgen_dup(peg::Span s) {
    char* d = (char*)opgen::ASTNode::get_arena().allocate((size_t)s.len + 1);
    std::memcpy(d, s.ptr, (size_t)s.len);
    d[s.len] = '\0';
    return d;
}

static inline const char* opgen_intern(const std::string& s) {
    char* d = (char*)opgen::ASTNode::get_arena().allocate(s.size() + 1);
    std::memcpy(d, s.data(), s.size());
    d[s.size()] = '\0';
    return d;
}

// Trim leading/trailing whitespace then intern — matches the C otrim_dup.
static inline const char* opgen_trim_intern(const std::string& s) {
    size_t b = 0, e = s.size();
    while (b < e && (s[b]==' '||s[b]=='\t'||s[b]=='\r'||s[b]=='\n')) b++;
    while (e > b && (s[e-1]==' '||s[e-1]=='\t'||s[e-1]=='\r'||s[e-1]=='\n')) e--;
    return opgen_intern(s.substr(b, e - b));
}

static inline int64_t opgen_parse_int(peg::Span s) {
    int64_t v = 0; int i = 0; int base = 10;
    if (s.len >= 2 && s.ptr[0] == '0' && (s.ptr[1] == 'x' || s.ptr[1] == 'X')) {
        base = 16; i = 2;
    }
    for (; i < s.len; i++) {
        char c = s.ptr[i];
        int d = (c <= '9') ? c - '0'
              : (c <= 'F') ? c - 'A' + 10
              :              c - 'a' + 10;
        v = v * base + d;
    }
    return v;
}

static inline double opgen_parse_float(peg::Span s) {
    char buf[64]; int n = s.len < 63 ? s.len : 63;
    std::memcpy(buf, s.ptr, (size_t)n); buf[n] = '\0';
    return std::strtod(buf, nullptr);
}

// Wrap a possibly-null pointer into an optional (nullopt when null) —
// preserves the C "NULL means absent" convention for `?` fields.
template <class T>
static inline std::optional<T*> opgen_opt(T* p) {
    return p ? std::optional<T*>(p) : std::nullopt;
}

using namespace opgen;


class Parser : public peg::PegCursor {
public:
    Parser() = default;

    void init(const char* input, int length);
    bool parse();

    opgen::Module* ast = nullptr;


private:
    void setup_skip();

    opgen::SourceLoc Loc() {
        return opgen::SourceLoc{nullptr, line(), col()};
    }


    bool parse_Opgen();
    bool parse_OpcodeDef(opgen::Opcode*& result);
    bool parse_FamilyDef(std::vector<opgen::Opcode*>& ops);
    bool parse_FamilyStackParam(std::vector<opgen::StackParam*>& list, std::vector<int>& var_flags);
    bool parse_FamilyMember(std::vector<opgen::ValueType>& mvts, std::vector<const char*>& mnames, std::vector<int64_t>& mhexes, std::vector<int64_t>& msubs);
    bool parse_OperandParam(std::vector<opgen::OperandParam*>& list);
    bool parse_StackParam(std::vector<opgen::StackParam*>& list);
    bool parse_ValueType(opgen::ValueType& out);
    bool parse_LocalValueKind(opgen::LocalValueKind& out);
    bool parse_Annotation(std::vector<opgen::ErrorCase*>& errs, std::vector<const char*>& flags, std::optional<opgen::LocalValueDecl*>& local_value);
    bool parse_SemBody(std::vector<opgen::SemStmt*>& body);
    bool parse_SemBlockStmt(std::vector<opgen::SemStmt*>& list);
    bool parse_SemLocalDecl(std::vector<opgen::SemStmt*>& list);
    bool parse_SemDeclarator(std::vector<opgen::SemStmt*>& list, const char* ty);
    bool parse_SemStmt(opgen::SemStmt*& out);
    bool parse_ForClause(opgen::SemStmt*& out);
    bool parse_SemBlock(opgen::SemStmt*& out);
    bool parse_SemSimpleStmt(opgen::SemStmt*& out);
    bool parse_SemExpr(opgen::SemExpr*& out);
    bool parse_SemTernary(opgen::SemExpr*& out);
    bool parse_SemCondOr(opgen::SemExpr*& out);
    bool parse_SemCondAnd(opgen::SemExpr*& out);
    bool parse_SemBinOr(opgen::SemExpr*& out);
    bool parse_SemBinXor(opgen::SemExpr*& out);
    bool parse_SemBinAnd(opgen::SemExpr*& out);
    bool parse_SemEq(opgen::SemExpr*& out);
    bool parse_SemRel(opgen::SemExpr*& out);
    bool parse_SemShift(opgen::SemExpr*& out);
    bool parse_SemAdd(opgen::SemExpr*& out);
    bool parse_SemMul(opgen::SemExpr*& out);
    bool parse_SemUnary(opgen::SemExpr*& out);
    bool parse_SemPostfix(opgen::SemExpr*& out);
    bool parse_SemPrimary(opgen::SemExpr*& out);
    bool parse_MethodType(const char*& out);
    bool parse_MethodParam(std::vector<opgen::MethodParam*>& list);
    bool parse_StatusDecl(std::optional<opgen::StatusDecl*>& out);
    bool parse_BackendDecl(std::optional<const char*>& out);
    bool parse_TypeDecl(std::vector<opgen::TypeDecl*>& list);
    bool parse_MethodDecl(std::vector<opgen::MethodDecl*>& list);
    bool parse_JavaPrimType(const char*& out);
    bool ident(peg::Span& out);
    bool ident() { peg::Span _d; return ident(_d); }
    bool integer(peg::Span& out);
    bool integer() { peg::Span _d; return integer(_d); }
    bool floating(peg::Span& out);
    bool floating() { peg::Span _d; return floating(_d); }
    bool string_lit(peg::Span& out);
    bool string_lit() { peg::Span _d; return string_lit(_d); }

};

