// Generated by pegc — do not edit
#pragma once

#include "PegRuntime.h"
#include "AsdlAST.h"

#include <string>
   #include <vector>
   #include "PegRuntime.h"


class Parser : public peg::PegCursor {
public:
    Parser() = default;

    void init(const char* input, int length);
    bool parse();

    asdl_ast::Module* ast = nullptr;


private:
    void setup_skip();


    bool parse_Asdl();
    bool parse_TypeAliasDecl(std::vector<asdl_ast::TypeAlias*>& aliases);
    bool parse_DefinitionDecl(std::vector<asdl_ast::Definition*>& defs);
    bool parse_TypeBodyDecl(asdl_ast::TypeBody*& result);
    bool parse_ProductBody(asdl_ast::TypeBody*& result);
    bool parse_SumBody(asdl_ast::TypeBody*& result);
    bool parse_ConstructorDecl(asdl_ast::Constructor*& result);
    bool parse_FieldList(std::vector<asdl_ast::Field*>& fields);
    bool parse_FieldDecl(asdl_ast::Field*& result);
    bool parse_TypId(std::string& name);
    bool parse_ConId(std::string& name);
    bool parse_AnyId(std::string& name);
    bool ident(peg::Span& out);
    bool string_lit(peg::Span& out);

};

