// Generated by pegc — do not edit
#pragma once

#include "PegRuntime.h"
#include "GrammarAST.h"

#include <string>
#include <vector>
#include <optional>
#include <cstdlib>

using namespace PegGrammar;


class Parser : public peg::PegCursor {
public:
    Parser() = default;

    void init(const char* input, int length);
    bool parse();

    Grammar* ast = nullptr;


private:
    void setup_skip();

    SourceLoc Loc() {
        return SourceLoc{nullptr, line(), col()};
    }

    void ParseParams(const std::string& raw, std::vector<Param*>& params) {
        // Split by commas, respecting <> nesting for templates
        std::vector<std::string> parts;
        int depth = 0;
        size_t start = 0;
        for (size_t i = 0; i < raw.size(); i++) {
            if (raw[i] == '<') depth++;
            else if (raw[i] == '>') depth--;
            else if (raw[i] == ',' && depth == 0) {
                parts.push_back(raw.substr(start, i - start));
                start = i + 1;
            }
        }
        parts.push_back(raw.substr(start));

        for (auto& part : parts) {
            size_t ps = part.find_first_not_of(" \t\r\n");
            size_t pe = part.find_last_not_of(" \t\r\n");
            if (ps == std::string::npos) continue;
            std::string trimmed = part.substr(ps, pe - ps + 1);
            if (trimmed.empty()) continue;

            size_t name_end = trimmed.size();
            while (name_end > 0 && (std::isalnum(trimmed[name_end-1]) || trimmed[name_end-1] == '_'))
                name_end--;
            std::string name = trimmed.substr(name_end);
            if (name.empty()) continue;

            bool is_ref = false;
            size_t type_end = name_end;
            while (type_end > 0 && trimmed[type_end-1] == ' ') type_end--;
            if (type_end > 0 && trimmed[type_end-1] == '&') {
                is_ref = true;
                type_end--;
            }
            while (type_end > 0 && trimmed[type_end-1] == ' ') type_end--;

            std::string type_code = trimmed.substr(0, type_end);
            auto* p = new Param(std::move(type_code), std::move(name), is_ref);
            p->loc = Loc();
            params.push_back(p);
        }
    }

    std::string TrimSemAction(const std::string& s) {
        size_t start = s.find_first_not_of(" \t\r\n");
        size_t end = s.find_last_not_of(" \t\r\n");
        if (start == std::string::npos) return "";
        return s.substr(start, end - start + 1);
    }


    bool parse_Peg();
    bool parse_SemAction_(std::vector<Header*>& headers);
    bool parse_CharsetDecl(std::vector<CharsetDef*>& defs);
    bool parse_CharsetExpr_(CharsetExpr*& result);
    bool parse_CharsetDiff(CharsetExpr*& result);
    bool parse_CharsetPrimary(CharsetExpr*& result);
    bool parse_TokenDecl(std::vector<TokenDef*>& defs);
    bool parse_TokenExpr_(TokenExpr*& result);
    bool parse_TokenSeq(TokenExpr*& result);
    bool parse_TokenFactor(TokenExpr*& result);
    bool parse_TokenAtom(TokenExpr*& result);
    bool parse_CommentDecl(std::vector<CommentDef*>& defs);
    bool parse_ProductionDecl(std::vector<Production*>& prods);
    bool parse_PegBody(PegExpr*& result);
    bool parse_PegSeq(PegExpr*& result);
    bool parse_PegFactor(PegExpr*& result);
    bool parse_PegAtom(PegExpr*& result);
    bool parse_ArgExpr(std::vector<Arg*>& args);

};

