// calc_jit.cpp — End-to-end JIT calculator using the full BBQ toolchain
//
// Pipeline: pegc parser → ASDL AST → DDCG compiler → burgc matcher → jitterator stencils
//
// Usage: calc_jit "10 + 20 * (5 - 3)"

#include "CalcMatcher.h"  // Generated by burgc — includes compiler.h and all deps
#include "Parser.h"       // Generated by pegc
#include <cstdio>
#include <cstring>

int main(int argc, char** argv) {
    const char* input = argc > 1 ? argv[1] : "10 + 20 * (5 - 3)";

    // ── Parse ──
    Parser parser;
    parser.init(input, (int)strlen(input));
    if (!parser.parse() || !parser.ast) {
        fprintf(stderr, "Parse error\n");
        return 1;
    }

    // ── Compile AST → IR continuation graph ──
    Compiler compiler;
    calc_ir::Node* ir = compiler.compile(parser.ast->body);

    // ── JIT: BURG labels + reduces → emits stencils ──
    JitContext ctx;
    jit_ctx = &ctx;
    ctx.emit_entry();
    burg_rewrite(ir);
    ctx.backpatch_all();

    // ── Execute ──
    auto* fn = (void(*)(int64_t*))ctx.buf.finalize();
    int64_t slots[64] = {};
    // Pre-fill slots for $N references (from command line: -s0=10 -s1=20 ...)
    for (int i = 2; i < argc; i++) {
        if (argv[i][0] == '-' && argv[i][1] == 's') {
            int slot = 0; int64_t val = 0;
            if (sscanf(argv[i], "-s%d=%ld", &slot, &val) == 2 && slot >= 0 && slot < 64)
                slots[slot] = val;
        }
    }
    fn(slots);

    printf("%s = %ld\n", input, slots[compiler.result_slot()]);
    return 0;
}
