// stencil_table.h — generated by jitterator. DO NOT EDIT.
#pragma once
#include <stdint.h>

typedef enum {
    STENCIL_ADD = 0,
    STENCIL_SUB = 1,
    STENCIL_LOAD_CONST = 2,
    STENCIL_HALT = 3,
    STENCIL_ENTRY = 4,
    STENCIL_COUNT = 5
} StencilId;

typedef enum {
    PATCH_ABS64,
    PATCH_ABS32S,
    PATCH_REL_BRANCH,  // 32-bit PC-relative branch (value = target address)
    PATCH_REL_DATA,    // 32-bit PC-relative data load (needs constant pool)
} PatchType;

typedef struct {
    uint32_t offset;
    PatchType type;
    uint16_t hole_index;
    const char *hole_name;
} PatchEntry;

typedef struct {
    const uint8_t *code;
    uint32_t code_size;
    const PatchEntry *patches;
    uint32_t patch_count;
    uint16_t hole_count;
    uint16_t data_hole_count;  // holes needing constant pool (8 bytes each)
    const char **hole_names;
} StencilDef;

static const uint8_t code_add[] = {
    0x48,0x8b,0x05,0x00,0x00,0x00,0x00,0x48,0x8b,0x0d,0x00,0x00,0x00,0x00,0x49,0x8b,
    0x0c,0xcc,0x49,0x03,0x0c,0xc4,0x48,0x8b,0x05,0x00,0x00,0x00,0x00,0x49,0x89,0x0c,
    0xc4,0xe9,0x00,0x00,0x00,0x00,
};

static const PatchEntry patches_add[] = {
    {3, PATCH_REL_DATA, 0, "_HOLE_lhs"},
    {10, PATCH_REL_DATA, 1, "_HOLE_rhs"},
    {25, PATCH_REL_DATA, 2, "_HOLE_dst"},
    {34, PATCH_REL_BRANCH, 3, "_HOLE_cont"},
};

static const char *holes_add[] = {"_HOLE_lhs", "_HOLE_rhs", "_HOLE_dst", "_HOLE_cont", };

static const uint8_t code_sub[] = {
    0x48,0x8b,0x05,0x00,0x00,0x00,0x00,0x49,0x8b,0x04,0xc4,0x48,0x8b,0x0d,0x00,0x00,
    0x00,0x00,0x49,0x2b,0x04,0xcc,0x48,0x8b,0x0d,0x00,0x00,0x00,0x00,0x49,0x89,0x04,
    0xcc,0xe9,0x00,0x00,0x00,0x00,
};

static const PatchEntry patches_sub[] = {
    {3, PATCH_REL_DATA, 0, "_HOLE_lhs"},
    {14, PATCH_REL_DATA, 1, "_HOLE_rhs"},
    {25, PATCH_REL_DATA, 2, "_HOLE_dst"},
    {34, PATCH_REL_BRANCH, 3, "_HOLE_cont"},
};

static const char *holes_sub[] = {"_HOLE_lhs", "_HOLE_rhs", "_HOLE_dst", "_HOLE_cont", };

static const uint8_t code_load_const[] = {
    0x48,0x8b,0x05,0x00,0x00,0x00,0x00,0x48,0x8b,0x0d,0x00,0x00,0x00,0x00,0x49,0x89,
    0x04,0xcc,0xe9,0x00,0x00,0x00,0x00,
};

static const PatchEntry patches_load_const[] = {
    {3, PATCH_REL_DATA, 0, "_HOLE_value"},
    {10, PATCH_REL_DATA, 1, "_HOLE_dst"},
    {19, PATCH_REL_BRANCH, 2, "_HOLE_cont"},
};

static const char *holes_load_const[] = {"_HOLE_value", "_HOLE_dst", "_HOLE_cont", };

static const uint8_t code_halt[] = {
    0xc3,
};

static const uint8_t code_entry[] = {
    0x41,0x57,0x41,0x56,0x41,0x55,0x41,0x54,0x53,0x49,0x89,0xfc,0xe8,0x00,0x00,0x00,
    0x00,0x5b,0x41,0x5c,0x41,0x5d,0x41,0x5e,0x41,0x5f,0xc3,
};

static const PatchEntry patches_entry[] = {
    {13, PATCH_REL_BRANCH, 0, "_HOLE_cont"},
};

static const char *holes_entry[] = {"_HOLE_cont", };

static const StencilDef stencil_table[STENCIL_COUNT] = {
    [STENCIL_ADD] = {code_add, 38, patches_add, 4, 4, 3, holes_add},
    [STENCIL_SUB] = {code_sub, 38, patches_sub, 4, 4, 3, holes_sub},
    [STENCIL_LOAD_CONST] = {code_load_const, 23, patches_load_const, 3, 3, 2, holes_load_const},
    [STENCIL_HALT] = {code_halt, 1, nullptr, 0, 0, 0, nullptr},
    [STENCIL_ENTRY] = {code_entry, 27, patches_entry, 1, 1, 0, holes_entry},
};
