// Generated by pegc — do not edit
#pragma once

#include "PegRuntime.h"
#include "ddcg_ast.h"

#include <string>
   #include <vector>
   #include <optional>
   #include "PegRuntime.h"
   #include "ddcg_ast.h"

using namespace DdcgAst;


class Parser : public peg::PegCursor {
public:
    Parser() = default;

    void init(const char* input, int length);
    bool parse();

    DdcgAst::File* ast = nullptr;


private:
    void setup_skip();

    DdcgAst::SourceLoc Loc() {
        return DdcgAst::SourceLoc{nullptr, line(), col()};
    }


    bool parse_Ddcg();
    bool parse_HeaderBlock(std::vector<DdcgAst::Header*>& headers);
    bool parse_ImportDecl(std::vector<DdcgAst::Import*>& imports);
    bool parse_DestEntry(std::vector<DdcgAst::DestDecl*>& dests, DdcgAst::TypeRef*& ir_root);
    bool parse_VariantList(std::vector<DdcgAst::DestVariant*>& variants);
    bool parse_DestVariant_(DdcgAst::DestVariant* * result);
    bool parse_DestFieldDecl(std::vector<DdcgAst::DestField*>& fields);
    bool parse_AuxiliaryDecl(std::vector<DdcgAst::Aux*>& auxiliaries);
    bool parse_PredicateDecl(std::vector<DdcgAst::Pred*>& predicates);
    bool parse_TypeRefList(std::vector<DdcgAst::TypeRef*>& refs);
    bool parse_TypeRef_(DdcgAst::TypeRef* * result);
    bool parse_RuleDecl(std::vector<DdcgAst::Rule*>& rules);
    bool parse_Block_(std::vector<DdcgAst::Stmt*>& body);
    bool parse_Pattern_(DdcgAst::Pattern* * result);
    bool parse_FieldPat_(std::vector<DdcgAst::FieldPat*>& fields);
    bool parse_Stmt_(std::vector<DdcgAst::Stmt*>& stmts);
    bool parse_Bind_(DdcgAst::Bind* * result);
    bool parse_Expr_(DdcgAst::Expr* * result);
    bool parse_TernaryExpr(DdcgAst::Expr* * result);
    bool parse_LogicalOr(DdcgAst::Expr* * result);
    bool parse_LogicalAnd(DdcgAst::Expr* * result);
    bool parse_Equality(DdcgAst::Expr* * result);
    bool parse_Relational(DdcgAst::Expr* * result);
    bool parse_Additive(DdcgAst::Expr* * result);
    bool parse_Multiplicative(DdcgAst::Expr* * result);
    bool parse_Unary(DdcgAst::Expr* * result);
    bool parse_Postfix(DdcgAst::Expr* * result);
    bool parse_Primary(DdcgAst::Expr* * result);
    bool ident(peg::Span& out);
    bool integer(peg::Span& out);
    bool string_lit(peg::Span& out);

};

