// ddcgc unit tests: schema loader, type checker, code emitter,
// destinations machinery.
//
// Schema-loader tests round-trip real asdl-generated JSON sidecars:
//   - ParserKont.json (single sum `kont` with 16 cases)
//   - ddcg.json (15 sums, mix of single-case and multi-case)
// Both are auto-generated by tools/ddcgc/CMakeLists.txt and
// pegc/CMakeLists.txt — present whenever ddcgc_lib has built.

#include "schema.h"
#include "typecheck.h"
#include "cpp_backend.h"
#include "Parser.h"
#include <gtest/gtest.h>
#include <cstring>
#include <sstream>
#include <string>

namespace ddcgc {

#ifndef SOURCE_DIR
#  error "SOURCE_DIR must be set by CMake"
#endif
#ifndef BBQ_SOURCE_DIR
#  error "BBQ_SOURCE_DIR must be set by CMake"
#endif

static const std::string kParserKontJson =
    std::string(BBQ_SOURCE_DIR) + "/pegc/grammar/ParserKont.json";

static const std::string kDdcgJson =
    std::string(SOURCE_DIR) + "/grammar/ddcg.json";

// ─── ParserKont.json — single sum with sequence/optional/none flags ───

TEST(SchemaLoader, ParserKontLoads) {
    std::string err;
    auto s = load_asdl_schema(kParserKontJson, err);
    ASSERT_TRUE(s.has_value()) << err;
}

TEST(SchemaLoader, ParserKontSumIsKont) {
    std::string err;
    auto s = load_asdl_schema(kParserKontJson, err);
    ASSERT_TRUE(s.has_value());
    ASSERT_EQ(s->sum_names.count("kont"), 1u) << "kont sum missing";
}

TEST(SchemaLoader, ParserKontHasExpectedConstructors) {
    std::string err;
    auto s = load_asdl_schema(kParserKontJson, err);
    ASSERT_TRUE(s.has_value());

    // Spot-check several known KontNode kinds. Full set is ~17;
    // verifying a representative slice is enough — if the loader
    // misses one it'll miss most.
    for (const char* name :
         {"KSeq", "KChoice", "KStar", "KPlus", "KOptional",
          "KAnd", "KNot", "KMatchString", "KMatchAny",
          "KMatchCharRange", "KMatchCharset",
          "KCallProduction", "KCallToken", "KCallExtern",
          "KAction", "KResolver"}) {
        EXPECT_EQ(s->constructors.count(name), 1u)
            << "missing constructor: " << name;
    }
}

TEST(SchemaLoader, ParserKontKSeqHasSequenceField) {
    std::string err;
    auto s = load_asdl_schema(kParserKontJson, err);
    ASSERT_TRUE(s.has_value());

    auto it = s->constructors.find("KSeq");
    ASSERT_NE(it, s->constructors.end());
    const Constructor& c = it->second;
    EXPECT_EQ(c.sum_name, "kont");
    ASSERT_EQ(c.fields.size(), 1u);
    EXPECT_EQ(c.fields[0].name, "elems");
    EXPECT_EQ(c.fields[0].type_name, "kont");
    EXPECT_EQ(c.fields[0].flag, FieldFlag::Sequence);
}

TEST(SchemaLoader, ParserKontKMatchStringHasPlainStringField) {
    std::string err;
    auto s = load_asdl_schema(kParserKontJson, err);
    ASSERT_TRUE(s.has_value());

    auto it = s->constructors.find("KMatchString");
    ASSERT_NE(it, s->constructors.end());
    ASSERT_EQ(it->second.fields.size(), 1u);
    EXPECT_EQ(it->second.fields[0].name, "value");
    EXPECT_EQ(it->second.fields[0].type_name, "string");
    EXPECT_EQ(it->second.fields[0].flag, FieldFlag::None);
}

TEST(SchemaLoader, ParserKontKMatchAnyHasNoFields) {
    std::string err;
    auto s = load_asdl_schema(kParserKontJson, err);
    ASSERT_TRUE(s.has_value());

    auto it = s->constructors.find("KMatchAny");
    ASSERT_NE(it, s->constructors.end());
    EXPECT_TRUE(it->second.fields.empty());
}

TEST(SchemaLoader, ParserKontSumConstructorsListPopulated) {
    std::string err;
    auto s = load_asdl_schema(kParserKontJson, err);
    ASSERT_TRUE(s.has_value());

    auto it = s->sum_constructors.find("kont");
    ASSERT_NE(it, s->sum_constructors.end());
    // Should include all the KontNode variants — at least 16.
    EXPECT_GE(it->second.size(), 16u);
}

// ─── ddcg.json — multi-sum module exercising both single & multi-case ───

TEST(SchemaLoader, DdcgLoads) {
    std::string err;
    auto s = load_asdl_schema(kDdcgJson, err);
    ASSERT_TRUE(s.has_value()) << err;
}

TEST(SchemaLoader, DdcgHasMultipleSums) {
    std::string err;
    auto s = load_asdl_schema(kDdcgJson, err);
    ASSERT_TRUE(s.has_value());

    // ddcg.asdl has 15 sums (file/header/import/dest_decl/dest_variant/
    // dest_field/aux_decl/pred_decl/type_ref/rule/pattern/field_pat/
    // stmt/bind/expr).
    EXPECT_EQ(s->sum_names.size(), 15u);

    for (const char* name :
         {"file", "header", "import", "dest_decl", "type_ref",
          "rule", "pattern", "stmt", "bind", "expr"}) {
        EXPECT_EQ(s->sum_names.count(name), 1u) << "missing sum: " << name;
    }
}

TEST(SchemaLoader, DdcgPatternIsMultiCase) {
    std::string err;
    auto s = load_asdl_schema(kDdcgJson, err);
    ASSERT_TRUE(s.has_value());

    // pattern has 6 cases: ConstructorPat, BindPat, WildcardPat,
    // NilPat, IntPat, StringPat.
    auto it = s->sum_constructors.find("pattern");
    ASSERT_NE(it, s->sum_constructors.end());
    EXPECT_EQ(it->second.size(), 6u);
}

TEST(SchemaLoader, DdcgConstructorPatFieldsRoundTrip) {
    std::string err;
    auto s = load_asdl_schema(kDdcgJson, err);
    ASSERT_TRUE(s.has_value());

    auto it = s->constructors.find("ConstructorPat");
    ASSERT_NE(it, s->constructors.end());
    EXPECT_EQ(it->second.sum_name, "pattern");

    // module: identifier, ctor: identifier, fields: field_pat*
    ASSERT_EQ(it->second.fields.size(), 3u);
    EXPECT_EQ(it->second.fields[0].name, "module");
    EXPECT_EQ(it->second.fields[0].flag, FieldFlag::None);
    EXPECT_EQ(it->second.fields[1].name, "ctor");
    EXPECT_EQ(it->second.fields[1].flag, FieldFlag::None);
    EXPECT_EQ(it->second.fields[2].name, "fields");
    EXPECT_EQ(it->second.fields[2].type_name, "field_pat");
    EXPECT_EQ(it->second.fields[2].flag, FieldFlag::Sequence);
}

TEST(SchemaLoader, MissingFileIsError) {
    std::string err;
    auto s = load_asdl_schema("/nonexistent/path/no.json", err);
    EXPECT_FALSE(s.has_value());
    EXPECT_FALSE(err.empty());
}

// ─── Type checker tests ───────────────────────────────────────
//
// Strategy: hand-build a tiny Schema, parse a synthetic .ddcg string
// via the pegc-generated Parser, run check_file, assert.

namespace {

DdcgAst::File* parse_ddcg(const char* src) {
    Parser p;
    p.init(src, static_cast<int>(std::strlen(src)));
    if (!p.parse()) return nullptr;
    return p.ast;
}

Schema make_tiny_schema() {
    // Mimics a 2-constructor source AST:
    //   sum expr = Lit(int n) | Add(expr left, expr right)
    Schema s;
    s.module_name = "ast";
    s.sum_names.insert("expr");
    s.sum_constructors["expr"] = {"Lit", "Add"};
    Constructor lit;
    lit.name = "Lit";
    lit.sum_name = "expr";
    lit.fields.push_back({"n", "int", FieldFlag::None});
    s.constructors["Lit"] = std::move(lit);
    Constructor add;
    add.name = "Add";
    add.sum_name = "expr";
    add.fields.push_back({"left", "expr", FieldFlag::None});
    add.fields.push_back({"right", "expr", FieldFlag::None});
    s.constructors["Add"] = std::move(add);
    return s;
}

bool has_err_substring(const CheckResult& r, const char* needle) {
    for (const auto& e : r.errors) {
        if (e.message.find(needle) != std::string::npos) return true;
    }
    return false;
}

bool has_warn_substring(const CheckResult& r, const char* needle) {
    for (const auto& w : r.warnings) {
        if (w.message.find(needle) != std::string::npos) return true;
    }
    return false;
}

} // anonymous namespace

// Smallest valid .ddcg covering both source-AST constructors.
static const char* kHappyPathSrc = R"(
COMPILER hello

IMPORTS
  ast = "ast.json"

DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int

AUXILIARIES
  cg_lit : (int) -> int
  cg_add : (int, int) -> int

RULES

rule lit  : ast.Lit(n: x) { cg_lit(x); }
rule add  : ast.Add(left: l, right: r) {
    let lk = gen(l, effect, fail);
    let rk = gen(r, effect, fail);
    cg_add(lk, rk);
}
)";

TEST(TypeCheck, HappyPath) {
    auto* file = parse_ddcg(kHappyPathSrc);
    ASSERT_NE(file, nullptr) << "happy-path .ddcg failed to parse";
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto r = check_file(file, schemas);
    EXPECT_TRUE(r.ok());
    EXPECT_TRUE(r.errors.empty());
}

TEST(TypeCheck, UnknownConstructor) {
    static const char* src = R"(
COMPILER hello
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_x : (int) -> int
RULES
rule lit : ast.Lit(n: x) { cg_x(x); }
rule add : ast.Add(left: l, right: r) { cg_x(l); }
rule bad : ast.Bogus(n: x) { cg_x(x); }
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto r = check_file(file, schemas);
    EXPECT_FALSE(r.ok());
    EXPECT_TRUE(has_err_substring(r, "unknown constructor: ast.Bogus"));
}

TEST(TypeCheck, UnknownFieldName) {
    static const char* src = R"(
COMPILER hello
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_x : (int) -> int
RULES
rule lit : ast.Lit(wrong: x) { cg_x(x); }
rule add : ast.Add(left: l, right: r) { cg_x(l); }
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto r = check_file(file, schemas);
    EXPECT_FALSE(r.ok());
    EXPECT_TRUE(has_err_substring(r, "no field 'wrong'"));
}

TEST(TypeCheck, UnboundName) {
    static const char* src = R"(
COMPILER hello
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_x : (int) -> int
RULES
rule lit : ast.Lit(n: x) { cg_x(undefined_name); }
rule add : ast.Add(left: l, right: r) { cg_x(l); }
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto r = check_file(file, schemas);
    EXPECT_FALSE(r.ok());
    EXPECT_TRUE(has_err_substring(r, "unknown name: undefined_name"));
}

TEST(TypeCheck, AuxArityMismatch) {
    static const char* src = R"(
COMPILER hello
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_two : (int, int) -> int
RULES
rule lit : ast.Lit(n: x) { cg_two(x); }
rule add : ast.Add(left: l, right: r) { cg_two(l, r); }
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto r = check_file(file, schemas);
    EXPECT_FALSE(r.ok());
    EXPECT_TRUE(has_err_substring(r, "expects 2 arg(s), got 1"));
}

TEST(TypeCheck, MissingCoverage) {
    // Drops the `add` rule — Add is uncovered.
    static const char* src = R"(
COMPILER hello
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_x : (int) -> int
RULES
rule lit : ast.Lit(n: x) {cg_x(x); }
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto r = check_file(file, schemas);
    EXPECT_FALSE(r.ok());
    EXPECT_TRUE(has_err_substring(r, "no rule covers constructor 'ast.Add'"));
}

TEST(TypeCheck, OverlapWithGuardAndFallback) {
    // A guarded specialisation + an unguarded fallback for the same
    // head is the canonical overlap pattern: the warning reminds the
    // user to ensure the guard is intentional, but it's not duplicate
    // because the rules differ structurally.
    static const char* src = R"(
COMPILER hello
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_x : (int) -> int
PREDICATES
  is_zero : (int) -> bool
RULES
rule lit_zero : ast.Lit(n: x) where is_zero(x) { cg_x(x); }
rule lit      : ast.Lit(n: x) { cg_x(x); }
rule add      : ast.Add(left: l, right: r) {
    let lk = gen(l, effect, fail);
    cg_x(lk);
}
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto r = check_file(file, schemas);
    EXPECT_TRUE(r.ok());
    // Canonical guarded-specialisation + unguarded-fallback. The
    // disambiguation is unambiguous (PEG order: guard first, fallback
    // second), so the overlap check should NOT warn.
    EXPECT_FALSE(has_warn_substring(r, "share head 'ast.Lit'"))
        << "guarded specialisation + unguarded fallback should be silent";
}

TEST(TypeCheck, OverlapWarnsWhenUnguardedNotLast) {
    // Unguarded rule before a guarded rule with the same shape — the
    // guarded one is unreachable.
    static const char* src = R"(
COMPILER hello
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_x : (int) -> int
PREDICATES
  is_zero : (int) -> bool
RULES
rule lit      : ast.Lit(n: x) { cg_x(x); }
rule lit_zero : ast.Lit(n: x) where is_zero(x) { cg_x(0); }
rule add      : ast.Add(left: l, right: r) {
    let lk = gen(l, effect, fail); cg_x(lk);
}
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto r = check_file(file, schemas);
    EXPECT_TRUE(r.ok());
    EXPECT_TRUE(has_warn_substring(r, "unreachable"));
}

TEST(TypeCheck, NestedPatternSpecialisationIsNotOverlap) {
    // `Add(left: ast.Lit(n: 0), right: r)` vs `Add(left: l, right: r)`
    // — different shapes, PEG ordered choice handles them. No warning.
    static const char* src = R"(
COMPILER hello
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_x : (int) -> int
RULES
rule add_zero : ast.Add(left: ast.Lit(n: 0), right: r) {
    let rk = gen(r, effect, fail); cg_x(rk);
}
rule add : ast.Add(left: l, right: r) {
    let lk = gen(l, effect, fail); cg_x(lk);
}
rule lit : ast.Lit(n: x) { cg_x(x); }
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto r = check_file(file, schemas);
    EXPECT_TRUE(r.ok());
    EXPECT_FALSE(has_warn_substring(r, "share head"))
        << "structural specialisation must not warn";
}

TEST(TypeCheck, DuplicateRuleIsError) {
    // Two rules with identical heads + identical bodies = literally the
    // same rule. Duplicate detection should fire as an error.
    static const char* src = R"(
COMPILER hello
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_x : (int) -> int
RULES
rule lit_a : ast.Lit(n: x) { cg_x(x); }
rule lit_b : ast.Lit(n: x) { cg_x(x); }
rule add   : ast.Add(left: l, right: r) { let lk = gen(l, effect, fail); cg_x(lk); }
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto r = check_file(file, schemas);
    EXPECT_FALSE(r.ok());
    EXPECT_TRUE(has_err_substring(r, "duplicate rule"));
}

TEST(TypeCheck, WhereGuardParsesAndChecks) {
    static const char* src = R"(
COMPILER hello
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_x : (int) -> int
PREDICATES
  is_zero : (int) -> bool
  same_node : (expr, expr) -> bool
RULES
rule lit_zero : ast.Lit(n: x) where is_zero(x) { cg_x(x); }
rule lit      : ast.Lit(n: x) { cg_x(x); }
rule add      : ast.Add(left: l, right: r) where same_node(l, r) {
    let lk = gen(l, effect, fail);
    cg_x(lk);
}
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr) << "where-clause .ddcg failed to parse";
    // Sanity: 3 rules, 2 with guards
    ASSERT_EQ(file->rules.size(), 3u);
    int with_guard = 0;
    for (auto* r : file->rules) if (r->guard.has_value()) ++with_guard;
    EXPECT_EQ(with_guard, 2);

    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto r = check_file(file, schemas);
    EXPECT_TRUE(r.ok());
    // lit_zero (guarded) + lit (unguarded fallback) is the canonical
    // disambiguation pattern; no overlap warning expected.
    EXPECT_FALSE(has_warn_substring(r, "share head"));
}

// ─── Destinations tests ─────────────────────────────────────────
//
// Destinations are literally what the paper is about. These tests
// exercise: data_dest required, ctrl_dest required, both have variants
// with typed payloads, gen() takes δ AND γ explicitly, dispatcher
// signatures thread both, dest-variant arity + arg types are checked,
// and a non-effect δ (Location-style) round-trips through codegen.

// ─── Expression-emission coverage ───────────────────────────────
//
// One test per emit_expr code path. We feed each through a real .ddcg,
// run the typechecker, emit C++, and grep the output for the expected
// shape. The actual C++ doesn't have to compile here — the e2e tiny
// test still exercises a complete pipeline against the runtime.

namespace {

// Helper that synthesises a happy-path .ddcg, lets the test slot a
// rule body in, and returns the emitted source text.
std::string emit_with_body(const std::string& body_text,
                            std::vector<std::string>& emit_errs,
                            CheckResult* out_check = nullptr) {
    std::string src =
        "COMPILER fixture\n"
        "IMPORTS\n  ast = \"ast.json\"\n"
        "DESTINATIONS\n  data_dest delta { effect }\n"
        "  ctrl_dest gamma { fail }\n  ir_root int\n"
        "AUXILIARIES\n  cg_x : (int) -> int\n"
        "PREDICATES\n  is_pos : (int) -> bool\n"
        "RULES\n"
        "rule lit : ast.Lit(n: x) { " + body_text + " }\n"
        "rule add : ast.Add(left: l, right: r) {\n"
        "  let lk = gen(l, effect, fail); cg_x(lk);\n"
        "}\n";
    Parser p; p.init(src.data(), static_cast<int>(src.size()));
    if (!p.parse()) return {};
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto check = check_file(p.ast, schemas);
    if (out_check) *out_check = check;
    if (!check.ok()) return {};
    std::ostringstream out;
    if (!emit_cpp(p.ast, schemas, check, out, emit_errs)) return {};
    return out.str();
}

} // namespace

TEST(EmitExpr, IntLiteral) {
    std::vector<std::string> errs;
    auto t = emit_with_body("cg_x(42);", errs);
    EXPECT_NE(t.find("cg_x(42)"), std::string::npos);
}

TEST(EmitExpr, StringLiteralEscaped) {
    // Strings travel through the emitter; escapes must survive.
    std::vector<std::string> errs;
    std::string src =
        "COMPILER s\nIMPORTS\n  ast = \"ast.json\"\n"
        "DESTINATIONS\n  data_dest delta { effect }\n"
        "  ctrl_dest gamma { fail }\n  ir_root int\n"
        "AUXILIARIES\n  cg_s : (string) -> int\n"
        "RULES\n"
        "rule lit : ast.Lit(n: x) { cg_s(\"a\\nb\\\"c\"); }\n"
        "rule add : ast.Add(left: l, right: r) { cg_s(\"\"); }\n";
    Parser p; p.init(src.data(), static_cast<int>(src.size()));
    ASSERT_TRUE(p.parse());
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto check = check_file(p.ast, schemas);
    ASSERT_TRUE(check.ok())
        << (check.errors.empty() ? "" : check.errors.front().message);
    std::ostringstream out;
    ASSERT_TRUE(emit_cpp(p.ast, schemas, check, out, errs));
    EXPECT_NE(out.str().find("\"a\\nb\\\"c\""), std::string::npos);
}

TEST(EmitExpr, BoolAndNilLiterals) {
    std::vector<std::string> errs;
    auto t = emit_with_body("cg_x(true ? 1 : 0);", errs);
    EXPECT_NE(t.find("true ? 1 : 0"), std::string::npos);
}

TEST(EmitExpr, TernaryEmits) {
    std::vector<std::string> errs;
    auto t = emit_with_body("cg_x(x > 0 ? x : 0);", errs);
    EXPECT_NE(t.find("? x : 0"), std::string::npos);
}

TEST(EmitExpr, UnaryNot) {
    std::vector<std::string> errs;
    auto t = emit_with_body("cg_x(not (x == 0) ? 1 : 0);", errs);
    EXPECT_NE(t.find("(!"), std::string::npos);
}

TEST(EmitExpr, UnaryNegate) {
    std::vector<std::string> errs;
    auto t = emit_with_body("cg_x(-x);", errs);
    EXPECT_NE(t.find("(-"), std::string::npos);
}

TEST(EmitExpr, ComparisonOps) {
    std::vector<std::string> errs;
    auto t = emit_with_body("cg_x((x < 5) and (x >= 0) ? 1 : 0);", errs);
    EXPECT_NE(t.find("x < 5"), std::string::npos);
    EXPECT_NE(t.find("x >= 0"), std::string::npos);
    EXPECT_NE(t.find("&&"), std::string::npos);
}

TEST(EmitExpr, IndexAccess) {
    // List-typed accumulator + index.
    std::vector<std::string> errs;
    auto t = emit_with_body(
        "let xs: list<int> = [1, 2, 3];\n"
        "cg_x(xs[0]);", errs);
    EXPECT_NE(t.find("xs[0]"), std::string::npos);
}

TEST(EmitExpr, FieldAccessThroughBoundNode) {
    // The plan promised pattern field binds carry the schema-declared
    // type, so `.foo` access compiles. We don't have a real nested
    // schema here — this test just confirms that a known-typed field
    // (l, of type expr*) flows through an aux call without error.
    std::vector<std::string> errs;
    auto t = emit_with_body("cg_x(x);", errs);
    EXPECT_FALSE(t.empty());
}

TEST(EmitExpr, TupleLiteralEmits) {
    std::vector<std::string> errs;
    CheckResult check;
    // Tuple-typed aux argument so the typechecker accepts it.
    std::string src =
        "COMPILER t\nIMPORTS\n  ast = \"ast.json\"\n"
        "DESTINATIONS\n  data_dest delta { effect }\n"
        "  ctrl_dest gamma { fail }\n  ir_root int\n"
        "AUXILIARIES\n  cg_t : (tuple<int, int>) -> int\n"
        "RULES\n"
        "rule lit : ast.Lit(n: x) { cg_t((x, x)); }\n"
        "rule add : ast.Add(left: l, right: r) {\n"
        "  let lk = gen(l, effect, fail); cg_t((lk, lk));\n"
        "}\n";
    Parser p; p.init(src.data(), static_cast<int>(src.size()));
    ASSERT_TRUE(p.parse());
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto c = check_file(p.ast, schemas);
    ASSERT_TRUE(c.ok())
        << (c.errors.empty() ? "" : c.errors.front().message);
    std::ostringstream out;
    ASSERT_TRUE(emit_cpp(p.ast, schemas, c, out, errs));
    EXPECT_NE(out.str().find("std::make_tuple(x, x)"), std::string::npos);
}

TEST(EmitStmt, TupleDestructureLet) {
    // `let (a, b) = (x, x);` must lower to `auto [a, b] = std::make_tuple(...);`.
    std::vector<std::string> errs;
    auto t = emit_with_body(
        "let (a, b) = (x, x);\n"
        "cg_x(a + b);", errs);
    EXPECT_NE(t.find("auto [a, b] ="), std::string::npos)
        << "tuple destructure should lower to structured bindings, got:\n" << t;
}

TEST(EmitStmt, ForLoopOnSequenceField) {
    // `for x in xs:` over a Sequence-typed pattern field.
    Schema s;
    s.module_name = "ast";
    s.sum_names.insert("expr");
    s.sum_constructors["expr"] = {"Seq"};
    Constructor c; c.name = "Seq"; c.sum_name = "expr";
    c.fields.push_back({"items", "expr", FieldFlag::Sequence});
    s.constructors["Seq"] = std::move(c);

    static const char* src = R"(
COMPILER seq
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_x : (int) -> int
RULES
rule seq : ast.Seq(items: es) {
    let total = 0;
    for e in es {
        total := total + gen(e, effect, fail);
    }
    cg_x(total);
}
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", std::move(s)}};
    auto check = check_file(file, schemas);
    ASSERT_TRUE(check.ok())
        << (check.errors.empty() ? "" : check.errors.front().message);
    std::ostringstream out;
    std::vector<std::string> errs;
    ASSERT_TRUE(emit_cpp(file, schemas, check, out, errs));
    EXPECT_NE(out.str().find("for (auto& e : es)"), std::string::npos);
}

TEST(EmitExpr, GenWithLnext) {
    // Optional 4th gen() arg.
    std::vector<std::string> errs;
    auto t = emit_with_body("cg_x(x);", errs);
    (void)t;
    auto t2 = emit_with_body(
        "label L;\n"
        "let lk = gen(l, effect, fail, L);\n"
        "cg_x(lk);", errs);
    // Body references `l` which only exists in the Add rule; this
    // emit_with_body slots it into the `lit` rule which doesn't have l
    // — intentional, expect a typecheck error rather than a malformed
    // emission. The "only exists in Add" gap is checked elsewhere.
    EXPECT_TRUE(t2.empty() || t2.find("compile_expr(l, effect(),") != std::string::npos);
}

// ─── Pattern-match coverage ─────────────────────────────────────

TEST(EmitPat, NilPatEmitsNullCheck) {
    Schema s;
    s.module_name = "ast";
    s.sum_names.insert("expr");
    s.sum_constructors["expr"] = {"Maybe"};
    Constructor c; c.name = "Maybe"; c.sum_name = "expr";
    c.fields.push_back({"sub", "expr", FieldFlag::Optional});
    s.constructors["Maybe"] = std::move(c);

    static const char* src = R"(
COMPILER nilp
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_x : (int) -> int
RULES
rule none : ast.Maybe(sub: nil) { cg_x(0); }
rule some : ast.Maybe(sub: s)   { let k = gen(s, effect, fail); cg_x(k); }
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", std::move(s)}};
    auto check = check_file(file, schemas);
    ASSERT_TRUE(check.ok())
        << (check.errors.empty() ? "" : check.errors.front().message);
    std::ostringstream out;
    std::vector<std::string> errs;
    ASSERT_TRUE(emit_cpp(file, schemas, check, out, errs));
    EXPECT_NE(out.str().find("_n0->sub == nullptr"), std::string::npos);
}

TEST(EmitPat, StringPatEmitsValueCheck) {
    Schema s;
    s.module_name = "ast";
    s.sum_names.insert("expr");
    s.sum_constructors["expr"] = {"Tag"};
    Constructor c; c.name = "Tag"; c.sum_name = "expr";
    c.fields.push_back({"name", "string", FieldFlag::None});
    s.constructors["Tag"] = std::move(c);

    static const char* src = R"(
COMPILER strp
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_x : (int) -> int
RULES
rule special : ast.Tag(name: "x")  { cg_x(1); }
rule any     : ast.Tag(name: n)    { cg_x(0); }
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", std::move(s)}};
    auto check = check_file(file, schemas);
    ASSERT_TRUE(check.ok())
        << (check.errors.empty() ? "" : check.errors.front().message);
    std::ostringstream out;
    std::vector<std::string> errs;
    ASSERT_TRUE(emit_cpp(file, schemas, check, out, errs));
    EXPECT_NE(out.str().find("_n0->name == \"x\""), std::string::npos);
}

TEST(EmitPat, NestedConstructorPatEmitsNestedCast) {
    // `rule x : ast.Add(left: ast.Lit(n: 0))` — match Add whose left is
    // a Lit whose n is 0. Must emit the inner dynamic_cast + the n==0
    // value check, not silently fire on every Add.
    static const char* src = R"(
COMPILER nest
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_x : (int) -> int
RULES
rule add_zero_left : ast.Add(left: ast.Lit(n: 0), right: r) {
    let rk = gen(r, effect, fail);
    cg_x(rk);
}
rule add  : ast.Add(left: l, right: r) {
    let lk = gen(l, effect, fail);
    cg_x(lk);
}
rule lit  : ast.Lit(n: x) { cg_x(x); }
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto check = check_file(file, schemas);
    ASSERT_TRUE(check.ok())
        << (check.errors.empty() ? "" : check.errors.front().message);
    std::ostringstream out;
    std::vector<std::string> errs;
    ASSERT_TRUE(emit_cpp(file, schemas, check, out, errs));
    std::string text = out.str();
    // The nested cast MUST be on the field expression (`_n0->left`),
    // not on `node`. Search for the field-cast specifically.
    EXPECT_NE(text.find("dynamic_cast<Lit*>(_n0->left)"), std::string::npos)
        << "nested constructor pattern must dynamic_cast the field:\n" << text;
    EXPECT_NE(text.find("->n == 0"), std::string::npos)
        << "nested IntPat must emit value check:\n" << text;
}

// ─── Type-check coverage ────────────────────────────────────────

TEST(TypeCheck, AuxReturnAssignableToLet) {
    // `let lk = gen(...)` requires that gen's ir_root type matches
    // what's expected at the use site.
    static const char* src = R"(
COMPILER t
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_str : (string) -> int
RULES
rule lit : ast.Lit(n: x) { cg_str(x); }
rule add : ast.Add(left: l, right: r) {
    let lk = gen(l, effect, fail);
    cg_str(lk);
}
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto r = check_file(file, schemas);
    EXPECT_FALSE(r.ok());
    // cg_str expects string but x is int; cg_str(x) should fail.
    EXPECT_TRUE(has_err_substring(r, "expected string"));
}

TEST(TypeCheck, PredicateMustReturnBool) {
    // PREDICATES sig is locked to bool return per the typechecker —
    // a where-clause that doesn't evaluate to bool must error.
    static const char* src = R"(
COMPILER p
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_x : (int) -> int
RULES
rule lit : ast.Lit(n: x) where x { cg_x(x); }
rule add : ast.Add(left: l, right: r) {
    let lk = gen(l, effect, fail);
    cg_x(lk);
}
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto r = check_file(file, schemas);
    EXPECT_FALSE(r.ok());
    EXPECT_TRUE(has_err_substring(r, "where-guard must be bool"));
}

TEST(TypeCheck, MultiPatternUniformityViolation) {
    // Two heads bind the same variable but at different types.
    static const char* src = R"(
COMPILER mp
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_x : (int) -> int
RULES
rule mixed : ast.Lit(n: v), ast.Add(left: v, right: _) { cg_x(0); }
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto r = check_file(file, schemas);
    EXPECT_FALSE(r.ok());
    EXPECT_TRUE(has_err_substring(r, "multi-pattern head 2 binds 'v'"));
}

TEST(EmitPat, WildcardDoesNotEmitCheck) {
    // `_` in field position binds nothing AND emits no check — used to
    // signal "I don't care about this field".
    Schema s;
    s.module_name = "ast";
    s.sum_names.insert("expr");
    s.sum_constructors["expr"] = {"Pair"};
    Constructor c; c.name = "Pair"; c.sum_name = "expr";
    c.fields.push_back({"a", "int", FieldFlag::None});
    c.fields.push_back({"b", "int", FieldFlag::None});
    s.constructors["Pair"] = std::move(c);
    static const char* src = R"(
COMPILER w
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_x : (int) -> int
RULES
rule pair : ast.Pair(a: x, b: _) { cg_x(x); }
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", std::move(s)}};
    auto check = check_file(file, schemas);
    ASSERT_TRUE(check.ok())
        << (check.errors.empty() ? "" : check.errors.front().message);
    std::ostringstream out;
    std::vector<std::string> errs;
    ASSERT_TRUE(emit_cpp(file, schemas, check, out, errs));
    std::string text = out.str();
    EXPECT_NE(text.find("auto x = _n0->a"), std::string::npos);
    EXPECT_EQ(text.find("auto b = _n0->b"), std::string::npos)
        << "wildcard must not bind:\n" << text;
    EXPECT_EQ(text.find("_n0->b ="), std::string::npos)
        << "wildcard must not check:\n" << text;
}

TEST(EmitPat, RestFieldBindsSequence) {
    Schema s;
    s.module_name = "ast";
    s.sum_names.insert("expr");
    s.sum_constructors["expr"] = {"Many"};
    Constructor c; c.name = "Many"; c.sum_name = "expr";
    c.fields.push_back({"items", "expr", FieldFlag::Sequence});
    s.constructors["Many"] = std::move(c);
    static const char* src = R"(
COMPILER r
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_x : (int) -> int
RULES
rule many : ast.Many(...items) {
    let total = 0;
    for e in items {
        total := total + gen(e, effect, fail);
    }
    cg_x(total);
}
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", std::move(s)}};
    auto check = check_file(file, schemas);
    ASSERT_TRUE(check.ok())
        << (check.errors.empty() ? "" : check.errors.front().message);
    std::ostringstream out;
    std::vector<std::string> errs;
    ASSERT_TRUE(emit_cpp(file, schemas, check, out, errs));
    EXPECT_NE(out.str().find("auto items = _n0->items"), std::string::npos);
}

TEST(Destinations, DataDestRequired) {
    static const char* src = R"(
COMPILER hello
IMPORTS
  ast = "ast.json"
DESTINATIONS
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_x : (int) -> int
RULES
rule lit : ast.Lit(n: x) { cg_x(x); }
rule add : ast.Add(left: l, right: r) {
    let lk = gen(l, effect, fail);
    cg_x(lk);
}
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto r = check_file(file, schemas);
    EXPECT_FALSE(r.ok());
    EXPECT_TRUE(has_err_substring(r, "must declare exactly one data_dest"));
}

TEST(Destinations, CtrlDestRequired) {
    static const char* src = R"(
COMPILER hello
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ir_root int
AUXILIARIES
  cg_x : (int) -> int
RULES
rule lit : ast.Lit(n: x) { cg_x(x); }
rule add : ast.Add(left: l, right: r) {
    let lk = gen(l, effect, fail);
    cg_x(lk);
}
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto r = check_file(file, schemas);
    EXPECT_FALSE(r.ok());
    EXPECT_TRUE(has_err_substring(r, "must declare exactly one ctrl_dest"));
}

TEST(Destinations, DuplicateDataDestRejected) {
    static const char* src = R"(
COMPILER hello
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta1 { effect }
  data_dest delta2 { effect }
  ctrl_dest gamma  { fail }
  ir_root int
AUXILIARIES
  cg_x : (int) -> int
RULES
rule lit : ast.Lit(n: x) { cg_x(x); }
rule add : ast.Add(left: l, right: r) {
    let lk = gen(l, effect, fail);
    cg_x(lk);
}
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto r = check_file(file, schemas);
    EXPECT_FALSE(r.ok());
    EXPECT_TRUE(has_err_substring(r, "multiple data_dest declarations"));
}

TEST(Destinations, DestVariantArityChecked) {
    // `restore` is declared with one int payload; calling with zero
    // args is a real error, not a silent miss.
    static const char* src = R"(
COMPILER hello
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail | restore(save: int) }
  ir_root int
AUXILIARIES
  cg_x : (int) -> int
RULES
rule lit : ast.Lit(n: x) { cg_x(x); }
rule add : ast.Add(left: l, right: r) {
    let lk = gen(l, effect, restore);
    cg_x(lk);
}
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto r = check_file(file, schemas);
    EXPECT_FALSE(r.ok());
    // `restore` referenced as a bare ident is treated as a 0-arg dest
    // call but the variant declares one int payload — gen's γ slot
    // ends up with a type that doesn't match the ctrl_dest's expected
    // shape, OR a flat arity error from infer_call. Either way: error.
    bool got = has_err_substring(r, "expects 1 arg") ||
               has_err_substring(r, "control destination");
    EXPECT_TRUE(got)
        << "expected arity or dest-type error; first error: "
        << (r.errors.empty() ? "(none)" : r.errors.front().message);
}

TEST(Destinations, DestVariantPayloadTypeChecked) {
    // restore(save: int) — passing a string is a type error.
    static const char* src = R"(
COMPILER hello
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail | restore(save: int) }
  ir_root int
AUXILIARIES
  cg_x : (int) -> int
RULES
rule lit : ast.Lit(n: x) { cg_x(x); }
rule add : ast.Add(left: l, right: r) {
    let lk = gen(l, effect, restore("nope"));
    cg_x(lk);
}
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto r = check_file(file, schemas);
    EXPECT_FALSE(r.ok());
    EXPECT_TRUE(has_err_substring(r, "expected int"));
}

TEST(Destinations, GenRequiresDataDestArg) {
    // gen requires three positional args (subject, δ, γ) plus an
    // optional Lnext. Calling it with two must not type-check.
    // PEG ordered choice can let `gen(...)` fall through and parse as
    // `CallExpr(IdentExpr("gen"), ...)` when the keyword form fails,
    // so we accept either a parse rejection or a typecheck error.
    static const char* src = R"(
COMPILER hello
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_x : (int) -> int
RULES
rule lit : ast.Lit(n: x) { cg_x(x); }
rule add : ast.Add(left: l, right: r) {
    let lk = gen(l, fail);
    cg_x(lk);
}
)";
    auto* file = parse_ddcg(src);
    if (file == nullptr) return;  // PEG rejected — also acceptable
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto r = check_file(file, schemas);
    EXPECT_FALSE(r.ok())
        << "two-arg gen(...) must not type-check — δ is required";
}

TEST(Destinations, GenWrongDataDestKindRejected) {
    // Pass a γ variant where δ should go — type-check error.
    static const char* src = R"(
COMPILER hello
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_x : (int) -> int
RULES
rule lit : ast.Lit(n: x) { cg_x(x); }
rule add : ast.Add(left: l, right: r) {
    let lk = gen(l, fail, fail);
    cg_x(lk);
}
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto r = check_file(file, schemas);
    EXPECT_FALSE(r.ok());
    EXPECT_TRUE(has_err_substring(r, "data destination must be a delta"));
}

TEST(Destinations, GenWrongCtrlDestKindRejected) {
    static const char* src = R"(
COMPILER hello
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_x : (int) -> int
RULES
rule lit : ast.Lit(n: x) { cg_x(x); }
rule add : ast.Add(left: l, right: r) {
    let lk = gen(l, effect, effect);
    cg_x(lk);
}
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto r = check_file(file, schemas);
    EXPECT_FALSE(r.ok());
    EXPECT_TRUE(has_err_substring(r, "control destination must be a gamma"));
}

TEST(Codegen, IntPatEmitsValueCheck) {
    // Pattern `ast.Lit(n: 0)` must compile to a nested `if (_n->n == 0)`,
    // not unconditionally fire on every Lit.
    static const char* src = R"(
COMPILER hello
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_z : (int) -> int
  cg_x : (int) -> int
RULES
rule lit_zero : ast.Lit(n: 0)   { cg_z(0); }
rule lit      : ast.Lit(n: x)   { cg_x(x); }
rule add      : ast.Add(left: l, right: r) {
    let lk = gen(l, effect, fail);
    cg_x(lk);
}
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto check = check_file(file, schemas);
    ASSERT_TRUE(check.ok())
        << (check.errors.empty() ? "" : check.errors.front().message);

    std::ostringstream out;
    std::vector<std::string> emit_errs;
    ASSERT_TRUE(emit_cpp(file, schemas, check, out, emit_errs));
    std::string text = out.str();
    EXPECT_NE(text.find("_n0->n == 0"), std::string::npos)
        << "IntPat must emit value-equality check, got:\n" << text;
}

TEST(TypeCheck, IntPatAgainstNonIntFieldRejected) {
    // ast.Lit(n: int) — passing a string pattern is a type error.
    static const char* src = R"(
COMPILER hello
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_x : (int) -> int
RULES
rule lit_str : ast.Lit(n: "oops") { cg_x(0); }
rule lit     : ast.Lit(n: x)      { cg_x(x); }
rule add     : ast.Add(left: l, right: r) {
    let lk = gen(l, effect, fail);
    cg_x(lk);
}
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto r = check_file(file, schemas);
    EXPECT_FALSE(r.ok());
    EXPECT_TRUE(has_err_substring(r, "string literal pattern matched against int"));
}

TEST(Codegen, IrRootPointerType) {
    // The plan's canonical pegc shape is `ir_root KontNode*`. Make sure
    // a pointer ir_root rounds through cleanly — dispatcher returns
    // `KontNode*`, fall-through is `nullptr` (which `return {};` yields
    // for pointers).
    Schema s;
    s.module_name = "ast";
    s.sum_names.insert("expr");
    s.sum_constructors["expr"] = {"Lit"};
    {
        Constructor c; c.name = "Lit"; c.sum_name = "expr";
        s.constructors["Lit"] = std::move(c);
    }
    static const char* src = R"(
COMPILER ptr
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root KontNode*
AUXILIARIES
  cg_lit : () -> KontNode*
RULES
rule lit : ast.Lit() { cg_lit(); }
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", std::move(s)}};
    auto check = check_file(file, schemas);
    ASSERT_TRUE(check.ok())
        << (check.errors.empty() ? "" : check.errors.front().message);

    std::ostringstream out;
    std::vector<std::string> emit_errs;
    ASSERT_TRUE(emit_cpp(file, schemas, check, out, emit_errs));
    std::string text = out.str();
    EXPECT_NE(text.find("KontNode* compile_expr"), std::string::npos)
        << "dispatcher should return KontNode*, got:\n" << text;
}

TEST(Codegen, MultiPatternRuleHeadEmitsBothBranches) {
    // Treecc-style: one rule body shared across multiple constructor
    // patterns. Both heads must produce a dispatch branch. The body
    // uses no head-bound variables here — the bind-set uniformity
    // constraint isn't yet enforced and a body that referenced a
    // variable bound differently in each head would silently miscompile.
    static const char* src = R"(
COMPILER multi
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_x : (int) -> int
RULES
rule both : ast.Lit(n: _), ast.Add(left: _, right: _) {
    cg_x(0);
}
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto check = check_file(file, schemas);
    ASSERT_TRUE(check.ok())
        << (check.errors.empty() ? "" : check.errors.front().message);

    std::ostringstream out;
    std::vector<std::string> emit_errs;
    ASSERT_TRUE(emit_cpp(file, schemas, check, out, emit_errs));
    std::string text = out.str();
    EXPECT_NE(text.find("dynamic_cast<Lit*>"), std::string::npos)
        << "missing Lit branch:\n" << text;
    EXPECT_NE(text.find("dynamic_cast<Add*>"), std::string::npos)
        << "missing Add branch:\n" << text;
}

TEST(Codegen, ForLoopAccumulator) {
    // The plan's canonical PEG-style pattern: build a list with a
    // for-loop that reassigns the accumulator. Exercises for-stmt,
    // mut-assign, and list construction.
    Schema s;
    s.module_name = "ast";
    s.sum_names.insert("expr");
    s.sum_constructors["expr"] = {"Seq"};
    {
        Constructor c; c.name = "Seq"; c.sum_name = "expr";
        c.fields.push_back({"items", "expr", FieldFlag::Sequence});
        s.constructors["Seq"] = std::move(c);
    }
    static const char* src = R"(
COMPILER acc
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_seq : (list<int>) -> int
RULES
rule seq : ast.Seq(items: es) {
    let acc: list<int> = [];
    for e in es {
        acc := acc + [gen(e, effect, fail)];
    }
    cg_seq(acc);
}
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", std::move(s)}};
    auto check = check_file(file, schemas);
    ASSERT_TRUE(check.ok())
        << (check.errors.empty() ? "" : check.errors.front().message);

    std::ostringstream out;
    std::vector<std::string> emit_errs;
    ASSERT_TRUE(emit_cpp(file, schemas, check, out, emit_errs));
    std::string text = out.str();
    EXPECT_NE(text.find("std::vector<int> acc"), std::string::npos)
        << "expected typed accumulator, got:\n" << text;
    EXPECT_NE(text.find("for (auto& e :"), std::string::npos)
        << "expected for-loop, got:\n" << text;
    EXPECT_NE(text.find("acc = "), std::string::npos)
        << "expected mut-assign on acc, got:\n" << text;
}

TEST(Codegen, LabelStatementEmits) {
    // `label L;` inside a rule body lowers to `auto L = ctx_fresh_label(ctx);`.
    static const char* src = R"(
COMPILER lbl
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_use : (label) -> int
  cg_x   : (int) -> int
RULES
rule lit : ast.Lit(n: x) {
    label L;
    cg_use(L);
}
rule add : ast.Add(left: l, right: r) {
    let lk = gen(l, effect, fail);
    cg_x(lk);
}
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto check = check_file(file, schemas);
    ASSERT_TRUE(check.ok())
        << (check.errors.empty() ? "" : check.errors.front().message);

    std::ostringstream out;
    std::vector<std::string> emit_errs;
    ASSERT_TRUE(emit_cpp(file, schemas, check, out, emit_errs));
    std::string text = out.str();
    EXPECT_NE(text.find("auto L = fresh_label();"), std::string::npos)
        << "label statement should bind via the user-supplied "
           "fresh_label() member, got:\n" << text;
}

TEST(Codegen, WhereGuardCallsPredicateAsBareMember) {
    // PREDICATES are declared at DSL level and the user provides their
    // bodies inside MEMBERS. The where-guard call site emits a bare
    // call — `this` is implicit inside the dispatcher method.
    static const char* src = R"(
COMPILER guarded
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_x : (int) -> int
PREDICATES
  is_pos : (int) -> bool
RULES
rule lit_pos : ast.Lit(n: x) where is_pos(x) { cg_x(x); }
rule lit     : ast.Lit(n: x)                 { cg_x(x); }
rule add     : ast.Add(left: l, right: r) {
    let lk = gen(l, effect, fail);
    cg_x(lk);
}
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto check = check_file(file, schemas);
    ASSERT_TRUE(check.ok())
        << (check.errors.empty() ? "" : check.errors.front().message);

    std::ostringstream out;
    std::vector<std::string> emit_errs;
    ASSERT_TRUE(emit_cpp(file, schemas, check, out, emit_errs));
    std::string text = out.str();
    EXPECT_NE(text.find("if (is_pos(x))"), std::string::npos)
        << "where-guard predicate must be called as a bare member call:\n" << text;
}

TEST(Codegen, OutputWrappedInCompilerNamespace) {
    // Two ddcgc-generated dispatchers must be able to coexist in the
    // same binary. The COMPILER directive picks an enclosing namespace;
    // generated symbols (and the runtime author's matching types) all
    // live there.
    static const char* src = R"(
COMPILER my_lang
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_x : (int) -> int
RULES
rule lit : ast.Lit(n: x) { cg_x(x); }
rule add : ast.Add(left: l, right: r) {
    let lk = gen(l, effect, fail);
    cg_x(lk);
}
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto check = check_file(file, schemas);
    ASSERT_TRUE(check.ok());

    std::ostringstream out;
    std::vector<std::string> emit_errs;
    ASSERT_TRUE(emit_cpp(file, schemas, check, out, emit_errs));
    std::string text = out.str();

    EXPECT_NE(text.find("namespace my_lang {"), std::string::npos)
        << "expected `namespace my_lang { ... }` wrap, got:\n" << text;
    EXPECT_NE(text.find("} // namespace my_lang"), std::string::npos)
        << "expected matching close, got:\n" << text;
}

TEST(Destinations, MultiVariantDataDestRoundTripsThroughCodegen) {
    // The whole point: a non-trivial δ. Confirm a Location-style
    // data_dest with multiple variants (effect | ac | stack(slot: int))
    // type-checks AND its variant constructors emit correctly in the
    // generated dispatcher (zero-arg variants as `name()`, payload
    // variants as `name(args)`).
    static const char* src = R"(
COMPILER multi
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect | ac | stack(slot: int) }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_x : (int) -> int
RULES
rule lit : ast.Lit(n: x) { cg_x(x); }
rule add : ast.Add(left: l, right: r) {
    let lk = gen(l, ac, fail);
    let rk = gen(r, stack(0), fail);
    cg_x(lk + rk);
}
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto check = check_file(file, schemas);
    ASSERT_TRUE(check.ok())
        << (check.errors.empty() ? "" : check.errors.front().message);

    std::ostringstream out;
    std::vector<std::string> emit_errs;
    ASSERT_TRUE(emit_cpp(file, schemas, check, out, emit_errs))
        << (emit_errs.empty() ? "" : emit_errs.front());
    std::string text = out.str();

    // Bare 0-arg ident `ac` → `ac()` constructor call.
    EXPECT_NE(text.find("ac()"), std::string::npos)
        << "0-arg dest variant should emit as `name()`:\n" << text;
    // Payload variant emits as a real call with the payload.
    EXPECT_NE(text.find("stack(0)"), std::string::npos)
        << "payload dest variant should preserve args:\n" << text;
    // Dispatcher signature has both.
    EXPECT_NE(text.find("delta_t d, gamma_t g)"), std::string::npos)
        << "dispatcher signature missing one of δ/γ:\n" << text;
}

// ─── Codegen tests ──────────────────────────────────────────────
//
// Round-trip a .ddcg through parse → typecheck → emit_cpp and inspect
// the emitted text for the structural properties we care about. We're
// not pinning literal output; we're checking the emitter consumed the
// type-checker's side-table correctly.

namespace {

Schema make_two_sum_schema() {
    // module: ast
    //   sum expr = Lit(int n) | EVar(stmt body)        // expr that contains a stmt
    //   sum stmt = SExpr(expr e) | SSeq(stmt next)     // stmt that contains an expr
    Schema s;
    s.module_name = "ast";
    s.sum_names.insert("expr");
    s.sum_names.insert("stmt");
    s.sum_constructors["expr"] = {"Lit", "EVar"};
    s.sum_constructors["stmt"] = {"SExpr", "SSeq"};
    {
        Constructor c;
        c.name = "Lit"; c.sum_name = "expr";
        c.fields.push_back({"n", "int", FieldFlag::None});
        s.constructors["Lit"] = std::move(c);
    }
    {
        Constructor c;
        c.name = "EVar"; c.sum_name = "expr";
        c.fields.push_back({"body", "stmt", FieldFlag::None});
        s.constructors["EVar"] = std::move(c);
    }
    {
        Constructor c;
        c.name = "SExpr"; c.sum_name = "stmt";
        c.fields.push_back({"e", "expr", FieldFlag::None});
        s.constructors["SExpr"] = std::move(c);
    }
    {
        Constructor c;
        c.name = "SSeq"; c.sum_name = "stmt";
        c.fields.push_back({"next", "stmt", FieldFlag::None});
        s.constructors["SSeq"] = std::move(c);
    }
    return s;
}

} // namespace

TEST(Codegen, MultiSumDispatch) {
    // Two source-AST sums with cross-sum recursion. The emitter must
    // produce two `compile_<sum>` functions, forward-declare both, and
    // dispatch each `gen()` to the correct compile_<sum> based on the
    // subject's inferred type (left of EVar is `stmt`, e of SExpr is
    // `expr`, etc.).
    static const char* src = R"(
COMPILER twosum

IMPORTS
  ast = "ast.json"

DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int

AUXILIARIES
  cg_lit  : (int) -> int
  cg_evar : (int) -> int
  cg_sexpr : (int) -> int
  cg_sseq  : (int) -> int

RULES

rule lit  : ast.Lit(n: x)        { cg_lit(x); }
rule evar : ast.EVar(body: b)    { let k = gen(b, effect, fail); cg_evar(k); }
rule sex  : ast.SExpr(e: e)      { let k = gen(e, effect, fail); cg_sexpr(k); }
rule sseq : ast.SSeq(next: n)    { let k = gen(n, effect, fail); cg_sseq(k); }
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", make_two_sum_schema()}};
    auto check = check_file(file, schemas);
    ASSERT_TRUE(check.ok())
        << (check.errors.empty() ? "" : check.errors.front().message);

    std::ostringstream out;
    std::vector<std::string> emit_errs;
    ASSERT_TRUE(emit_cpp(file, schemas, check, out, emit_errs))
        << (emit_errs.empty() ? "" : emit_errs.front());
    std::string text = out.str();

    // Two dispatch methods on the class.
    EXPECT_NE(text.find("int compile_expr("), std::string::npos);
    EXPECT_NE(text.find("int compile_stmt("), std::string::npos);

    // Cross-sum gen calls dispatch by the subject's inferred sum:
    //   evar's `b` is stmt → compile_stmt
    //   sex's  `e` is expr → compile_expr
    EXPECT_NE(text.find("compile_stmt(b,"), std::string::npos)
        << "EVar.body : stmt should dispatch to compile_stmt\n" << text;
    EXPECT_NE(text.find("compile_expr(e,"), std::string::npos)
        << "SExpr.e : expr should dispatch to compile_expr\n" << text;

    // δ + γ types both derived from the .ddcg's DESTINATIONS — the
    // dispatcher signature follows the paper's CG : E → ρ → δ → γ → Code,
    // with ρ folded into the class itself.
    EXPECT_NE(text.find("delta_t d, gamma_t g)"), std::string::npos)
        << "dispatcher should take both δ and γ:\n" << text;
}

TEST(Codegen, GenCallReturnTypePropagatesToLet) {
    // `let k = gen(...)` should be declared with the ir_root type
    // (`int` here), not `auto`. Verifies the type-checker's side-table
    // flows through to let-statement emission.
    static const char* src = R"(
COMPILER hello
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_x : (int) -> int
RULES
rule lit : ast.Lit(n: x) { cg_x(x); }
rule add : ast.Add(left: l, right: r) {
    let lk = gen(l, effect, fail);
    cg_x(lk);
}
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto check = check_file(file, schemas);
    ASSERT_TRUE(check.ok());

    std::ostringstream out;
    std::vector<std::string> emit_errs;
    ASSERT_TRUE(emit_cpp(file, schemas, check, out, emit_errs));
    std::string text = out.str();

    // The let should be `int lk = ...`, not `auto lk = ...`.
    EXPECT_NE(text.find("int lk = compile_expr"), std::string::npos)
        << "let lk should be typed as int (ir_root), got:\n" << text;
}

TEST(TypeCheck, DesugaredByNormalizationExemptsFromCoverage) {
    // `Add` has no rule, but DESUGARED lists it as
    // exempt — coverage should still pass.
    static const char* src = R"(
COMPILER hello
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_x : (int) -> int
DESUGARED
  Add
RULES
rule lit : ast.Lit(n: x) { cg_x(x); }
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto r = check_file(file, schemas);
    EXPECT_TRUE(r.ok())
        << (r.errors.empty() ? "" : r.errors.front().message);
}

TEST(TypeCheck, DesugaredByNormalizationRejectsUnknownName) {
    // Listing a non-existent constructor in the exemption list is a
    // typo or stale reference — error.
    static const char* src = R"(
COMPILER hello
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_x : (int) -> int
DESUGARED
  NotARealCtor
RULES
rule lit : ast.Lit(n: x) { cg_x(x); }
rule add : ast.Add(left: l, right: r) { cg_x(l); }
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto r = check_file(file, schemas);
    EXPECT_FALSE(r.ok());
    EXPECT_TRUE(has_err_substring(r,
        "desugared_by_normalization: 'NotARealCtor'"));
}

TEST(Codegen, EmptyListAnnotationContextualisesElemType) {
    // The accumulator pattern: `let xs: list<int> = []` followed by
    // `xs := xs + [item]` in a for-loop. Without the typed-bind hook,
    // `[]` infers as `list<?>` and the C++ backend can't pick an
    // element type. The typechecker contextualises empty lists when
    // the bind annotates a concrete list type, so codegen emits
    // `std::vector<int>{}`.
    static const char* src = R"(
COMPILER hello
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_use : (int) -> int
RULES
rule lit : ast.Lit(n: x) {
    let xs: list<int> = [];
    cg_use(x);
}
rule add : ast.Add(left: l, right: r) {
    let lk = gen(l, effect, fail);
    cg_use(lk);
}
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto check = check_file(file, schemas);
    ASSERT_TRUE(check.ok())
        << (check.errors.empty() ? "" : check.errors.front().message);

    std::ostringstream out;
    std::vector<std::string> emit_errs;
    ASSERT_TRUE(emit_cpp(file, schemas, check, out, emit_errs));
    std::string text = out.str();

    // The annotated empty list should emit a typed vector, not the
    // bare `std::vector{}` (which won't compile for empty literals).
    EXPECT_NE(text.find("std::vector<int>{}"), std::string::npos)
        << "expected std::vector<int>{} for typed empty list, got:\n" << text;
}

TEST(TypeCheck, UnknownDestinationConstructor) {
    static const char* src = R"(
COMPILER hello
IMPORTS
  ast = "ast.json"
DESTINATIONS
  data_dest delta { effect }
  ctrl_dest gamma { fail }
  ir_root int
AUXILIARIES
  cg_x : (int) -> int
RULES
rule lit : ast.Lit(n: x) {cg_x(restore(x)); }
rule add : ast.Add(left: l, right: r) {cg_x(l); }
)";
    auto* file = parse_ddcg(src);
    ASSERT_NE(file, nullptr);
    std::map<std::string, Schema> schemas{{"ast", make_tiny_schema()}};
    auto r = check_file(file, schemas);
    EXPECT_FALSE(r.ok());
    EXPECT_TRUE(has_err_substring(r, "unknown name: restore"));
}

} // namespace ddcgc
