// Generated by pegc — do not edit
#pragma once

#include "PegRuntime.h"
#include "BurgAST.h"

#include <string>
   #include <vector>
   #include <cstdint>
   #include "PegRuntime.h"


class Parser : public peg::PegCursor {
public:
    Parser() = default;

    void init(const char* input, int length);
    bool parse();

    burg_ast::Spec* ast = nullptr;


private:
    void setup_skip();


    bool parse_Burg();
    bool parse_Decl(std::vector<burg_ast::TermDecl*>& terms, std::string& start, std::vector<std::string>& entries, std::string& ns, std::string& members, std::string& priv, std::vector<std::string>& headers, std::vector<burg_ast::AuxDecl*>& auxes, std::vector<burg_ast::RewriteRule*>& rewrites, std::vector<burg_ast::AnalysisDecl*>& analyses);
    bool parse_NamespaceDecl(std::string& ns);
    bool parse_MembersDecl(std::string& members);
    bool parse_PrivateDecl(std::string& priv);
    bool parse_HeaderAction_(std::vector<std::string>& headers);
    bool parse_TermDecl_(std::vector<burg_ast::TermDecl*>& terms);
    bool parse_StartDecl(std::string& start);
    bool parse_EntryDecl(std::vector<std::string>& entries);
    bool parse_RuleDecl(burg_ast::Rule* * result);
    bool parse_TreePat(burg_ast::TreePattern* * result);
    bool parse_AuxSection(std::vector<burg_ast::AuxDecl*>& out);
    bool parse_AuxDecl_(burg_ast::AuxDecl* * result);
    bool parse_RewriteSection(std::vector<burg_ast::RewriteRule*>& out, std::vector<burg_ast::AnalysisDecl*>& analyses);
    bool parse_AnalysisDecl_(burg_ast::AnalysisDecl* * result);
    bool parse_RewriteRule_(burg_ast::RewriteRule* * result);
    bool parse_RewritePat_(burg_ast::RewritePat* * result);
    bool parse_RewriteTmpl_(burg_ast::RewriteTmpl* * result);
    bool ident(peg::Span& out);
    bool ident() { peg::Span _d; return ident(_d); }
    bool integer(peg::Span& out);
    bool integer() { peg::Span _d; return integer(_d); }
    bool qualified_ident(peg::Span& out);
    bool qualified_ident() { peg::Span _d; return qualified_ident(_d); }

};

