// Generated by pegc — do not edit
#pragma once

#include "PegRuntime.h"
#include "BurgAST.h"

#include <string>
   #include <vector>
   #include <cstdint>


class Parser : public peg::PegCursor {
public:
    Parser() = default;

    void init(const char* input, int length);
    bool parse();

    burg_ast::Spec* ast = nullptr;


private:
    void setup_skip();


    bool parse_Burg();
    bool parse_Decl(std::vector<burg_ast::TermDecl*>& terms, std::string& start, std::string& ns, std::string& members, std::vector<std::string>& headers);
    bool parse_NamespaceDecl(std::string& ns);
    bool parse_MembersDecl(std::string& members);
    bool parse_HeaderAction_(std::vector<std::string>& headers);
    bool parse_TermDecl_(std::vector<burg_ast::TermDecl*>& terms);
    bool parse_StartDecl(std::string& start);
    bool parse_RuleDecl(burg_ast::Rule* * result);
    bool parse_TreePat(burg_ast::TreePattern* * result);

};

