// rewrite_backend.cpp — emit a saturating rewriter from the REWRITE section.
//
// One matcher function per rule and one entry point. A matcher walks the
// classes, tries its pattern against each e-node, and on a match builds the
// template and merges it with the class it matched — match, instantiate,
// merge, which is the whole of a rewrite.
//
// The emitted file talks to the e-graph and to nothing else. It cannot see
// the consumer's IR, its allocator, or libc: a rewriter that reached for any
// of those would have to be satisfied by every consumer of every grammar.
// Values the rules need travel on the class payload, recorded by whichever
// stage built the graph and knew them.
#include "generator.h"
#include <ostream>
#include <string>

namespace {

// Substitute `$name` with the C variable holding that binder's class.
std::string subst_binders(const std::string& src) {
    std::string out;
    for (size_t i = 0; i < src.size(); i++) {
        if (src[i] == '$' && i + 1 < src.size() &&
            (isalpha((unsigned char)src[i + 1]) || src[i + 1] == '_')) {
            i++;
            while (i < src.size() &&
                   (isalnum((unsigned char)src[i]) || src[i] == '_'))
                out += src[i++];
            i--;
        } else {
            out += src[i];
        }
    }
    return out;
}

// Emit the match for one pattern node against `cls`, opening a scope per
// level. Returns the number of scopes opened, for the caller to close.
int emit_match(std::ostream& o, const burg_ast::RewritePat* p,
               const std::string& cls, int depth, int& tmp) {
    // A binder names the class already in hand — no loop, no copy.
    if (p->is_binder) return 0;

    std::string ni = "n" + std::to_string(tmp++);
    std::string ind((size_t)depth * 4, ' ');
    o << ind << "int " << ni << "_n = eg_class_nodes(g, " << cls << ");\n";
    o << ind << "for (int " << ni << " = 0; " << ni << " < " << ni
      << "_n; " << ni << "++) {\n";
    o << ind << "    if (eg_class_node_op(g, " << cls << ", " << ni
      << ") != BURG_" << p->name << ") continue;\n";
    o << ind << "    if (eg_class_node_nkids(g, " << cls << ", " << ni
      << ") != " << p->children.size() << ") continue;\n";
    // Every child's accessor first, then the descents. Interleaving them puts
    // a later sibling inside the loop an earlier one opened — still correct,
    // since it does not depend on that loop's variable, but re-evaluated on
    // every iteration and indented as though it were not nested.
    std::vector<std::string> kid_names;
    for (size_t k = 0; k < p->children.size(); k++) {
        // A binder child takes the kid's own name, so the body reads the
        // class directly; a nested pattern gets a temporary to descend into.
        const burg_ast::RewritePat* c = p->children[k];
        std::string kid = c->is_binder ? c->name
                                       : ("k" + std::to_string(tmp++));
        kid_names.push_back(kid);
        o << ind << "    eg_id " << kid << " = eg_class_node_kid(g, " << cls
          << ", " << ni << ", " << k << ");\n";
    }
    int opened = 1;
    for (size_t k = 0; k < p->children.size(); k++)
        opened += emit_match(o, p->children[k], kid_names[k], depth + 1, tmp);
    return opened;
}

// Emit the construction of a template, returning the C expression for the
// class it produces.
std::string emit_build(std::ostream& o, const burg_ast::RewriteTmpl* t,
                       const std::string& ind, int& tmp) {
    if (t->kind == burg_ast::RewriteTmpl::Binder) return t->name;

    std::vector<std::string> kids;
    for (auto* c : t->children) kids.push_back(emit_build(o, c, ind, tmp));

    std::string v = "b" + std::to_string(tmp++);
    if (t->kind == burg_ast::RewriteTmpl::Helper) {
        // An auxiliary trades in classes, because that is the rewriter's only
        // currency; whatever value it needs was recorded on the payload by
        // the stage that had it.
        o << ind << "eg_id " << v << " = " << t->name << "(g";
        for (auto& k : kids) o << ", " << k;
        o << ");\n";
        return v;
    }
    o << ind << "eg_id " << v << "_k[] = { ";
    for (size_t i = 0; i < kids.size(); i++) o << (i ? ", " : "") << kids[i];
    if (kids.empty()) o << "0";
    o << " };\n";
    // data 0: a template builds a structural node. A leaf that needs a
    // discriminant is produced by an auxiliary, which is the only thing that
    // knows the value to put there.
    o << ind << "eg_id " << v << " = eg_add(g, BURG_" << t->name << ", 0, "
      << v << "_k, " << kids.size() << ");\n";
    return v;
}

}  // namespace

void emit_rewriter(std::ostream& o, const BurgAnalysis& a,
                   const std::string& name) {
    o << "/* AUTO-GENERATED by burgc --rewrite — do not edit. */\n"
         "#include \"egraph.h\"\n\n";

    o << "/* Terminal ids, as the tiling grammar declares them. */\n";
    for (auto* t : a.spec->terminals) {
        o << "#define BURG_" << t->name << " ";
        if (t->symbol.empty()) o << t->number; else o << t->symbol;
        o << "\n";
    }
    o << "\n";

    if (!a.spec->auxiliaries.empty()) {
        o << "/* Auxiliaries. Each takes the classes its binders matched and\n"
             " * returns the class of its result. A value an auxiliary needs\n"
             " * arrives on the class payload, recorded by whichever stage\n"
             " * built the graph and had it — it is not recovered here. */\n";
        for (auto* d : a.spec->auxiliaries) {
            o << "extern eg_id " << d->name << "(egraph* g";
            for (size_t i = 0; i < d->params.size(); i++) o << ", eg_id";
            o << ");\n";
        }
        o << "\n";
    }

    for (auto* rw : a.spec->rewrites) {
        o << "/* " << rw->name << " */\n"
          << "static bool rw_" << rw->name << "(egraph* g) {\n"
             "    bool changed = false;\n"
             "    int ncls = eg_class_count(g);\n"
             "    for (eg_id c = 0; c < ncls; c++) {\n"
             "        if (eg_find(g, c) != c) continue;\n";
        int tmp = 0;
        // Depth 2 == inside `for (c) {`; each nested pattern level opens one
        // more loop, and the closers unwind them in step so the emitted file
        // reads like something a person wrote.
        int opened = emit_match(o, rw->pattern, "c", 2, tmp);
        std::string ind((size_t)(opened + 2) * 4, ' ');
        if (!rw->guard.empty())
            o << ind << "if (!(" << subst_binders(rw->guard) << ")) continue;\n";
        std::string built = emit_build(o, rw->tmpl, ind, tmp);
        o << ind << "if (eg_merge(g, c, " << built << ")) changed = true;\n";
        for (int i = opened; i > 0; i--)
            o << std::string((size_t)(i + 1) * 4, ' ') << "}\n";
        o << "    }\n"
             "    return changed;\n"
             "}\n\n";
    }

    o << "/* One pass over the rule set. */\n"
         "static bool " << name << "_round(egraph* g, void* user) {\n"
         "    (void)user;\n"
         "    bool changed = false;\n";
    for (auto* rw : a.spec->rewrites)
        o << "    if (rw_" << rw->name << "(g)) changed = true;\n";
    o << "    return changed;\n"
         "}\n\n";

    o << "/* Saturate the region to fixpoint or to whichever cap binds. */\n"
         "int " << name << "_rewrite_region(egraph* g, eg_caps caps) {\n"
         "    return eg_saturate(g, " << name << "_round, 0, caps);\n"
         "}\n";
}
