// opcodes.h + opcode_tables.c emitters, ported from emit_opcodes_h.cpp /
// emit_opcode_tables_c.cpp. The per-opcode facts come from the Spec instead of
// the C global derived_table; every emitted byte is unchanged.
#include "tablesemit.h"
#include <cctype>
#include <string>

namespace opgen {

// ── opcodes.h ───────────────────────────────────────────────

void TablesEmitter::emit_opcodes_h(FILE* out) {
    fprintf(out,
        "/* AUTO-GENERATED by opgen — do not edit. */\n"
        "/* Source: the opcode spec (.def). */\n"
        "#ifndef OPGEN_GEN_OPCODES_H\n"
        "#define OPGEN_GEN_OPCODES_H\n\n");

    // OP_* constants, sorted by opcode value.
    fprintf(out, "/* ===== OP_* opcode constants (sorted by value) ===== */\n");
    int max_op = 0;
    for (auto* op : mod_->opcodes)
        if (op->opcode_val > max_op) max_op = op->opcode_val;
    fprintf(out, "#define OPGEN_NUM_OPCODES %d\n\n", max_op + 1);

    for (int op = 0; op < 256; op++) {
        if (!spec_.derived(op).present) continue;
        const char* mn = spec_.derived(op).ast->mnemonic;
        std::string up;
        for (const char* p = mn; *p; ++p)
            up.push_back(static_cast<char>(toupper(static_cast<unsigned char>(*p))));
        fprintf(out, "#define OP_%-22s 0x%02X\n", up.c_str(), op);
    }
    fprintf(out, "\n");

    fprintf(out,
        "/* ===== Per-opcode category flags (opcode_flags[] bits) ===== */\n"
        "#define OPCF_BRANCH       0x01u   /* has a branch target (cond or uncond) */\n"
        "#define OPCF_RETURN       0x02u   /* {s,i,a,}return */\n"
        "#define OPCF_INVOKE       0x04u   /* mnemonic starts with \"invoke\" */\n"
        "#define OPCF_SWITCH       0x08u   /* {s,i}{table,lookup}switch */\n"
        "#define OPCF_HAS_CP_REF   0x10u   /* any operand is a CP reference */\n"
        "#define OPCF_ENDS_BB      0x20u   /* control flow does not fall through */\n"
        "#define OPCF_LOCAL_LOAD   0x40u   /* pushes a local-variable value (sload/aload/iload) */\n"
        "#define OPCF_LOCAL_STORE  0x80u   /* writes a local variable (sstore/astore/istore, sinc/iinc) */\n\n"
        "/* Sentinel values in opcode_stack_delta[] / opcode_length[]. */\n"
        "#define OPCD_VARIABLE     ((signed char)-128) /* per-call-site delta */\n"
        "#define OPCL_VARIABLE     0                   /* payload-dependent length */\n\n");

    fprintf(out,
        "/* ===== Tables (defined in src/gen/opcode_tables.c) ===== */\n"
        "extern const unsigned char opcode_length[256];\n"
        "extern const signed char   opcode_stack_delta[256];\n"
        "extern const char* const   opcode_name[256];\n"
        "extern const unsigned char opcode_flags[256];\n"
        "extern const unsigned char opcode_cp_ref_offset[256];\n"
        "/* Stack cells popped by an opcode (sum of stack_in widths).\n"
        " * OPCD_VARIABLE for per-call-site opcodes (invokes/dup_x/switch). */\n"
        "extern const signed char   opcode_stack_pops[256];\n");

    if (!mod_->headers.empty()) {
        fprintf(out, "\n/* ===== User header blocks (from opcodes.def) ===== */\n\n");
        for (auto* h : mod_->headers) {
            fputs(h, out);
            fputc('\n', out);
        }
    }

    fprintf(out, "\n#endif /* OPGEN_GEN_OPCODES_H */\n");
}

// ── opcode_tables.c ─────────────────────────────────────────

template <class F>
static void emit_uchar_table(FILE* out, const char* name, F get) {
    fprintf(out, "const unsigned char %s[256] = {\n", name);
    for (int row = 0; row < 16; row++) {
        fprintf(out, "    /* 0x%02X */ ", row * 16);
        for (int col = 0; col < 16; col++)
            fprintf(out, "%3d,", get(row * 16 + col));
        fprintf(out, "\n");
    }
    fprintf(out, "};\n\n");
}

template <class F>
static void emit_schar_table(FILE* out, const char* name, F get) {
    fprintf(out, "const signed char %s[256] = {\n", name);
    for (int row = 0; row < 16; row++) {
        fprintf(out, "    /* 0x%02X */ ", row * 16);
        for (int col = 0; col < 16; col++)
            fprintf(out, "%4d,", get(row * 16 + col));
        fprintf(out, "\n");
    }
    fprintf(out, "};\n\n");
}

void TablesEmitter::emit_opcode_tables_c(FILE* out) {
    const Spec& s = spec_;
    fprintf(out,
        "/* AUTO-GENERATED by opgen — do not edit. */\n"
        "/* Source: the opcode spec (.def). */\n\n"
        "#include \"gen/opcodes.h\"\n\n");

    emit_uchar_table(out, "opcode_length",        [&](int op){ return s.derived(op).length; });
    emit_schar_table(out, "opcode_stack_delta",   [&](int op){ return s.derived(op).sp_delta; });
    emit_uchar_table(out, "opcode_flags",         [&](int op){ return (int)s.derived(op).flags; });
    emit_uchar_table(out, "opcode_cp_ref_offset", [&](int op){ return s.derived(op).cp_ref_offset; });
    emit_schar_table(out, "opcode_stack_pops",    [&](int op){ return s.derived(op).present ? s.derived(op).sp_pops : 0; });

    fprintf(out, "const char* const opcode_name[256] = {\n");
    for (int op = 0; op < 256; op++)
        if (s.derived(op).present)
            fprintf(out, "    [0x%02X] = \"%s\",\n", op, s.derived(op).ast->mnemonic);
    fprintf(out, "};\n\n");

    if (mod_->body_c.has_value()) {
        fprintf(out, "\n/* ===== User body (from opcodes.def after %%%%) ===== */\n");
        fputs(*mod_->body_c, out);
        fputc('\n', out);
    }
}

} // namespace opgen
