// Generated by BBQ — do not edit
#pragma once

#include <cstdint>
#include <variant>
#include <vector>
#include <optional>
#include <string>



struct Elf64_Ident;
struct Elf64_Shdr;
struct Elf64_Sym;
struct Elf64_Rela;
struct Elf64_Phdr;
struct Elf64_Rel;
struct Elf64_Ehdr;
struct Elf64;

struct Elf64_Ident {
    uint32_t ei_mag;
    uint8_t ei_class;
    uint8_t ei_data;
    uint8_t ei_version;
    uint8_t ei_osabi;
    uint8_t ei_abiversion;
    std::vector<uint8_t> ei_pad;
};

struct Elf64_Shdr {
    uint32_t sh_name;
    uint32_t sh_type;
    uint64_t sh_flags;
    uint64_t sh_addr;
    uint64_t sh_offset;
    uint64_t sh_size;
    uint32_t sh_link;
    uint32_t sh_info;
    uint64_t sh_addralign;
    uint64_t sh_entsize;
};

struct Elf64_Sym {
    uint32_t st_name;
    uint8_t st_info;
    uint8_t st_other;
    uint16_t st_shndx;
    uint64_t st_value;
    uint64_t st_size;
    uint8_t st_bind;
    uint8_t st_type;
};

struct Elf64_Rela {
    uint64_t r_offset;
    uint64_t r_info;
    int64_t r_addend;
    uint32_t r_sym;
    uint32_t r_type;
};

struct Elf64_Phdr {
    uint32_t p_type;
    uint32_t p_flags;
    uint64_t p_offset;
    uint64_t p_vaddr;
    uint64_t p_paddr;
    uint64_t p_filesz;
    uint64_t p_memsz;
    uint64_t p_align;
};

struct Elf64_Rel {
    uint64_t r_offset;
    uint64_t r_info;
    uint32_t r_sym;
    uint32_t r_type;
};

struct Elf64_Ehdr {
    Elf64_Ident e_ident;
    uint16_t e_type;
    uint16_t e_machine;
    uint32_t e_version;
    uint64_t e_entry;
    uint64_t e_phoff;
    uint64_t e_shoff;
    uint32_t e_flags;
    uint16_t e_ehsize;
    uint16_t e_phentsize;
    uint16_t e_phnum;
    uint16_t e_shentsize;
    uint16_t e_shnum;
    uint16_t e_shstrndx;
};

struct Elf64 {
    Elf64_Ehdr ehdr;
    std::vector<Elf64_Shdr> shdrs;
    std::vector<Elf64_Phdr> phdrs;
};



