// Generated by BBQ — do not edit
#include "elf64Parser.h"



bool parse_Elf64_Ident(bbq::BBQContext& ctx, Elf64_Ident& out) {
    if (!ctx.read_uint32(out.ei_mag))
        return ctx.fail("Elf64_Ident.ei_mag: read failed");
    if (!((out.ei_mag == 1179403647)))
        return ctx.fail("Elf64_Ident.ei_mag: constraint failed");
    if (!ctx.read_uint8(out.ei_class))
        return ctx.fail("Elf64_Ident.ei_class: read failed");
    if (!((out.ei_class == 2)))
        return ctx.fail("Elf64_Ident.ei_class: constraint failed");
    if (!ctx.read_uint8(out.ei_data))
        return ctx.fail("Elf64_Ident.ei_data: read failed");
    if (!ctx.read_uint8(out.ei_version))
        return ctx.fail("Elf64_Ident.ei_version: read failed");
    if (!ctx.read_uint8(out.ei_osabi))
        return ctx.fail("Elf64_Ident.ei_osabi: read failed");
    if (!ctx.read_uint8(out.ei_abiversion))
        return ctx.fail("Elf64_Ident.ei_abiversion: read failed");
    if (!ctx.read_bytes(out.ei_pad, 7))
        return ctx.fail("Elf64_Ident.ei_pad: read bytes failed");
    return true;
}

bool parse_Elf64_Shdr(bbq::BBQContext& ctx, Elf64_Shdr& out) {
    if (!ctx.read_uint32(out.sh_name))
        return ctx.fail("Elf64_Shdr.sh_name: read failed");
    if (!ctx.read_uint32(out.sh_type))
        return ctx.fail("Elf64_Shdr.sh_type: read failed");
    if (!ctx.read_uint64(out.sh_flags))
        return ctx.fail("Elf64_Shdr.sh_flags: read failed");
    if (!ctx.read_uint64(out.sh_addr))
        return ctx.fail("Elf64_Shdr.sh_addr: read failed");
    if (!ctx.read_uint64(out.sh_offset))
        return ctx.fail("Elf64_Shdr.sh_offset: read failed");
    if (!ctx.read_uint64(out.sh_size))
        return ctx.fail("Elf64_Shdr.sh_size: read failed");
    if (!ctx.read_uint32(out.sh_link))
        return ctx.fail("Elf64_Shdr.sh_link: read failed");
    if (!ctx.read_uint32(out.sh_info))
        return ctx.fail("Elf64_Shdr.sh_info: read failed");
    if (!ctx.read_uint64(out.sh_addralign))
        return ctx.fail("Elf64_Shdr.sh_addralign: read failed");
    if (!ctx.read_uint64(out.sh_entsize))
        return ctx.fail("Elf64_Shdr.sh_entsize: read failed");
    return true;
}

bool parse_Elf64_Sym(bbq::BBQContext& ctx, Elf64_Sym& out) {
    if (!ctx.read_uint32(out.st_name))
        return ctx.fail("Elf64_Sym.st_name: read failed");
    if (!ctx.read_uint8(out.st_info))
        return ctx.fail("Elf64_Sym.st_info: read failed");
    if (!ctx.read_uint8(out.st_other))
        return ctx.fail("Elf64_Sym.st_other: read failed");
    if (!ctx.read_uint16(out.st_shndx))
        return ctx.fail("Elf64_Sym.st_shndx: read failed");
    if (!ctx.read_uint64(out.st_value))
        return ctx.fail("Elf64_Sym.st_value: read failed");
    if (!ctx.read_uint64(out.st_size))
        return ctx.fail("Elf64_Sym.st_size: read failed");
    out.st_bind = ((out.st_info >> 4) & 15);
    out.st_type = (out.st_info & 15);
    return true;
}

bool parse_Elf64_Rela(bbq::BBQContext& ctx, Elf64_Rela& out) {
    if (!ctx.read_uint64(out.r_offset))
        return ctx.fail("Elf64_Rela.r_offset: read failed");
    if (!ctx.read_uint64(out.r_info))
        return ctx.fail("Elf64_Rela.r_info: read failed");
    if (!ctx.read_int64(out.r_addend))
        return ctx.fail("Elf64_Rela.r_addend: read failed");
    out.r_sym = ((out.r_info >> 32) & 0xFFFFFFFFULL);
    out.r_type = (out.r_info & 0xFFFFFFFFULL);
    return true;
}

bool parse_Elf64_Phdr(bbq::BBQContext& ctx, Elf64_Phdr& out) {
    if (!ctx.read_uint32(out.p_type))
        return ctx.fail("Elf64_Phdr.p_type: read failed");
    if (!ctx.read_uint32(out.p_flags))
        return ctx.fail("Elf64_Phdr.p_flags: read failed");
    if (!ctx.read_uint64(out.p_offset))
        return ctx.fail("Elf64_Phdr.p_offset: read failed");
    if (!ctx.read_uint64(out.p_vaddr))
        return ctx.fail("Elf64_Phdr.p_vaddr: read failed");
    if (!ctx.read_uint64(out.p_paddr))
        return ctx.fail("Elf64_Phdr.p_paddr: read failed");
    if (!ctx.read_uint64(out.p_filesz))
        return ctx.fail("Elf64_Phdr.p_filesz: read failed");
    if (!ctx.read_uint64(out.p_memsz))
        return ctx.fail("Elf64_Phdr.p_memsz: read failed");
    if (!ctx.read_uint64(out.p_align))
        return ctx.fail("Elf64_Phdr.p_align: read failed");
    return true;
}

bool parse_Elf64_Rel(bbq::BBQContext& ctx, Elf64_Rel& out) {
    if (!ctx.read_uint64(out.r_offset))
        return ctx.fail("Elf64_Rel.r_offset: read failed");
    if (!ctx.read_uint64(out.r_info))
        return ctx.fail("Elf64_Rel.r_info: read failed");
    out.r_sym = ((out.r_info >> 32) & 0xFFFFFFFFULL);
    out.r_type = (out.r_info & 0xFFFFFFFFULL);
    return true;
}

bool parse_Elf64_Ehdr(bbq::BBQContext& ctx, Elf64_Ehdr& out) {
    { bbq::ScopeGuard _scope(ctx, &out);
        if (!parse_Elf64_Ident(ctx, out.e_ident))
            return ctx.fail("Elf64_Ehdr.e_ident");
    }
    if (!ctx.read_uint16(out.e_type))
        return ctx.fail("Elf64_Ehdr.e_type: read failed");
    if (!ctx.read_uint16(out.e_machine))
        return ctx.fail("Elf64_Ehdr.e_machine: read failed");
    if (!ctx.read_uint32(out.e_version))
        return ctx.fail("Elf64_Ehdr.e_version: read failed");
    if (!ctx.read_uint64(out.e_entry))
        return ctx.fail("Elf64_Ehdr.e_entry: read failed");
    if (!ctx.read_uint64(out.e_phoff))
        return ctx.fail("Elf64_Ehdr.e_phoff: read failed");
    if (!ctx.read_uint64(out.e_shoff))
        return ctx.fail("Elf64_Ehdr.e_shoff: read failed");
    if (!ctx.read_uint32(out.e_flags))
        return ctx.fail("Elf64_Ehdr.e_flags: read failed");
    if (!ctx.read_uint16(out.e_ehsize))
        return ctx.fail("Elf64_Ehdr.e_ehsize: read failed");
    if (!ctx.read_uint16(out.e_phentsize))
        return ctx.fail("Elf64_Ehdr.e_phentsize: read failed");
    if (!ctx.read_uint16(out.e_phnum))
        return ctx.fail("Elf64_Ehdr.e_phnum: read failed");
    if (!ctx.read_uint16(out.e_shentsize))
        return ctx.fail("Elf64_Ehdr.e_shentsize: read failed");
    if (!ctx.read_uint16(out.e_shnum))
        return ctx.fail("Elf64_Ehdr.e_shnum: read failed");
    if (!ctx.read_uint16(out.e_shstrndx))
        return ctx.fail("Elf64_Ehdr.e_shstrndx: read failed");
    return true;
}

bool parse_Elf64(bbq::BBQContext& ctx, Elf64& out) {
    { bbq::ScopeGuard _scope(ctx, &out);
        if (!parse_Elf64_Ehdr(ctx, out.ehdr))
            return ctx.fail("Elf64.ehdr");
    }
    { bbq::LoopGuard _lg(ctx);
        auto count = static_cast<size_t>(out.ehdr.e_shnum);
        out.shdrs.resize(count);
        for (size_t i = 0; i < count; i++) {
            ctx.set_loop_index(static_cast<int64_t>(i));
            auto elem_scope = ctx.push_interval((out.ehdr.e_shoff + (ctx.loop_index() * out.ehdr.e_shentsize)), (out.ehdr.e_shoff + ((ctx.loop_index() + 1) * out.ehdr.e_shentsize)));
            { bbq::ScopeGuard _scope(ctx, &out);
                if (!parse_Elf64_Shdr(ctx, out.shdrs[i]))
                    return ctx.fail("Elf64.shdrs[]");
            }
        }
    }
    { bbq::LoopGuard _lg(ctx);
        auto count = static_cast<size_t>(out.ehdr.e_phnum);
        out.phdrs.resize(count);
        for (size_t i = 0; i < count; i++) {
            ctx.set_loop_index(static_cast<int64_t>(i));
            auto elem_scope = ctx.push_interval((out.ehdr.e_phoff + (ctx.loop_index() * out.ehdr.e_phentsize)), (out.ehdr.e_phoff + ((ctx.loop_index() + 1) * out.ehdr.e_phentsize)));
            { bbq::ScopeGuard _scope(ctx, &out);
                if (!parse_Elf64_Phdr(ctx, out.phdrs[i]))
                    return ctx.fail("Elf64.phdrs[]");
            }
        }
    }
    return true;
}



