// Generated by BBQ — do not edit
#pragma once

#include "elf64Types.h"
#include "BBQContext.h"



bool parse_Elf64_Ident(bbq::BBQContext& ctx, Elf64_Ident& out);
bool parse_Elf64_Shdr(bbq::BBQContext& ctx, Elf64_Shdr& out);
bool parse_Elf64_Sym(bbq::BBQContext& ctx, Elf64_Sym& out);
bool parse_Elf64_Rela(bbq::BBQContext& ctx, Elf64_Rela& out);
bool parse_Elf64_Phdr(bbq::BBQContext& ctx, Elf64_Phdr& out);
bool parse_Elf64_Rel(bbq::BBQContext& ctx, Elf64_Rel& out);
bool parse_Elf64_Ehdr(bbq::BBQContext& ctx, Elf64_Ehdr& out);
bool parse_Elf64(bbq::BBQContext& ctx, Elf64& out);


