// Generated by ddcgc — do not edit
#pragma once
//
// Shape: `class Compiler` inside `namespace bbq`.
// MEMBERS verbatim block holds the consumer's state and the
// aux/pred bodies (called as bare methods on `this`). The
// generated dispatch methods read `current_loc` / call
// `fresh_label()` if RULES use `label`; the consumer must
// declare those in MEMBERS.
//
// The two destination types `<data_dest>_t` and `<ctrl_dest>_t`
// must exist at namespace scope, with one constructor function
// per variant — those are *namespace-level*, not class members,
// because callers of `compile_<sum>` build δ/γ values themselves.


   #include "BBQ_AST.h"
   #include "Sema.h"
   #include "KontNode.h"
   #include "ParseArena.h"
   #include "StringPool.h"
   #include "CompiledGrammar.h"
   #include <cassert>
   #include <cstring>
   #include <cstdio>
   #include <unordered_map>
   #include <utility>
   #include <vector>

   // ddcgc references generated IR types as `bbq_ir::*` (matching the
   // asdl module name `module bbq_ir`). Our hand-written runtime
   // declares them in `bbq::cek::` (the existing CEK namespace).
   // Alias one to the other so the ddcg-generated Compiler class
   // finds StaticKont / DynamicKont / Value / etc.
   namespace bbq_ir = bbq::cek;

   // Destination types live at `namespace bbq` scope — that's where
   // ddcgc generates `class Compiler`, and the generated dispatch
   // methods reference these as bare names (delta_t / gamma_t / rho_t).
   namespace bbq {

   // δ — paper §3.1 Location class. BBQ uses {effect, ac}.
   enum class DeltaTag : unsigned char { Effect, Ac, Stack, Local };
   struct delta_t { DeltaTag tag; int i; };
   inline delta_t effect()        { return {DeltaTag::Effect, 0}; }
   inline delta_t ac()            { return {DeltaTag::Ac,     0}; }
   inline delta_t stack()         { return {DeltaTag::Stack,  0}; }
   inline delta_t local(int i)    { return {DeltaTag::Local,  i}; }

   // γ — paper §3.2 control destination. BBQ uses jump(L) only.
   enum class GammaTag : unsigned char { Jump, Pair, Ret };
   struct gamma_t {
       GammaTag tag;
       bbq::cek::StaticKont* L;
       bbq::cek::StaticKont* Lt;
       bbq::cek::StaticKont* Lf;
   };
   inline gamma_t jump(bbq::cek::StaticKont* L)                                       { return {GammaTag::Jump, L,       nullptr, nullptr}; }
   inline gamma_t pair(bbq::cek::StaticKont* Lt, bbq::cek::StaticKont* Lf)            { return {GammaTag::Pair, nullptr, Lt,      Lf}; }
   inline gamma_t ret()                                                                { return {GammaTag::Ret,  nullptr, nullptr, nullptr}; }

   // ρ — lexical-scope chain consumed at compile time only. The
   // yoctojc pattern: each backtrackable scope wraps the caller's ρ
   // with a frame carrying the static failure target for inner
   // where-checks. find_backtrack_target walks ρ at compile time to
   // resolve the on_false destination; intern_field_or_anon walks to
   // the innermost in_field for capture naming.
   //
   //   in_field      — current field name, for capture metadata.
   //                   intern_field_or_anon walks to it.
   //   in_alt        — non-last arm of an alt; next_arm is the
   //                   compile-time-baked OnFailKont link that
   //                   restores the savepoint and dispatches to the
   //                   next arm.
   //   in_optional   — optional inner; skip is the OnFailKont link
   //                   that restores + pops + jumps past the optional.
   //   in_array_elem — array-element scope. Acts as a name barrier
   //                   for intern_field_or_anon. skip is non-null only
   //                   in resync mode (= the ResyncKont); otherwise
   //                   find_backtrack_target walks past transparently.
   //
   // The struct is a POD; `parent` is a pointer because C++ structs
   // can't recurse by value. Constructors are Compiler member methods
   // (see PRIVATE block) so parent allocation goes through arena_;
   // ddcgc-emitted calls resolve to `this->ctor(...)` via bare-name
   // lookup in dispatcher methods.
   enum class RhoTag : unsigned char {
       Root,
       InField,
       InAlt,
       InOptional,
       InArrayElem,
   };
   struct rho_t {
       RhoTag tag;
       const char* name;                  // InField only
       bbq::cek::StaticKont* fail_target; // InAlt.next_arm / InOptional.skip / InArrayElem.skip
       rho_t* parent;                     // every non-Root variant
   };

   } // namespace bbq

#include <vector>
#include <tuple>
#include <string>

namespace bbq {

template <class T>
static inline std::vector<T> _ddcgc_concat(std::vector<T> a,
                                            const std::vector<T>& b) {
    a.insert(a.end(), b.begin(), b.end());
    return a;
}

class Compiler {
public:
    // ─── MEMBERS (verbatim) ─────────────────────

    // ── Public API: the only entry point on bbq::Compiler ──────
    //
    // Per design doc §5.4: the driver owns program-exit wrapping.
    // For each rule:
    //   1. Allocate the rule's exit kont chain: Halt at the bottom,
    //      ReturnRule on top. Top-level entries push a throwaway
    //      ReturnFrame in the runtime so ReturnRule has something to
    //      pop; inner calls (via InvokeRule) push real ReturnFrames.
    //   2. Compile the rule body with γ=jump(exit). Top-level Struct
    //      bodies inline (no BeginStruct wrapper) so user-facing
    //      results expose `result.<field>` rather than
    //      `result.<empty>.<field>`.
    //   3. Record the body head in rule_entries_.
    //
    // After every rule has compiled, walk pending_patches_ and resolve
    // each (slot, name) to rule_entries_[name]. Sema rejects refs to
    // unknown rule names before we get here, so an unresolved patch
    // means an internal invariant was broken.
    bbq::cek::CompiledGrammar* compile_grammar(BBQ::Grammar* grammar) {
        if (!grammar) return nullptr;
        auto* result = new bbq::cek::CompiledGrammar();
        arena_   = &result->arena;
        strings_ = &result->strings;
        rule_entries_.clear();
        pending_patches_.clear();

        std::vector<bbq::cek::CompiledGrammar::RuleEntry> entries;
        entries.reserve(grammar->rules.size());

        for (auto* rule : grammar->rules) {
            auto* halt = arena_->alloc<bbq::cek::HaltNode>();
            auto* exit_kont = make_return_rule(halt);
            auto* exit_static = static_cast<bbq::cek::StaticKont*>(exit_kont);

            ::bbq::rho_t rho = root();
            bbq::cek::StaticKont* body_head = nullptr;
            if (auto* st = dynamic_cast<BBQ::Struct*>(rule->body)) {
                body_head = compile_fields(st->fields, rho, exit_static);
            } else {
                body_head = compile_type_expr(
                    rule->body, rho, ::bbq::effect(),
                    ::bbq::jump(exit_static), exit_static);
            }

            rule_entries_[rule->name] = body_head;
            entries.push_back({result->strings.intern(rule->name), body_head});
        }

        // Resolve every InvokeRuleNode's entry by looking up its rule
        // name in rule_entries_. Recursive grammars round-trip cleanly
        // here: the back-edge from kid → Tree finds Tree's body head.
        for (auto& [slot, name] : pending_patches_) {
            auto it = rule_entries_.find(name);
            if (it == rule_entries_.end()) {
                std::fprintf(stderr,
                    "bbq compile: unresolved rule reference '%s' "
                    "(Sema should have caught this)\n", name.c_str());
                std::abort();
            }
            *slot = it->second;
        }

        if (!entries.empty()) {
            result->rules = static_cast<bbq::cek::CompiledGrammar::RuleEntry*>(
                result->arena.allocate(
                    entries.size() * sizeof(bbq::cek::CompiledGrammar::RuleEntry),
                    alignof(bbq::cek::CompiledGrammar::RuleEntry)));
            for (size_t i = 0; i < entries.size(); ++i) {
                result->rules[i] = entries[i];
            }
            result->rule_count = static_cast<int>(entries.size());
        }

        for (auto* d : grammar->directives) {
            if (auto* ed = dynamic_cast<BBQ::EndianDirective*>(d)) {
                result->default_little_endian =
                    (ed->endian == BBQ::Endianness::Little);
            }
        }

        // Pre-intern built-in function names into result->strings so
        // CallApplyKont's dispatch can use pointer-equality against
        // call-site func_name pointers (also interned in this pool).
        bbq::cek::populate_builtins(*result);

        return result;
    }
    // ─── End MEMBERS ────────────────────────────
private:
    // ─── PRIVATE (verbatim) ─────────────────────

    // Allocation arena for IR konts, owned by the compiled grammar.
    bbq::cek::ParseArena* arena_ = nullptr;
    bbq::cek::StringPool* strings_ = nullptr;

    // Rule entry table — populated as each rule finishes compiling.
    // After the per-rule loop in compile_grammar, every rule name maps
    // to its real body-head kont. pending_patches_ is then resolved
    // against this table.
    std::unordered_map<std::string, bbq::cek::StaticKont*> rule_entries_;

    // Forward-reference patch list. make_invoke_rule allocates an
    // InvokeRuleNode with entry=nullptr and pushes (&node->entry, name)
    // onto this list. compile_grammar walks the list at the end and
    // resolves each slot to rule_entries_[name]. Sema rejects any
    // unknown name before we get here, so unresolved entries indicate
    // a Sema/compiler invariant violation and abort.
    std::vector<std::pair<bbq::cek::KontNode**, std::string>> pending_patches_;

    // ddcgc-generated dispatch threads `current_loc` from each AST
    // node it traverses (via `current_loc = node->loc`). Type matches
    // BBQ_AST.h's SourceLoc. Rule bodies don't currently consume it
    // but keeping it correct so generated code compiles.
    BBQ::SourceLoc current_loc{};

    // ── ρ constructors (member methods so parent allocation hits arena_) ──
    //
    // The C++ ddcg backend calls these as `this->ctor(...)` via bare-
    // name lookup in dispatcher methods (per emit_backend.h:118-120
    // design intent). All non-Root variants arena-copy parent so the
    // resulting rho_t is self-contained; ρ chains live as long as the
    // ParseArena, which is the right scope (ρ is throwaway after
    // compile_grammar but the arena is per-CompiledGrammar anyway).
    //
    // ρ frames are POD-copied from `parent_val` into a fresh arena slot
    // via placement-new; arena_->alloc<rho_t>() returns aligned storage.
    ::bbq::rho_t* arena_rho(::bbq::rho_t parent_val) {
        auto* p = arena_->alloc<::bbq::rho_t>();
        *p = parent_val;
        return p;
    }

    ::bbq::rho_t root() {
        return ::bbq::rho_t{::bbq::RhoTag::Root, nullptr, nullptr, nullptr};
    }
    ::bbq::rho_t in_field(const std::string& name, ::bbq::rho_t parent_val) {
        const char* n = name.empty() ? nullptr : strings_->intern(name);
        return ::bbq::rho_t{::bbq::RhoTag::InField, n,
                            nullptr, arena_rho(parent_val)};
    }
    ::bbq::rho_t in_alt(bbq::cek::StaticKont* next_arm, ::bbq::rho_t parent_val) {
        return ::bbq::rho_t{::bbq::RhoTag::InAlt, nullptr,
                            next_arm, arena_rho(parent_val)};
    }
    ::bbq::rho_t in_optional(bbq::cek::StaticKont* skip, ::bbq::rho_t parent_val) {
        return ::bbq::rho_t{::bbq::RhoTag::InOptional, nullptr,
                            skip, arena_rho(parent_val)};
    }
    ::bbq::rho_t in_array_elem(bbq::cek::StaticKont* skip,
                               ::bbq::rho_t parent_val) {
        return ::bbq::rho_t{::bbq::RhoTag::InArrayElem, nullptr,
                            skip, arena_rho(parent_val)};
    }

    // ── make_X allocators ─────────────────────────────────────

    bbq::cek::StaticKont* make_match_primitive(const std::string& nm, bbq::cek::PrimitiveInfo p, bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::MatchPrimitiveNode>();
        k->field_name = nm.empty() ? nullptr : strings_->intern(nm); k->prim = p; k->next = nx;
        return k;
    }
    bbq::cek::StaticKont* make_begin_struct(const std::string& nm, bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::BeginStructNode>();
        k->struct_name = strings_->intern(nm); k->next = nx;
        return k;
    }
    bbq::cek::StaticKont* make_end_struct(bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::EndStructNode>();
        k->next = nx;
        return k;
    }
    bbq::cek::StaticKont* make_eval_constraint(bbq::cek::StaticKont* e,
                                               bbq::cek::StaticKont* on_false,
                                               bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::EvalConstraintNode>();
        k->constraint_expr = e; k->on_false = on_false; k->next = nx;
        return k;
    }
    bbq::cek::StaticKont* make_bind_compute(const std::string& nm, bbq::cek::StaticKont* e, bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::BindComputeNode>();
        k->field_name = nm.empty() ? nullptr : strings_->intern(nm); k->compute_expr = e; k->next = nx;
        return k;
    }
    bbq::cek::StaticKont* make_invoke_rule(const std::string& nm,
                                           bbq::cek::StaticKont* caller_fail_target,
                                           bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::InvokeRuleNode>();
        k->rule_name = strings_->intern(nm);
        k->entry = nullptr;
        k->caller_fail_target = caller_fail_target;
        k->next = nx;
        pending_patches_.emplace_back(&k->entry, nm);
        return k;
    }
    bbq::cek::StaticKont* make_on_fail(bbq::cek::StaticKont* target,
                                       bbq::cek::StaticKont* next_on_fail,
                                       bool pop_frame) {
        auto* k = arena_->alloc<bbq::cek::OnFailKont>();
        k->target = target;
        k->next_on_fail = next_on_fail;
        k->pop_frame = pop_frame;
        return k;
    }
    bbq::cek::StaticKont* make_abort_rule() {
        return arena_->alloc<bbq::cek::AbortRuleKont>();
    }
    bbq::cek::StaticKont* make_return_rule(bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::ReturnRuleNode>();
        k->next = nx;
        return k;
    }
    bbq::cek::StaticKont* make_begin_choice(bbq::cek::StaticKont* on_fail_target,
                                            bbq::cek::StaticKont* first) {
        auto* k = arena_->alloc<bbq::cek::BeginChoiceNode>();
        k->on_fail_target = on_fail_target;
        k->next = first;
        return k;
    }
    bbq::cek::StaticKont* make_commit_choice(bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::CommitChoiceNode>();
        k->next = nx;
        return k;
    }
    bbq::cek::StaticKont* make_begin_optional(bbq::cek::StaticKont* on_fail_target,
                                              bbq::cek::StaticKont* inner,
                                              bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::BeginOptionalNode>();
        k->on_fail_target = on_fail_target;
        k->inner = inner;
        k->next = nx;
        return k;
    }
    bbq::cek::StaticKont* make_end_optional(bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::EndOptionalNode>();
        k->next = nx;
        return k;
    }
    bbq::cek::StaticKont* make_begin_array(const std::string& nm, bbq::cek::ArrayMode mode,
                                         bbq::cek::StaticKont* count_expr,
                                         bbq::cek::StaticKont* end_node,
                                         bbq::cek::StaticKont* resync_target,
                                         bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::BeginArrayNode>();
        k->array_name = strings_->intern(nm); k->mode = mode;
        k->count_expr = count_expr; k->end_node = end_node;
        k->resync_target = resync_target; k->next = nx;
        return k;
    }
    bbq::cek::StaticKont* make_array_next(bbq::cek::ArrayMode mode,
                                        bbq::cek::StaticKont* count_expr,
                                        bbq::cek::StaticKont* until_expr,
                                        bbq::cek::StaticKont* end_node,
                                        bbq::cek::StaticKont* body_entry,
                                        bool resync) {
        auto* k = arena_->alloc<bbq::cek::ArrayNextNode>();
        k->mode = mode;
        k->count_expr = count_expr; k->until_expr = until_expr;
        k->end_node = end_node; k->body_entry = body_entry;
        k->resync = resync;
        return k;
    }
    bbq::cek::StaticKont* make_end_array(bool resync, bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::EndArrayNode>();
        k->resync = resync;
        k->next = nx;
        return k;
    }
    bbq::cek::StaticKont* make_resync(bbq::cek::StaticKont* body_entry,
                                      bbq::cek::StaticKont* end_node) {
        auto* k = arena_->alloc<bbq::cek::ResyncKont>();
        k->body_entry = body_entry;
        k->end_node = end_node;
        return k;
    }
    bbq::cek::StaticKont* make_switch_dispatch(bbq::cek::StaticKont* disc,
                                             std::vector<bbq::cek::switch_case> cases,
                                             bbq::cek::StaticKont* dflt) {
        auto* k = arena_->alloc<bbq::cek::SwitchDispatchNode>();
        k->discriminator_expr = disc;
        if (!cases.empty()) {
            auto* buf = static_cast<bbq::cek::switch_case*>(
                arena_->allocate(cases.size() * sizeof(bbq::cek::switch_case),
                                 alignof(bbq::cek::switch_case)));
            for (size_t i = 0; i < cases.size(); ++i) buf[i] = cases[i];
            k->cases = buf;
            k->cases_count = static_cast<int>(cases.size());
        }
        k->default_target = dflt;
        return k;
    }
    bbq::cek::StaticKont* make_bitfield_read(bbq::cek::PrimitiveInfo container,
                                           std::vector<bbq::cek::bitfield_entry> entries,
                                           bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::BitfieldReadNode>();
        k->container = container;
        if (!entries.empty()) {
            auto* buf = static_cast<bbq::cek::bitfield_entry*>(
                arena_->allocate(entries.size() * sizeof(bbq::cek::bitfield_entry),
                                 alignof(bbq::cek::bitfield_entry)));
            for (size_t i = 0; i < entries.size(); ++i) buf[i] = entries[i];
            k->entries = buf;
            k->entries_count = static_cast<int>(entries.size());
        }
        k->next = nx;
        return k;
    }
    bbq::cek::StaticKont* make_set_endian(bbq::cek::StaticKont* e, bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::SetEndianNode>();
        k->endian_expr = e; k->next = nx;
        return k;
    }
    bbq::cek::StaticKont* make_external_call(const std::string& fn, const std::string& field, bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::ExternalCallNode>();
        k->func_name = strings_->intern(fn);
        k->field_name = strings_->intern(field);
        k->next = nx;
        return k;
    }
    bbq::cek::StaticKont* make_match_bytes(const std::string& fn, bbq::cek::StaticKont* len, bool is_str, bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::MatchBytesNode>();
        k->field_name = strings_->intern(fn);
        k->length_expr = len;
        k->is_string = is_str;
        k->next = nx;
        return k;
    }
    bbq::cek::StaticKont* make_halt() {
        return arena_->alloc<bbq::cek::HaltNode>();
    }

    // Expression leaves
    bbq::cek::StaticKont* make_int_lit(int64_t v) {
        auto* k = arena_->alloc<bbq::cek::IntLitKont>();
        k->v = v; return k;
    }
    bbq::cek::StaticKont* make_bool_lit(bool v) {
        auto* k = arena_->alloc<bbq::cek::BoolLitKont>();
        k->v = v; return k;
    }
    bbq::cek::StaticKont* make_float_lit(double v) {
        auto* k = arena_->alloc<bbq::cek::FloatLitKont>();
        k->v = v; return k;
    }
    bbq::cek::StaticKont* make_str_lit(const std::string& v) {
        auto* k = arena_->alloc<bbq::cek::StrLitKont>();
        k->v = strings_->intern(v); return k;
    }
    bbq::cek::StaticKont* make_ref(const std::string& nm) {
        auto* k = arena_->alloc<bbq::cek::RefKont>();
        k->name = strings_->intern(nm); return k;
    }
    bbq::cek::StaticKont* make_pos()       { return arena_->alloc<bbq::cek::PosKont>(); }
    bbq::cek::StaticKont* make_remaining() { return arena_->alloc<bbq::cek::RemainingKont>(); }
    bbq::cek::StaticKont* make_at_end()    { return arena_->alloc<bbq::cek::AtEndKont>(); }
    bbq::cek::StaticKont* make_eoi()       { return arena_->alloc<bbq::cek::EOIKont>(); }
    bbq::cek::StaticKont* make_loop_var()  { return arena_->alloc<bbq::cek::LoopVarKont>(); }

    // Unary
    bbq::cek::StaticKont* make_neg(bbq::cek::StaticKont* e) {
        auto* k = arena_->alloc<bbq::cek::NegKont>(); k->operand = e; return k;
    }
    bbq::cek::StaticKont* make_bit_not(bbq::cek::StaticKont* e) {
        auto* k = arena_->alloc<bbq::cek::BitNotKont>(); k->operand = e; return k;
    }
    bbq::cek::StaticKont* make_not(bbq::cek::StaticKont* e) {
        auto* k = arena_->alloc<bbq::cek::NotKont>(); k->operand = e; return k;
    }

    // Binop allocators (one per op kont).
#define BBQ_DDCG_BINOP_MAKE(name, KontType)                                         \
    bbq::cek::StaticKont* name(bbq::cek::StaticKont* l, bbq::cek::StaticKont* r) {        \
        auto* k = arena_->alloc<bbq::cek::KontType>();                              \
        k->left = l; k->right = r;                                                  \
        return k;                                                                   \
    }
    BBQ_DDCG_BINOP_MAKE(make_add,        AddKont)
    BBQ_DDCG_BINOP_MAKE(make_sub,        SubKont)
    BBQ_DDCG_BINOP_MAKE(make_mul,        MulKont)
    BBQ_DDCG_BINOP_MAKE(make_div,        DivKont)
    BBQ_DDCG_BINOP_MAKE(make_mod,        ModKont)
    BBQ_DDCG_BINOP_MAKE(make_bit_and,    BitAndKont)
    BBQ_DDCG_BINOP_MAKE(make_bit_or,     BitOrKont)
    BBQ_DDCG_BINOP_MAKE(make_bit_xor,    BitXorKont)
    BBQ_DDCG_BINOP_MAKE(make_shl,        ShlKont)
    BBQ_DDCG_BINOP_MAKE(make_shr,        ShrKont)
    BBQ_DDCG_BINOP_MAKE(make_eq,         EqKont)
    BBQ_DDCG_BINOP_MAKE(make_ne,         NeKont)
    BBQ_DDCG_BINOP_MAKE(make_lt,         LtKont)
    BBQ_DDCG_BINOP_MAKE(make_le,         LeKont)
    BBQ_DDCG_BINOP_MAKE(make_gt,         GtKont)
    BBQ_DDCG_BINOP_MAKE(make_ge,         GeKont)
    BBQ_DDCG_BINOP_MAKE(make_logical_and, LogicalAndKont)
    BBQ_DDCG_BINOP_MAKE(make_logical_or,  LogicalOrKont)
#undef BBQ_DDCG_BINOP_MAKE

    bbq::cek::StaticKont* make_ternary(bbq::cek::StaticKont* c, bbq::cek::StaticKont* t, bbq::cek::StaticKont* el) {
        auto* k = arena_->alloc<bbq::cek::TernaryKont>();
        k->cond = c; k->then_ = t; k->else_ = el;
        return k;
    }

    bbq::cek::StaticKont* make_call(const std::string& name, std::vector<bbq::cek::StaticKont*> args) {
        auto* k = arena_->alloc<bbq::cek::CallKont>();
        k->func_name = strings_->intern(name);
        if (!args.empty()) {
            auto** buf = static_cast<bbq::cek::KontNode**>(
                arena_->allocate(args.size() * sizeof(bbq::cek::KontNode*),
                                 alignof(bbq::cek::KontNode*)));
            for (size_t i = 0; i < args.size(); ++i) buf[i] = args[i];
            k->args = buf;
            k->args_count = static_cast<int>(args.size());
        }
        return k;
    }

    bbq::cek::StaticKont* make_path_start(const std::string& nm) {
        auto* k = arena_->alloc<bbq::cek::PathStartKont>();
        k->name = strings_->intern(nm); return k;
    }
    bbq::cek::StaticKont* make_field_access(const std::string& fld, bbq::cek::StaticKont* base) {
        auto* k = arena_->alloc<bbq::cek::FieldAccessKont>();
        k->field = strings_->intern(fld); k->base = base; return k;
    }
    bbq::cek::StaticKont* make_index_access(bbq::cek::StaticKont* idx, bbq::cek::StaticKont* base) {
        auto* k = arena_->alloc<bbq::cek::IndexAccessKont>();
        k->index_expr = idx; k->base = base; return k;
    }
    bbq::cek::StaticKont* make_capture_value(bbq::cek::StaticKont* path) {
        auto* k = arena_->alloc<bbq::cek::CaptureValueKont>();
        k->path = path; return k;
    }

    // ── Panic ─────────────────────────────────────────────────

    [[noreturn]] bbq::cek::StaticKont* panic_unreachable() {
        std::fprintf(stderr, "bbq.ddcg: paper-undefined gamma context (driver bug)\n");
        std::abort();
    }

    // ── Helpers ───────────────────────────────────────────────

    bbq::cek::PrimitiveInfo to_prim_info(BBQ::PrimitiveKind* kind) {
        bbq::cek::PrimitiveInfo p{};
        if (auto* ik = dynamic_cast<BBQ::IntegerKind*>(kind)) {
            p.kind = bbq::cek::PrimKind::Integer;
            switch (ik->width) {
                case BBQ::Width::W8:  p.width = bbq::cek::PrimWidth::W8;  break;
                case BBQ::Width::W16: p.width = bbq::cek::PrimWidth::W16; break;
                case BBQ::Width::W32: p.width = bbq::cek::PrimWidth::W32; break;
                case BBQ::Width::W64: p.width = bbq::cek::PrimWidth::W64; break;
            }
            p.sign = (ik->sign == BBQ::Signedness::Signed)
                ? bbq::cek::PrimSign::Signed : bbq::cek::PrimSign::Unsigned;
            switch (ik->endian) {
                case BBQ::Endianness::Little:  p.endian = bbq::cek::PrimEndian::Little; break;
                case BBQ::Endianness::Big:     p.endian = bbq::cek::PrimEndian::Big; break;
                case BBQ::Endianness::Default: p.endian = bbq::cek::PrimEndian::Native; break;
            }
        } else if (auto* fk = dynamic_cast<BBQ::FloatKind*>(kind)) {
            p.kind = bbq::cek::PrimKind::Float;
            p.width = (fk->width == BBQ::Width::W32) ? bbq::cek::PrimWidth::W32 : bbq::cek::PrimWidth::W64;
            switch (fk->endian) {
                case BBQ::Endianness::Little:  p.endian = bbq::cek::PrimEndian::Little; break;
                case BBQ::Endianness::Big:     p.endian = bbq::cek::PrimEndian::Big; break;
                case BBQ::Endianness::Default: p.endian = bbq::cek::PrimEndian::Native; break;
            }
        } else if (dynamic_cast<BBQ::BoolKind*>(kind)) {
            p.kind = bbq::cek::PrimKind::Bool;
            p.width = bbq::cek::PrimWidth::W8;
        }
        return p;
    }

    bool endian_to_bool(BBQ::Endianness e) {
        return e == BBQ::Endianness::Little;
    }

    bbq::cek::StaticKont*
    compile_array(BBQ::TypeExpr* element,
                  BBQ::ArraySpec* spec,
                  bool resync,
                  ::bbq::rho_t r,
                  bbq::cek::StaticKont* Lnext) {
        // Determine mode + count/until exprs from the AST spec.
        bbq::cek::ArrayMode mode = bbq::cek::ArrayMode::EOF_;
        bbq::cek::StaticKont* count_expr = nullptr;
        bbq::cek::StaticKont* until_expr = nullptr;

        if (auto* fc = dynamic_cast<BBQ::FixedCount*>(spec)) {
            mode = bbq::cek::ArrayMode::FixedCount;
            count_expr = compile_expr(fc->count, r, ::bbq::ac(),
                                      ::bbq::jump(Lnext), Lnext);
        } else if (auto* st = dynamic_cast<BBQ::SepTerm*>(spec)) {
            if (dynamic_cast<BBQ::EofTerm*>(st->term)) {
                mode = bbq::cek::ArrayMode::EOF_;
            } else if (auto* count_term = dynamic_cast<BBQ::CountTerm*>(st->term)) {
                mode = bbq::cek::ArrayMode::Count;
                count_expr = compile_expr(count_term->count, r, ::bbq::ac(),
                                          ::bbq::jump(Lnext), Lnext);
            } else if (auto* until_term = dynamic_cast<BBQ::UntilTerm*>(st->term)) {
                mode = bbq::cek::ArrayMode::Until;
                until_expr = compile_expr(until_term->condition, r, ::bbq::ac(),
                                          ::bbq::jump(Lnext), Lnext);
            }
        }

        // EndArray pops the LoopFrame (and the resync Savepoint, if
        // any) and chains into Lnext.
        bbq::cek::StaticKont* end_kont = make_end_array(resync, Lnext);

        // Allocate ArrayNext with body_entry=null; patch after body
        // compilation to break the cycle. ArrayNext refreshes the
        // resync savepoint (if any) per iteration.
        auto* array_next = arena_->alloc<bbq::cek::ArrayNextNode>();
        array_next->mode = mode;
        array_next->count_expr = count_expr;
        array_next->until_expr = until_expr;
        array_next->end_node = end_kont;
        array_next->body_entry = nullptr;
        array_next->resync = resync;

        // resync_target — allocated up front when in resync mode so
        // both the runtime Savepoint and the compile-time
        // in_array_elem.skip can carry the same ResyncKont.
        // body_entry is patched after element compile (cycle break,
        // same pattern as ArrayNext.body_entry).
        bbq::cek::ResyncKont* resync_kont = nullptr;
        if (resync) {
            resync_kont = arena_->alloc<bbq::cek::ResyncKont>();
            resync_kont->body_entry = nullptr;
            resync_kont->end_node = end_kont;
        }

        // Compile element body with ρ pushed for the array element
        // scope. in_array_elem is a name barrier (elements are
        // anonymous), and in resync mode it carries the ResyncKont
        // so where-checks inside the element body dispatch to it via
        // on_false — the same target the runtime Savepoint uses.
        std::string array_name = intern_field_or_anon(r);
        ::bbq::rho_t elem_rho = in_array_elem(resync_kont, r);
        bbq::cek::StaticKont* body_head = compile_type_expr(
            element, elem_rho, ::bbq::effect(),
            ::bbq::jump(array_next), array_next);
        array_next->body_entry = body_head;
        if (resync_kont) resync_kont->body_entry = body_head;

        return make_begin_array(array_name, mode,
                                count_expr, end_kont,
                                resync_kont, body_head);
    }

    bbq::cek::StaticKont*
    compile_alternatives(std::vector<BBQ::TypeExpr*> alts,
                         ::bbq::rho_t r,
                         bbq::cek::StaticKont* Lnext) {
        if (alts.empty()) return Lnext;
        if (alts.size() == 1) {
            // Single alternative — no choice, just compile it.
            return compile_type_expr(alts[0], r, ::bbq::effect(),
                                     ::bbq::jump(Lnext), Lnext);
        }
        // Each non-last arm's success path threads through CommitChoice
        // (pops the Savepoint and chains to Lnext). The last arm
        // chains directly to Lnext — the Savepoint pops via the
        // "exhausted" OnFailKont if the last arm itself fails.
        auto* commit = make_commit_choice(Lnext);

        // Compile arms right-to-left so each link in the OnFailKont
        // chain knows the next arm's entry. The same link serves as
        // (a) the runtime Savepoint.on_fail_target for byte-fails and
        // (b) the static in_alt.next_arm for where-fails routed via
        // on_false. Both paths converge on the same OnFailKont.
        bbq::cek::StaticKont* exhausted =
            make_on_fail(nullptr, nullptr, /*pop_frame=*/true);
        bbq::cek::StaticKont* last_entry = compile_type_expr(
            alts.back(), r, ::bbq::effect(),
            ::bbq::jump(Lnext), Lnext);
        bbq::cek::StaticKont* next_link = exhausted;
        bbq::cek::StaticKont* next_target = last_entry;
        // Walk N-2..1 (skip 0; first arm is BeginChoice.next).
        for (size_t i = alts.size() - 1; i-- > 1; ) {
            bbq::cek::StaticKont* link =
                make_on_fail(next_target, next_link, /*pop_frame=*/false);
            // Push in_alt with this arm's failure target so any
            // where-check inside the arm body resolves on_false to
            // `link` via find_backtrack_target.
            ::bbq::rho_t arm_rho = in_alt(link, r);
            bbq::cek::StaticKont* arm_entry = compile_type_expr(
                alts[i], arm_rho, ::bbq::effect(),
                ::bbq::jump(commit), commit);
            next_link = link;
            next_target = arm_entry;
        }
        // Arm 0's failure target = head link of the chain. The arm
        // sees in_alt(head_link, parent) as its ρ.
        bbq::cek::StaticKont* head_link =
            make_on_fail(next_target, next_link, /*pop_frame=*/false);
        ::bbq::rho_t arm0_rho = in_alt(head_link, r);
        bbq::cek::StaticKont* first = compile_type_expr(
            alts[0], arm0_rho, ::bbq::effect(),
            ::bbq::jump(commit), commit);
        return make_begin_choice(head_link, first);
    }

    bbq::cek::StaticKont*
    compile_union(std::vector<BBQ::Variant*> variants,
                  ::bbq::rho_t r,
                  bbq::cek::StaticKont* Lnext) {
        // Each variant has a body type_expr; treat them as alternatives.
        std::vector<BBQ::TypeExpr*> alts;
        alts.reserve(variants.size());
        for (auto* v : variants) alts.push_back(v->body);
        return compile_alternatives(alts, r, Lnext);
    }

    bbq::cek::StaticKont*
    compile_primitive(BBQ::PrimitiveKind* kind,
                      std::optional<BBQ::Expr*> constraint,
                      std::optional<BBQ::Interval*> interval,
                      ::bbq::rho_t r,
                      bbq::cek::StaticKont* Lnext) {
        // Emit the constraint check first (it's the LAST thing to run
        // after the primitive read), wrapped around Lnext.
        bbq::cek::StaticKont* tail = Lnext;
        if (constraint.has_value() && constraint.value()) {
            auto* expr_ir = compile_expr(constraint.value(), r,
                                         ::bbq::ac(), ::bbq::jump(Lnext), Lnext);
            // on_false is the static failure target for this where-
            // check, resolved from ρ at compile time. find_backtrack_
            // target walks ρ to the innermost in_alt / in_optional /
            // in_array_elem(skip!=null) and returns that scope's
            // failure handler. If ρ bottoms out at root with no
            // backtrackable frame in scope, AbortRuleKont takes over
            // and crosses the rule boundary into the caller's chain.
            bbq::cek::StaticKont* on_false = find_backtrack_target(r);
            if (!on_false) on_false = make_abort_rule();
            tail = make_eval_constraint(expr_ir, on_false, Lnext);
        }

        // Bytes/String → MatchBytes with the interval-derived length.
        if (dynamic_cast<BBQ::BytesKind*>(kind) != nullptr ||
            dynamic_cast<BBQ::StringKind*>(kind) != nullptr) {
            bool is_string = (dynamic_cast<BBQ::StringKind*>(kind) != nullptr);
            // Interval must be Length(expr) for bytes/string with
            // variable length.
            bbq::cek::StaticKont* length_expr = nullptr;
            if (interval.has_value()) {
                if (auto* len = dynamic_cast<BBQ::Length*>(interval.value())) {
                    length_expr = compile_expr(len->length, r,
                                               ::bbq::ac(),
                                               ::bbq::jump(tail), tail);
                }
            }
            if (length_expr == nullptr) {
                // No interval / not Length — emit a literal 0-length;
                // runtime will produce an empty bytes capture. Sema
                // catches missing-length-on-bytes earlier so this is
                // a defensive default.
                length_expr = make_int_lit(0);
            }
            return make_match_bytes(intern_field_or_anon(r),
                                    length_expr, is_string, tail);
        }

        // Other primitives → MatchPrimitive.
        bbq::cek::PrimitiveInfo prim = to_prim_info(kind);
        return make_match_primitive(intern_field_or_anon(r), prim, tail);
    }

    // Walk ρ to the innermost in_field, returning its name.
    // in_alt and in_optional are transparent — a where-fail inside
    // an alternative arm or optional inner still wants the enclosing
    // field's name for its capture. in_array_elem is a name barrier:
    // array elements are anonymous regardless of the enclosing array's
    // name, so the walk stops there and returns empty. Empty when no
    // in_field is in scope (rule body level, anonymous capture).
    std::string intern_field_or_anon(::bbq::rho_t r) {
        const ::bbq::rho_t* p = &r;
        while (p) {
            switch (p->tag) {
                case ::bbq::RhoTag::InField:
                    return p->name ? std::string(p->name) : std::string();
                case ::bbq::RhoTag::InArrayElem:
                case ::bbq::RhoTag::Root:
                    return std::string();
                case ::bbq::RhoTag::InAlt:
                case ::bbq::RhoTag::InOptional:
                    p = p->parent;
                    continue;
            }
        }
        return std::string();
    }

    // Walk ρ to find the static failure target for the innermost
    // backtrackable scope. Returns nullptr when ρ bottoms out at root
    // with no backtrack frame in scope — caller substitutes
    // AbortRuleKont so the failure crosses the rule boundary into the
    // caller's nearest scope (via ReturnFrame::rule_fail_target).
    //
    // in_field is transparent (a where-check inside a named field
    // still backtracks to whatever the surrounding scope provides).
    // in_array_elem is transparent unless `skip` is set — non-null
    // skip means resync mode, so element-fail goes to the resync
    // handler; null skip means the array doesn't recover from element
    // failure and the walk continues outward.
    bbq::cek::StaticKont* find_backtrack_target(::bbq::rho_t r) {
        const ::bbq::rho_t* p = &r;
        while (p) {
            switch (p->tag) {
                case ::bbq::RhoTag::Root:
                    return nullptr;
                case ::bbq::RhoTag::InAlt:
                    return p->fail_target;
                case ::bbq::RhoTag::InOptional:
                    return p->fail_target;
                case ::bbq::RhoTag::InArrayElem:
                    if (p->fail_target) return p->fail_target;
                    p = p->parent;
                    continue;
                case ::bbq::RhoTag::InField:
                    p = p->parent;
                    continue;
            }
        }
        return nullptr;
    }

    bbq::cek::StaticKont* make_ref_or_builtin(const std::string& n) {
        if (n == "i")         return make_loop_var();
        if (n == "pos")       return make_pos();
        if (n == "remaining") return make_remaining();
        if (n == "at_end")    return make_at_end();
        return make_ref(n);
    }

    // ── Helper implementations ────────────────────────
    //
    // These are MEMBER methods that the rule bodies call. They take
    // AST nodes/lists by value (matching what ddcgc passes through
    // the auto-generated dispatch) and return either an IR sub-tree
    // or a list of IR shapes. They recursively call compile_expr /
    // compile_type_expr (the auto-generated dispatch entries) which
    // ddcgc declares on this class.

    std::vector<bbq::cek::StaticKont*>
    compile_call_args(std::vector<BBQ::Expr*> args, ::bbq::rho_t r,
                      bbq::cek::StaticKont* Lnext) {
        std::vector<bbq::cek::StaticKont*> out;
        out.reserve(args.size());
        for (auto* a : args) {
            out.push_back(compile_expr(a, r, ::bbq::ac(), ::bbq::jump(Lnext), Lnext));
        }
        return out;
    }

    bbq::cek::StaticKont*
    compile_fields(std::vector<BBQ::Field*> fields, ::bbq::rho_t r,
                   bbq::cek::StaticKont* tail) {
        // Compile fields in reverse so each field's `next` chains to
        // the already-compiled tail. Each field body sees its own ρ
        // frame in_field(name, parent=r); the parent link preserves any
        // backtrack frame visible at struct entry.
        bbq::cek::StaticKont* chain = tail;
        for (auto it = fields.rbegin(); it != fields.rend(); ++it) {
            BBQ::Field* f = *it;
            chain = compile_type_expr(
                f->body, in_field(f->name, r),
                ::bbq::effect(), ::bbq::jump(chain), chain);
        }
        return chain;
    }

    std::vector<bbq::cek::bitfield_entry>
    compile_bitfield_entries(std::vector<BBQ::BitfieldEntry*> entries) {
        std::vector<bbq::cek::bitfield_entry> out;
        out.reserve(entries.size());
        for (auto* e : entries) {
            bbq::cek::bitfield_entry b{};
            b.name = strings_->intern(e->name);
            b.width_bits = static_cast<int>(e->width);
            out.push_back(b);
        }
        return out;
    }

    bbq::cek::StaticKont*
    compile_switch_default(std::optional<BBQ::SwitchDefault*> dflt, ::bbq::rho_t r,
                           bbq::cek::StaticKont* Lnext) {
        if (!dflt.has_value() || !dflt.value()) return nullptr;
        // `default: reject` has no target — caller (compile_switch)
        // emits a fail node directly. Returning nullptr here triggers
        // that path uniformly with the no-default case.
        if (dflt.value()->is_reject || !dflt.value()->target.has_value())
            return nullptr;
        return compile_type_expr(*dflt.value()->target, r, ::bbq::effect(),
                                 ::bbq::jump(Lnext), Lnext);
    }

    std::vector<bbq::cek::switch_case>
    compile_switch_cases(std::vector<BBQ::SwitchCase*> cases, ::bbq::rho_t r,
                         bbq::cek::StaticKont* Lnext) {
        std::vector<bbq::cek::switch_case> out;
        out.reserve(cases.size());
        for (auto* c : cases) {
            bbq::cek::switch_case sc{};
            sc.match_value = case_value_to_value(c->value);
            sc.target = compile_type_expr(c->target, r, ::bbq::effect(),
                                          ::bbq::jump(Lnext), Lnext);
            out.push_back(sc);
        }
        return out;
    }

    // Convert a BBQ AST case_value variant into a typed Value.
    // Cases are int or string at the AST level; runtime SwitchSelect
    // matches by tag + interned-pointer or scalar comparison.
    bbq::cek::Value* case_value_to_value(BBQ::CaseValue* cv) {
        if (auto* iv = dynamic_cast<BBQ::IntValue*>(cv)) {
            auto* v = arena_->alloc<bbq::cek::IntValue>();
            v->v = iv->value;
            return v;
        }
        if (auto* sv = dynamic_cast<BBQ::StrValue*>(cv)) {
            auto* v = arena_->alloc<bbq::cek::StringValue>();
            v->v = strings_->intern(sv->value);
            return v;
        }
        if (auto* iv = dynamic_cast<BBQ::IdentValue*>(cv)) {
            // IdentValue's payload is `name` (identifier), not `value`.
            auto* v = arena_->alloc<bbq::cek::StringValue>();
            v->v = strings_->intern(iv->name);
            return v;
        }
        return nullptr;
    }

    // Path navigation: walk a RefPath (Simple / FieldAcc / IndexAcc)
    // outward-in, building a chain of path-nav konts. The outermost
    // call wraps with CaptureValue when then_capture is true.
    bbq::cek::StaticKont*
    compile_ref_path(BBQ::RefPath* path, const std::string& field, bool then_capture) {
        if (auto* simple = dynamic_cast<BBQ::Simple*>(path)) {
            auto* base = make_path_start(simple->name);
            auto* fa = make_field_access(field, base);
            return then_capture ? make_capture_value(fa) : fa;
        }
        if (auto* fa = dynamic_cast<BBQ::FieldAcc*>(path)) {
            auto* base = compile_ref_path(fa->base, fa->field, false);
            auto* step = make_field_access(field, base);
            return then_capture ? make_capture_value(step) : step;
        }
        if (auto* ia = dynamic_cast<BBQ::IndexAcc*>(path)) {
            // Index expressions are pure value-producers — no
            // backtrackable scope to inherit. Compile with ρ=root.
            ::bbq::rho_t r = root();
            auto* idx = compile_expr(ia->index, r, ::bbq::ac(),
                                     ::bbq::jump(nullptr), nullptr);
            auto* base = compile_ref_path(ia->base, "", false);
            auto* step = make_index_access(idx, base);
            auto* fa_step = make_field_access(field, step);
            return then_capture ? make_capture_value(fa_step) : fa_step;
        }
        return nullptr;
    }

    bbq::cek::StaticKont*
    compile_ref_index_path(BBQ::RefPath* base_path, bbq::cek::StaticKont* idx, bool then_capture) {
        auto* base = compile_ref_path(base_path, "", false);
        auto* step = make_index_access(idx, base);
        return then_capture ? make_capture_value(step) : step;
    }
    // ─── End PRIVATE ────────────────────────────
protected:
    // ─── action-language funs ───────────────────
    // Internal helpers; consumer (subclass) calls
    // these from rule bodies and other funs, not
    // from external code.

    // fun cg_jump
    bbq_ir::StaticKont* cg_jump(gamma_t g, bbq_ir::StaticKont* Lnext) {
        return ([&]() -> bbq_ir::StaticKont* {
            auto _m = g;
            switch (_m.tag) {
            case GammaTag::Jump: {
                auto L = _m.L;
                return ((L == Lnext) ? Lnext : panic_unreachable());
            }
            }
            return {};
        })();
    }

    // fun cg_deliver
    bbq_ir::StaticKont* cg_deliver(bbq_ir::StaticKont* value, delta_t d, gamma_t g, bbq_ir::StaticKont* Lnext) {
        return ([&]() -> bbq_ir::StaticKont* {
            auto _m = g;
            switch (_m.tag) {
            case GammaTag::Jump: {
                auto L = _m.L;
                return ((L == Lnext) ? value : panic_unreachable());
            }
            }
            return {};
        })();
    }
private:

    // Dispatcher for ast.expr
    bbq_ir::StaticKont* compile_expr(BBQ::Expr* node, rho_t rho, delta_t delta, gamma_t gamma, bbq_ir::StaticKont* Lnext = {}) {
        (void)delta; (void)gamma; (void)Lnext;
        (void)rho;
        current_loc = node->loc;
        if (auto* _n0 = dynamic_cast<BBQ::IntLit*>(node)) {
            auto n = _n0->value;
            return cg_deliver(make_int_lit(n), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::BoolLit*>(node)) {
            auto b = _n0->value;
            return cg_deliver(make_bool_lit(b), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::FloatLit*>(node)) {
            auto f = _n0->value;
            return cg_deliver(make_float_lit(f), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::StrLit*>(node)) {
            auto s = _n0->value;
            return cg_deliver(make_str_lit(s), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::EOI*>(node)) {
            return cg_deliver(make_eoi(), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::Ref*>(node)) {
            if (auto* _n1 = dynamic_cast<BBQ::Simple*>(_n0->path)) {
                auto n = _n1->name;
                return cg_deliver(make_ref_or_builtin(n), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::Ref*>(node)) {
            if (auto* _n1 = dynamic_cast<BBQ::FieldAcc*>(_n0->path)) {
                auto b = _n1->base;
                auto f = _n1->field;
                bbq_ir::StaticKont* path_node = compile_ref_path(b, f, false);
                return cg_deliver(make_capture_value(path_node), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::Ref*>(node)) {
            if (auto* _n1 = dynamic_cast<BBQ::IndexAcc*>(_n0->path)) {
                auto b = _n1->base;
                auto i = _n1->index;
                bbq_ir::StaticKont* idx = compile_expr(i, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* path_node = compile_ref_index_path(b, idx, false);
                return cg_deliver(make_capture_value(path_node), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::Add)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_add(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::Sub)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_sub(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::Mul)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_mul(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::Div)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_div(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::Mod)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_mod(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::BitAnd)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_bit_and(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::BitOr)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_bit_or(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::BitXor)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_bit_xor(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::Shl)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_shl(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::Shr)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_shr(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::Eq)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_eq(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::Ne)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_ne(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::Lt)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_lt(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::Le)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_le(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::Gt)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_gt(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::Ge)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_ge(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::And)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_logical_and(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::Or)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_logical_or(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::UnaryOp*>(node)) {
            auto e = _n0->operand;
            if ((_n0->op == BBQ::Unaryop::Neg)) {
                bbq_ir::StaticKont* ev = compile_expr(e, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_neg(ev), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::UnaryOp*>(node)) {
            auto e = _n0->operand;
            if ((_n0->op == BBQ::Unaryop::BitNot)) {
                bbq_ir::StaticKont* ev = compile_expr(e, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_bit_not(ev), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::UnaryOp*>(node)) {
            auto e = _n0->operand;
            if ((_n0->op == BBQ::Unaryop::Not)) {
                bbq_ir::StaticKont* ev = compile_expr(e, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_not(ev), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::Ternary*>(node)) {
            auto c = _n0->cond;
            auto t = _n0->then_branch;
            auto el = _n0->else_branch;
            bbq_ir::StaticKont* cv = compile_expr(c, rho, ac(), jump(Lnext), Lnext);
            bbq_ir::StaticKont* tv = compile_expr(t, rho, ac(), jump(Lnext), Lnext);
            bbq_ir::StaticKont* ev = compile_expr(el, rho, ac(), jump(Lnext), Lnext);
            return cg_deliver(make_ternary(cv, tv, ev), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::EndianLit*>(node)) {
            auto v = _n0->value;
            return cg_deliver(make_bool_lit(endian_to_bool(v)), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::Call*>(node)) {
            auto f = _n0->func;
            auto as = _n0->args;
            std::vector<bbq_ir::StaticKont*> arg_irs = compile_call_args(as, rho, Lnext);
            return cg_deliver(make_call(f, arg_irs), delta, gamma, Lnext);
        }
        return {};
    }

    // Dispatcher for ast.rule
    bbq_ir::StaticKont* compile_rule(BBQ::Rule* node, rho_t rho, delta_t delta, gamma_t gamma, bbq_ir::StaticKont* Lnext = {}) {
        (void)delta; (void)gamma; (void)Lnext;
        (void)rho;
        current_loc = node->loc;
        if (auto* _n0 = dynamic_cast<BBQ::Rule*>(node)) {
            auto n = _n0->name;
            auto b = _n0->body;
            return compile_type_expr(b, rho, delta, gamma, Lnext);
        }
        return {};
    }

    // Dispatcher for ast.type_expr
    bbq_ir::StaticKont* compile_type_expr(BBQ::TypeExpr* node, rho_t rho, delta_t delta, gamma_t gamma, bbq_ir::StaticKont* Lnext = {}) {
        (void)delta; (void)gamma; (void)Lnext;
        (void)rho;
        current_loc = node->loc;
        if (auto* _n0 = dynamic_cast<BBQ::Struct*>(node)) {
            auto fs = _n0->fields;
            bbq_ir::StaticKont* end_kont = make_end_struct(Lnext);
            bbq_ir::StaticKont* fields_chain = compile_fields(fs, rho, end_kont);
            return cg_deliver(make_begin_struct(intern_field_or_anon(rho), fields_chain), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::Primitive*>(node)) {
            auto k = _n0->kind;
            auto cn = _n0->constraint.has_value() ? *_n0->constraint : nullptr;
            auto iv = _n0->interval.has_value() ? *_n0->interval : nullptr;
            return cg_deliver(compile_primitive(k, cn, iv, rho, Lnext), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::RuleRef*>(node)) {
            auto n = _n0->name;
            bbq_ir::StaticKont* end_st = make_end_struct(Lnext);
            bbq_ir::StaticKont* invoke = make_invoke_rule(n, find_backtrack_target(rho), end_st);
            return cg_deliver(make_begin_struct(intern_field_or_anon(rho), invoke), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::Compute*>(node)) {
            auto e = _n0->expression;
            bbq_ir::StaticKont* expr_ir = compile_expr(e, rho, ac(), jump(Lnext), Lnext);
            return cg_deliver(make_bind_compute(intern_field_or_anon(rho), expr_ir, Lnext), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::Extern*>(node)) {
            auto f = _n0->func_name;
            return cg_deliver(make_external_call(f, intern_field_or_anon(rho), Lnext), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::EndianSwitch*>(node)) {
            auto e = _n0->endian_expr;
            bbq_ir::StaticKont* expr_ir = compile_expr(e, rho, ac(), jump(Lnext), Lnext);
            return cg_deliver(make_set_endian(expr_ir, Lnext), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::Bitfield*>(node)) {
            auto c = _n0->container;
            auto es = _n0->entries;
            auto prim = to_prim_info(c);
            std::vector<bbq_ir::bitfield_entry> entry_list = compile_bitfield_entries(es);
            return cg_deliver(make_bitfield_read(prim, entry_list, Lnext), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::Optional*>(node)) {
            auto e = _n0->element;
            bbq_ir::StaticKont* end = make_end_optional(Lnext);
            bbq_ir::StaticKont* skip = make_on_fail(Lnext, nullptr, true);
            bbq_ir::StaticKont* inner = compile_type_expr(e, in_optional(skip, rho), effect(), jump(end), end);
            return cg_deliver(make_begin_optional(skip, inner, Lnext), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::Switch*>(node)) {
            auto d = _n0->discriminator;
            auto cs = _n0->cases;
            auto dflt = _n0->default_.has_value() ? *_n0->default_ : nullptr;
            std::vector<bbq_ir::switch_case> cs_list = compile_switch_cases(cs, rho, Lnext);
            bbq_ir::StaticKont* disc = compile_expr(d, rho, ac(), jump(Lnext), Lnext);
            bbq_ir::StaticKont* default_target = compile_switch_default(dflt, rho, Lnext);
            return cg_deliver(make_switch_dispatch(disc, cs_list, default_target), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::Alternatives*>(node)) {
            auto a = _n0->alts;
            return cg_deliver(compile_alternatives(a, rho, Lnext), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::Union*>(node)) {
            auto vs = _n0->variants;
            return cg_deliver(compile_union(vs, rho, Lnext), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::Array*>(node)) {
            auto e = _n0->element;
            auto s = _n0->spec;
            auto rs = _n0->resync;
            return cg_deliver(compile_array(e, s, rs, rho, Lnext), delta, gamma, Lnext);
        }
        return {};
    }
};

} // namespace bbq
