// Generated by ddcgc — do not edit
#pragma once
//
// Shape: `class Compiler` inside `namespace bbq`.
// MEMBERS verbatim block holds the consumer's state and the
// aux/pred bodies (called as bare methods on `this`). The
// generated dispatch methods read `current_loc` / call
// `fresh_label()` if RULES use `label`; the consumer must
// declare those in MEMBERS.
//
// The two destination types `<data_dest>_t` and `<ctrl_dest>_t`
// must exist at namespace scope, with one constructor function
// per variant — those are *namespace-level*, not class members,
// because callers of `compile_<sum>` build δ/γ values themselves.


   #include "BBQ_AST.h"
   #include "Sema.h"
   #include "KontNode.h"
   #include "ParseArena.h"
   #include "StringPool.h"
   #include "CompiledGrammar.h"
   #include <cassert>
   #include <cstring>
   #include <cstdio>
   #include <unordered_map>
   #include <utility>
   #include <vector>

   // ddcgc references generated IR types as `bbq_ir::*` (matching the
   // asdl module name `module bbq_ir`). Our hand-written runtime
   // declares them in `bbq::cek::` (the existing CEK namespace).
   // Alias one to the other so the ddcg-generated Compiler class
   // finds StaticKont / DynamicKont / Value / etc.
   namespace bbq_ir = bbq::cek;

   // Destination types live at `namespace bbq` scope — that's where
   // ddcgc generates `class Compiler`, and the generated dispatch
   // methods reference these as bare names (delta_t / gamma_t / rho_t).
   namespace bbq {

   // δ — paper §3.1 Location class. BBQ uses {effect, ac}.
   enum class DeltaTag : unsigned char { Effect, Ac, Stack, Local };
   struct delta_t { DeltaTag tag; int i; };
   inline delta_t effect()        { return {DeltaTag::Effect, 0}; }
   inline delta_t ac()            { return {DeltaTag::Ac,     0}; }
   inline delta_t stack()         { return {DeltaTag::Stack,  0}; }
   inline delta_t local(int i)    { return {DeltaTag::Local,  i}; }

   // γ — paper §3.2 control destination. BBQ uses jump(L) only.
   enum class GammaTag : unsigned char { Jump, Pair, Ret };
   struct gamma_t {
       GammaTag tag;
       bbq::cek::StaticKont* L;
       bbq::cek::StaticKont* Lt;
       bbq::cek::StaticKont* Lf;
   };
   inline gamma_t jump(bbq::cek::StaticKont* L)                                       { return {GammaTag::Jump, L,       nullptr, nullptr}; }
   inline gamma_t pair(bbq::cek::StaticKont* Lt, bbq::cek::StaticKont* Lf)            { return {GammaTag::Pair, nullptr, Lt,      Lf}; }
   inline gamma_t ret()                                                                { return {GammaTag::Ret,  nullptr, nullptr, nullptr}; }

   // ρ — lexical-scope chain consumed at compile time only. The
   // yoctojc pattern: each backtrackable scope wraps the caller's ρ
   // with a frame carrying the static failure target for inner
   // where-checks. find_backtrack_target walks ρ at compile time to
   // resolve the on_false destination; intern_field_or_anon walks to
   // the innermost in_field for capture naming.
   //
   //   in_field      — current field name, for capture metadata.
   //                   intern_field_or_anon walks to it.
   //   in_alt        — non-last arm of an alt; next_arm is the
   //                   compile-time-baked OnFailKont link that
   //                   restores the savepoint and dispatches to the
   //                   next arm.
   //   in_optional   — optional inner; skip is the OnFailKont link
   //                   that restores + pops + jumps past the optional.
   //   in_array_elem — array-element scope. Acts as a name barrier
   //                   for intern_field_or_anon. skip is non-null only
   //                   in resync mode (= the ResyncKont); otherwise
   //                   find_backtrack_target walks past transparently.
   //
   // The struct is a POD; `parent` is a pointer because C++ structs
   // can't recurse by value. Constructors are Compiler member methods
   // (see PRIVATE block) so parent allocation goes through arena_;
   // ddcgc-emitted calls resolve to `this->ctor(...)` via bare-name
   // lookup in dispatcher methods.
   enum class RhoTag : unsigned char {
       Root,
       InField,
       InAlt,
       InOptional,
       InArrayElem,
   };
   struct rho_t {
       RhoTag tag;
       const char* name;                  // InField only
       bbq::cek::StaticKont* fail_target; // InAlt.next_arm / InOptional.skip / InArrayElem.skip
       rho_t* parent;                     // every non-Root variant
   };

   } // namespace bbq

#include <vector>
#include <tuple>
#include <string>

namespace bbq {

template <class T>
static inline std::vector<T> _ddcgc_concat(std::vector<T> a,
                                            const std::vector<T>& b) {
    a.insert(a.end(), b.begin(), b.end());
    return a;
}

class Compiler {
public:
    // ─── MEMBERS (verbatim) ─────────────────────

    // ── Public API: the only entry point on bbq::Compiler ──────
    //
    // Per design doc §5.4: the driver owns program-exit wrapping.
    // For each rule:
    //   1. Allocate the rule's exit kont chain: Halt at the bottom,
    //      ReturnRule on top. Top-level entries push a throwaway
    //      ReturnFrame in the runtime so ReturnRule has something to
    //      pop; inner calls (via InvokeRule) push real ReturnFrames.
    //   2. Compile the rule body with γ=jump(exit). Top-level Struct
    //      bodies inline (no BeginStruct wrapper) so user-facing
    //      results expose `result.<field>` rather than
    //      `result.<empty>.<field>`.
    //   3. Record the body head in rule_entries_.
    //
    // After every rule has compiled, walk pending_patches_ and resolve
    // each (slot, name) to rule_entries_[name]. Sema rejects refs to
    // unknown rule names before we get here, so an unresolved patch
    // means an internal invariant was broken.
    bbq::cek::CompiledGrammar* compile_grammar(BBQ::Grammar* grammar) {
        if (!grammar) return nullptr;
        auto* result = new bbq::cek::CompiledGrammar();
        arena_   = &result->arena;
        strings_ = &result->strings;
        rule_entries_.clear();
        pending_patches_.clear();

        std::vector<bbq::cek::CompiledGrammar::RuleEntry> entries;
        entries.reserve(grammar->rules.size());

        for (auto* rule : grammar->rules) {
            auto* halt = arena_->alloc<bbq::cek::HaltNode>();
            auto* exit_kont = make_return_rule(halt);
            auto* exit_static = static_cast<bbq::cek::StaticKont*>(exit_kont);

            ::bbq::rho_t rho = root();
            bbq::cek::StaticKont* body_head = nullptr;
            if (auto* st = dynamic_cast<BBQ::Struct*>(rule->body)) {
                // Top-level structs inline their fields directly (no BeginStruct
                // wrapper). A struct-level `where` still applies: it runs after the
                // fields, before ReturnRule. (struct_def handles the nested case.)
                bbq::cek::StaticKont* tail = wrap_struct_where(st->constraint, rho, exit_static);
                body_head = compile_fields(st->fields, rho, tail);
            } else if (auto* bf = dynamic_cast<BBQ::Bitfield*>(rule->body)) {
                // Top-level bitfields inline their members directly into the rule
                // struct (no BeginStruct wrapper), the same shape as top-level
                // structs. bitfield_def handles the nested (inline field) case,
                // where the members must sit under their own sub-struct scope.
                bbq::cek::PrimitiveInfo prim = to_prim_info(bf->container);
                body_head = compile_bitfield(prim, bf->entries, rho, exit_static);
            } else {
                body_head = compile_type_expr(
                    rule->body, rho, ::bbq::effect(),
                    ::bbq::jump(exit_static), exit_static);
            }

            rule_entries_[rule->name] = body_head;
            entries.push_back({result->strings.intern(rule->name), body_head});
        }

        // Resolve every InvokeRuleNode's entry by looking up its rule
        // name in rule_entries_. Recursive grammars round-trip cleanly
        // here: the back-edge from kid → Tree finds Tree's body head.
        for (auto& [slot, name] : pending_patches_) {
            auto it = rule_entries_.find(name);
            if (it == rule_entries_.end()) {
                std::fprintf(stderr,
                    "bbq compile: unresolved rule reference '%s' "
                    "(Sema should have caught this)\n", name.c_str());
                std::abort();
            }
            *slot = it->second;
        }

        if (!entries.empty()) {
            result->rules = static_cast<bbq::cek::CompiledGrammar::RuleEntry*>(
                result->arena.allocate(
                    entries.size() * sizeof(bbq::cek::CompiledGrammar::RuleEntry),
                    alignof(bbq::cek::CompiledGrammar::RuleEntry)));
            for (size_t i = 0; i < entries.size(); ++i) {
                result->rules[i] = entries[i];
            }
            result->rule_count = static_cast<int>(entries.size());
        }

        for (auto* d : grammar->directives) {
            if (auto* ed = dynamic_cast<BBQ::EndianDirective*>(d)) {
                result->default_little_endian =
                    (ed->endian == BBQ::Endianness::Little);
            }
        }

        // Pre-intern built-in function names into result->strings so
        // CallApplyKont's dispatch can use pointer-equality against
        // call-site func_name pointers (also interned in this pool).
        bbq::cek::populate_builtins(*result);

        return result;
    }
    // ─── End MEMBERS ────────────────────────────
private:
    // ─── PRIVATE (verbatim) ─────────────────────

    // Allocation arena for IR konts, owned by the compiled grammar.
    bbq::ParseArena* arena_ = nullptr;
    bbq::cek::StringPool* strings_ = nullptr;

    // Rule entry table — populated as each rule finishes compiling.
    // After the per-rule loop in compile_grammar, every rule name maps
    // to its real body-head kont. pending_patches_ is then resolved
    // against this table.
    std::unordered_map<std::string, bbq::cek::StaticKont*> rule_entries_;

    // Forward-reference patch list. make_invoke_rule allocates an
    // InvokeRuleNode with entry=nullptr and pushes (&node->entry, name)
    // onto this list. compile_grammar walks the list at the end and
    // resolves each slot to rule_entries_[name]. Sema rejects any
    // unknown name before we get here, so unresolved entries indicate
    // a Sema/compiler invariant violation and abort.
    std::vector<std::pair<bbq::cek::KontNode**, std::string>> pending_patches_;

    // ddcgc-generated dispatch threads `current_loc` from each AST
    // node it traverses (via `current_loc = node->loc`). Type matches
    // BBQ_AST.h's SourceLoc. Rule bodies don't currently consume it
    // but keeping it correct so generated code compiles.
    BBQ::SourceLoc current_loc{};

    // ── ρ constructors (member methods so parent allocation hits arena_) ──
    //
    // The C++ ddcg backend calls these as `this->ctor(...)` via bare-
    // name lookup in dispatcher methods (per emit_backend.h:118-120
    // design intent). All non-Root variants arena-copy parent so the
    // resulting rho_t is self-contained; ρ chains live as long as the
    // ParseArena, which is the right scope (ρ is throwaway after
    // compile_grammar but the arena is per-CompiledGrammar anyway).
    //
    // ρ frames are POD-copied from `parent_val` into a fresh arena slot
    // via placement-new; arena_->alloc<rho_t>() returns aligned storage.
    ::bbq::rho_t* arena_rho(::bbq::rho_t parent_val) {
        auto* p = arena_->alloc<::bbq::rho_t>();
        *p = parent_val;
        return p;
    }

    ::bbq::rho_t root() {
        return ::bbq::rho_t{::bbq::RhoTag::Root, nullptr, nullptr, nullptr};
    }
    ::bbq::rho_t in_field(const std::string& name, ::bbq::rho_t parent_val) {
        const char* n = name.empty() ? nullptr : strings_->intern(name);
        return ::bbq::rho_t{::bbq::RhoTag::InField, n,
                            nullptr, arena_rho(parent_val)};
    }
    ::bbq::rho_t in_alt(bbq::cek::StaticKont* next_arm, ::bbq::rho_t parent_val) {
        return ::bbq::rho_t{::bbq::RhoTag::InAlt, nullptr,
                            next_arm, arena_rho(parent_val)};
    }
    ::bbq::rho_t in_optional(bbq::cek::StaticKont* skip, ::bbq::rho_t parent_val) {
        return ::bbq::rho_t{::bbq::RhoTag::InOptional, nullptr,
                            skip, arena_rho(parent_val)};
    }
    ::bbq::rho_t in_array_elem(bbq::cek::StaticKont* skip,
                               ::bbq::rho_t parent_val) {
        return ::bbq::rho_t{::bbq::RhoTag::InArrayElem, nullptr,
                            skip, arena_rho(parent_val)};
    }

    // ── make_X allocators ─────────────────────────────────────

    bbq::cek::StaticKont* make_match_primitive(bbq::cek::PrimitiveInfo p, bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::MatchPrimitiveNode>();
        k->prim = p; k->next = nx;
        return k;
    }
    // Concrete store konts: each consumes the producer's value in ac and does its
    // one thing. Capture → record an output-tree node; StoreEnv → bind in E; Drop
    // → discard. The name (the WHERE) lives on the store, not the producer.
    bbq::cek::StaticKont* make_capture(const std::string& nm, bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::CaptureKont>();
        k->name = nm.empty() ? nullptr : strings_->intern(nm); k->next = nx;
        return k;
    }
    bbq::cek::StaticKont* make_store_env(const std::string& nm, bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::StoreEnvKont>();
        k->name = nm.empty() ? nullptr : strings_->intern(nm); k->next = nx;
        return k;
    }
    // A field's name picks its placement. Any real name Captures into the output
    // tree AND binds in E. `_` skips Capture — never in the output struct — but
    // StoreEnv stays (under the name `_`), because a `_` field's own `where` (and
    // a `_` length sizing a later array) read the value back through E; a
    // separator is `_` for arrays, so the same path verifies a delimiter. "Don't
    // store in the struct" = skip Capture; the binding is internal plumbing kept
    // for verification. (There is no pure-discard placement: every "don't store"
    // case still wants the binding.)
    bbq::cek::StaticKont* field_dest(const std::string& nm, bbq::cek::StaticKont* tail) {
        if (nm == "_") return make_store_env(nm, tail);
        return make_capture(nm, make_store_env(nm, tail));
    }
    bbq::cek::StaticKont* make_begin_struct(const std::string& nm, bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::BeginStructNode>();
        k->struct_name = strings_->intern(nm); k->next = nx;
        return k;
    }
    bbq::cek::StaticKont* make_begin_variant(const std::string& nm, int tag,
                                             bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::BeginVariantNode>();
        k->variant_name = strings_->intern(nm); k->variant_tag = tag; k->next = nx;
        return k;
    }
    bbq::cek::StaticKont* make_end_struct(bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::EndStructNode>();
        k->next = nx;
        return k;
    }
    bbq::cek::StaticKont* make_seek(bbq::cek::StaticKont* expr, bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::SeekKont>();
        k->expr = expr; k->next = nx; return k;
    }
    bbq::cek::StaticKont* make_push_interval(bool relative, bbq::cek::StaticKont* expr,
                                             bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::PushIntervalNode>();
        k->relative = relative; k->expr = expr; k->next = nx; return k;
    }
    bbq::cek::StaticKont* make_pop_interval(bool checked, bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::PopIntervalNode>();
        k->checked = checked; k->next = nx; return k;
    }

    // Wrap a body (already chained into a PopInterval) with the interval entry
    // sequence. StartEnd: eval(start) -> Seek -> eval(end) -> PushInterval(abs) -> body.
    // Length: eval(len) -> PushInterval(rel = pos+len) -> body (no seek). The start/end
    // expressions deliver to the accumulator (ac) that Seek/PushInterval consume.
    bbq::cek::StaticKont* interval_entry(BBQ::Interval* iv, ::bbq::rho_t r,
                                         bbq::cek::StaticKont* body) {
        if (auto* se = dynamic_cast<BBQ::StartEnd*>(iv)) {
            // Seek(start) -> PushInterval(abs end) -> body. Each kont carries its
            // offset expression and triggers it (gamma is a placeholder — the apply
            // consumer is pushed below the expr, so the expr's own continuation is
            // never taken).
            auto* end_e = compile_expr(se->end, r, ::bbq::ac(), ::bbq::jump(body), body);
            auto* push = make_push_interval(false, end_e, body);
            auto* start_e = compile_expr(se->start, r, ::bbq::ac(), ::bbq::jump(push), push);
            return make_seek(start_e, push);
        }
        if (auto* len = dynamic_cast<BBQ::Length*>(iv)) {
            auto* len_e = compile_expr(len->length, r, ::bbq::ac(), ::bbq::jump(body), body);
            return make_push_interval(true, len_e, body);
        }
        return body;
    }

    BBQ::Interval* interval_of(BBQ::TypeExpr* node) {
        if (auto* p  = dynamic_cast<BBQ::Primitive*>(node))
            return p->interval.has_value() ? p->interval.value() : nullptr;
        if (auto* rr = dynamic_cast<BBQ::RuleRef*>(node))
            return rr->interval.has_value() ? rr->interval.value() : nullptr;
        if (auto* a  = dynamic_cast<BBQ::Array*>(node))
            return a->interval.has_value() ? a->interval.value() : nullptr;
        if (auto* e  = dynamic_cast<BBQ::Extern*>(node))
            return e->interval.has_value() ? e->interval.value() : nullptr;
        return nullptr;
    }
    bbq::cek::StaticKont* make_eval_constraint(bbq::cek::StaticKont* e,
                                               bbq::cek::StaticKont* on_false,
                                               bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::EvalConstraintNode>();
        k->constraint_expr = e; k->on_false = on_false; k->next = nx;
        return k;
    }
    bbq::cek::StaticKont* make_bind_compute(bbq::cek::StaticKont* e, bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::BindComputeNode>();
        k->compute_expr = e; k->next = nx;
        return k;
    }
    bbq::cek::StaticKont* make_invoke_rule(const std::string& nm,
                                           bbq::cek::StaticKont* caller_fail_target,
                                           bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::InvokeRuleNode>();
        k->rule_name = strings_->intern(nm);
        k->entry = nullptr;
        k->caller_fail_target = caller_fail_target;
        k->next = nx;
        pending_patches_.emplace_back(&k->entry, nm);
        return k;
    }
    bbq::cek::StaticKont* make_on_fail(bbq::cek::StaticKont* target,
                                       bbq::cek::StaticKont* next_on_fail,
                                       bool pop_frame) {
        auto* k = arena_->alloc<bbq::cek::OnFailKont>();
        k->target = target;
        k->next_on_fail = next_on_fail;
        k->pop_frame = pop_frame;
        return k;
    }
    bbq::cek::StaticKont* make_abort_rule() {
        return arena_->alloc<bbq::cek::AbortRuleKont>();
    }
    bbq::cek::StaticKont* make_return_rule(bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::ReturnRuleNode>();
        k->next = nx;
        return k;
    }
    bbq::cek::StaticKont* make_begin_choice(bbq::cek::StaticKont* on_fail_target,
                                            bbq::cek::StaticKont* first) {
        auto* k = arena_->alloc<bbq::cek::BeginChoiceNode>();
        k->on_fail_target = on_fail_target;
        k->next = first;
        return k;
    }
    bbq::cek::StaticKont* make_commit_choice(bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::CommitChoiceNode>();
        k->next = nx;
        return k;
    }
    bbq::cek::StaticKont* make_begin_optional(bbq::cek::StaticKont* on_fail_target,
                                              bbq::cek::StaticKont* inner,
                                              bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::BeginOptionalNode>();
        k->on_fail_target = on_fail_target;
        k->inner = inner;
        k->next = nx;
        return k;
    }
    bbq::cek::StaticKont* make_end_optional(bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::EndOptionalNode>();
        k->next = nx;
        return k;
    }
    bbq::cek::StaticKont*
    compile_optional(BBQ::TypeExpr* e, std::optional<BBQ::Expr*> constraint,
                     ::bbq::rho_t r, bbq::cek::StaticKont* Lnext) {
        if (constraint.has_value() && constraint.value()) {
            // Predicated: `if (cond) parse element else absent`. No Savepoint —
            // the predicate decides presence, so a present element that fails is
            // a hard failure, propagating to the enclosing backtrack frame via r
            // (hence the element parses under r, not in_optional), exactly like
            // the static backends' `if (cond) { read } else { nullopt }`.
            // EvalConstraint is the boolean branch: false routes to Lnext (absent).
            auto* inner = compile_type_expr(e, r, ::bbq::effect(),
                                            ::bbq::jump(Lnext), Lnext);
            auto* cond = compile_expr(constraint.value(), r, ::bbq::ac(),
                                      ::bbq::jump(Lnext), Lnext);
            return make_eval_constraint(cond, Lnext, inner);
        }
        // Try/restore: the skip link restores the Savepoint, pops it (no
        // retries), and continues past the optional with the element absent.
        auto* end = make_end_optional(Lnext);
        auto* skip = make_on_fail(Lnext, nullptr, /*pop_frame=*/true);
        auto* inner = compile_type_expr(e, in_optional(skip, r),
                                        ::bbq::effect(), ::bbq::jump(end), end);
        return make_begin_optional(skip, inner, Lnext);
    }
    bbq::cek::StaticKont* make_begin_array(const std::string& nm, bbq::cek::ArrayMode mode,
                                         bbq::cek::StaticKont* count_expr,
                                         bbq::cek::StaticKont* until_expr,
                                         bbq::cek::StaticKont* end_node,
                                         bbq::cek::StaticKont* resync_target,
                                         bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::BeginArrayNode>();
        k->array_name = strings_->intern(nm); k->mode = mode;
        k->count_expr = count_expr; k->until_expr = until_expr; k->end_node = end_node;
        k->resync_target = resync_target; k->next = nx;
        return k;
    }
    bbq::cek::StaticKont* make_array_next(bbq::cek::ArrayMode mode,
                                        bbq::cek::StaticKont* count_expr,
                                        bbq::cek::StaticKont* until_expr,
                                        bbq::cek::StaticKont* end_node,
                                        bbq::cek::StaticKont* body_entry,
                                        bool resync) {
        auto* k = arena_->alloc<bbq::cek::ArrayNextNode>();
        k->mode = mode;
        k->count_expr = count_expr; k->until_expr = until_expr;
        k->end_node = end_node; k->body_entry = body_entry;
        k->resync = resync;
        return k;
    }
    bbq::cek::StaticKont* make_end_array(bool resync, bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::EndArrayNode>();
        k->resync = resync;
        k->next = nx;
        return k;
    }
    bbq::cek::StaticKont* make_resync(bbq::cek::StaticKont* body_entry,
                                      bbq::cek::StaticKont* end_node) {
        auto* k = arena_->alloc<bbq::cek::ResyncKont>();
        k->body_entry = body_entry;
        k->end_node = end_node;
        return k;
    }
    bbq::cek::StaticKont* make_switch_dispatch(bbq::cek::StaticKont* disc,
                                             std::vector<bbq::cek::switch_case> cases,
                                             bbq::cek::StaticKont* dflt,
                                             bool default_reject) {
        auto* k = arena_->alloc<bbq::cek::SwitchDispatchNode>();
        k->discriminator_expr = disc;
        k->default_reject = default_reject;
        if (!cases.empty()) {
            auto* buf = static_cast<bbq::cek::switch_case*>(
                arena_->allocate(cases.size() * sizeof(bbq::cek::switch_case),
                                 alignof(bbq::cek::switch_case)));
            for (size_t i = 0; i < cases.size(); ++i) buf[i] = cases[i];
            k->cases = buf;
            k->cases_count = static_cast<int>(cases.size());
        }
        k->default_target = dflt;
        return k;
    }
    bbq::cek::StaticKont* make_extract_bits(bbq::cek::PrimitiveInfo container,
                                            int width_bits, int offset_before,
                                            bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::ExtractBitsNode>();
        k->container = container;
        k->width_bits = width_bits;
        k->offset_before = offset_before;
        k->next = nx;
        return k;
    }
    bbq::cek::StaticKont* make_advance_pos(int by, bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::AdvancePosNode>();
        k->by = by; k->next = nx;
        return k;
    }
    // A bitfield = one ExtractBits → Capture → StoreEnv per member, sharing the
    // container interval, then one AdvancePos past the container. The members
    // flatten into the enclosing scope (no Bitfield wrapper); pos stays at the
    // container start while each member reads it in place, then advances once.
    bbq::cek::StaticKont*
    compile_bitfield(bbq::cek::PrimitiveInfo container,
                     std::vector<BBQ::BitfieldEntry*> entries,
                     ::bbq::rho_t r,
                     bbq::cek::StaticKont* Lnext) {
        bbq::cek::StaticKont* chain = make_advance_pos(
            static_cast<int>(container.byte_count()), Lnext);
        // offset_before(e_i) = sum of widths of e_0..e_{i-1} (declaration order).
        std::vector<int> offset_before(entries.size(), 0);
        int cum = 0;
        for (size_t i = 0; i < entries.size(); ++i) {
            offset_before[i] = cum;
            cum += static_cast<int>(entries[i]->width);
        }
        // Build in reverse so each member's `next` chains to the rest. A member's
        // `where` runs after its StoreEnv (value bound under the member name), so
        // it can check itself or an earlier member; on failure it backtracks via
        // the bitfield field's ρ-resolved target.
        for (size_t i = entries.size(); i-- > 0; ) {
            const std::string& nm = entries[i]->name;
            bbq::cek::StaticKont* tail = chain;
            if (entries[i]->constraint.has_value() && entries[i]->constraint.value()) {
                auto* expr_ir = compile_expr(entries[i]->constraint.value(), r,
                                             ::bbq::ac(), ::bbq::jump(chain), chain);
                bbq::cek::StaticKont* on_false = find_backtrack_target(r);
                if (!on_false) on_false = make_abort_rule();
                tail = make_eval_constraint(expr_ir, on_false, chain);
            }
            chain = make_extract_bits(container, static_cast<int>(entries[i]->width),
                                      offset_before[i],
                                      field_dest(nm, tail));
        }
        return chain;
    }
    bbq::cek::StaticKont* make_set_endian(bbq::cek::StaticKont* e, bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::SetEndianNode>();
        k->endian_expr = e; k->next = nx;
        return k;
    }
    bbq::cek::StaticKont* make_external_call(const std::string& fn, const std::string& wf,
                                             bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::ExternalCallNode>();
        k->func_name = strings_->intern(fn);
        k->write_func = wf.empty() ? nullptr : strings_->intern(wf);
        k->next = nx;
        return k;
    }
    bbq::cek::StaticKont* make_match_bytes(bbq::cek::StaticKont* len, bool is_str, bbq::cek::StaticKont* nx) {
        auto* k = arena_->alloc<bbq::cek::MatchBytesNode>();
        k->length_expr = len;
        k->is_string = is_str;
        k->next = nx;
        return k;
    }
    bbq::cek::StaticKont* make_halt() {
        return arena_->alloc<bbq::cek::HaltNode>();
    }

    // Expression leaves
    bbq::cek::StaticKont* make_int_lit(int64_t v) {
        auto* k = arena_->alloc<bbq::cek::IntLitKont>();
        k->v = v; return k;
    }
    bbq::cek::StaticKont* make_bool_lit(bool v) {
        auto* k = arena_->alloc<bbq::cek::BoolLitKont>();
        k->v = v; return k;
    }
    bbq::cek::StaticKont* make_float_lit(double v) {
        auto* k = arena_->alloc<bbq::cek::FloatLitKont>();
        k->v = v; return k;
    }
    bbq::cek::StaticKont* make_str_lit(const std::string& v) {
        auto* k = arena_->alloc<bbq::cek::StrLitKont>();
        k->v = strings_->intern(v); return k;
    }
    bbq::cek::StaticKont* make_ref(const std::string& nm) {
        auto* k = arena_->alloc<bbq::cek::RefKont>();
        k->name = strings_->intern(nm); return k;
    }
    bbq::cek::StaticKont* make_pos()       { return arena_->alloc<bbq::cek::PosKont>(); }
    bbq::cek::StaticKont* make_remaining() { return arena_->alloc<bbq::cek::RemainingKont>(); }
    bbq::cek::StaticKont* make_buffer()    { return arena_->alloc<bbq::cek::BufferKont>(); }
    bbq::cek::StaticKont* make_start()     { return arena_->alloc<bbq::cek::StartKont>(); }
    bbq::cek::StaticKont* make_end()       { return arena_->alloc<bbq::cek::EndKont>(); }

    // @name context builtin → leaf kont (the `@` sigil is stripped by the parser).
    bbq::cek::StaticKont* make_builtin(const std::string& n) {
        if (n == "pos")       return make_pos();
        if (n == "start")     return make_start();
        if (n == "end")       return make_end();
        if (n == "remaining") return make_remaining();
        if (n == "index")     return make_loop_var();
        if (n == "buffer")    return make_buffer();
        // Sema rejects unknown @names before compile; defensive fallback.
        return make_pos();
    }
    bbq::cek::StaticKont* make_eoi()       { return arena_->alloc<bbq::cek::EOIKont>(); }
    bbq::cek::StaticKont* make_loop_var()  { return arena_->alloc<bbq::cek::LoopVarKont>(); }

    // Unary
    bbq::cek::StaticKont* make_neg(bbq::cek::StaticKont* e) {
        auto* k = arena_->alloc<bbq::cek::NegKont>(); k->operand = e; return k;
    }
    bbq::cek::StaticKont* make_bit_not(bbq::cek::StaticKont* e) {
        auto* k = arena_->alloc<bbq::cek::BitNotKont>(); k->operand = e; return k;
    }
    bbq::cek::StaticKont* make_not(bbq::cek::StaticKont* e) {
        auto* k = arena_->alloc<bbq::cek::NotKont>(); k->operand = e; return k;
    }

    // Binop allocators (one per op kont).
#define BBQ_DDCG_BINOP_MAKE(name, KontType)                                         \
    bbq::cek::StaticKont* name(bbq::cek::StaticKont* l, bbq::cek::StaticKont* r) {        \
        auto* k = arena_->alloc<bbq::cek::KontType>();                              \
        k->left = l; k->right = r;                                                  \
        return k;                                                                   \
    }
    BBQ_DDCG_BINOP_MAKE(make_add,        AddKont)
    BBQ_DDCG_BINOP_MAKE(make_sub,        SubKont)
    BBQ_DDCG_BINOP_MAKE(make_mul,        MulKont)
    BBQ_DDCG_BINOP_MAKE(make_div,        DivKont)
    BBQ_DDCG_BINOP_MAKE(make_mod,        ModKont)
    BBQ_DDCG_BINOP_MAKE(make_bit_and,    BitAndKont)
    BBQ_DDCG_BINOP_MAKE(make_bit_or,     BitOrKont)
    BBQ_DDCG_BINOP_MAKE(make_bit_xor,    BitXorKont)
    BBQ_DDCG_BINOP_MAKE(make_shl,        ShlKont)
    BBQ_DDCG_BINOP_MAKE(make_shr,        ShrKont)
    BBQ_DDCG_BINOP_MAKE(make_eq,         EqKont)
    BBQ_DDCG_BINOP_MAKE(make_ne,         NeKont)
    BBQ_DDCG_BINOP_MAKE(make_lt,         LtKont)
    BBQ_DDCG_BINOP_MAKE(make_le,         LeKont)
    BBQ_DDCG_BINOP_MAKE(make_gt,         GtKont)
    BBQ_DDCG_BINOP_MAKE(make_ge,         GeKont)
    BBQ_DDCG_BINOP_MAKE(make_logical_and, LogicalAndKont)
    BBQ_DDCG_BINOP_MAKE(make_logical_or,  LogicalOrKont)
#undef BBQ_DDCG_BINOP_MAKE

    bbq::cek::StaticKont* make_ternary(bbq::cek::StaticKont* c, bbq::cek::StaticKont* t, bbq::cek::StaticKont* el) {
        auto* k = arena_->alloc<bbq::cek::TernaryKont>();
        k->cond = c; k->then_ = t; k->else_ = el;
        return k;
    }

    bbq::cek::StaticKont* make_call(const std::string& name, std::vector<bbq::cek::StaticKont*> args) {
        auto* k = arena_->alloc<bbq::cek::CallKont>();
        k->func_name = strings_->intern(name);
        if (!args.empty()) {
            auto** buf = static_cast<bbq::cek::KontNode**>(
                arena_->allocate(args.size() * sizeof(bbq::cek::KontNode*),
                                 alignof(bbq::cek::KontNode*)));
            for (size_t i = 0; i < args.size(); ++i) buf[i] = args[i];
            k->args = buf;
            k->args_count = static_cast<int>(args.size());
        }
        return k;
    }

    bbq::cek::StaticKont* make_path_start(const std::string& nm) {
        auto* k = arena_->alloc<bbq::cek::PathStartKont>();
        k->name = strings_->intern(nm); return k;
    }
    bbq::cek::StaticKont* make_field_access(const std::string& fld, bbq::cek::StaticKont* base) {
        auto* k = arena_->alloc<bbq::cek::FieldAccessKont>();
        k->field = strings_->intern(fld); k->base = base; return k;
    }
    bbq::cek::StaticKont* make_index_access(bbq::cek::StaticKont* idx, bbq::cek::StaticKont* base) {
        auto* k = arena_->alloc<bbq::cek::IndexAccessKont>();
        k->index_expr = idx; k->base = base; return k;
    }
    bbq::cek::StaticKont* make_capture_value(bbq::cek::StaticKont* path) {
        auto* k = arena_->alloc<bbq::cek::CaptureValueKont>();
        k->path = path; return k;
    }

    // ── Panic ─────────────────────────────────────────────────

    [[noreturn]] bbq::cek::StaticKont* panic_unreachable() {
        std::fprintf(stderr, "bbq.ddcg: paper-undefined gamma context (driver bug)\n");
        std::abort();
    }

    // ── Helpers ───────────────────────────────────────────────

    bbq::cek::PrimitiveInfo to_prim_info(BBQ::PrimitiveKind* kind) {
        bbq::cek::PrimitiveInfo p{};
        if (auto* ik = dynamic_cast<BBQ::IntegerKind*>(kind)) {
            p.kind = bbq::cek::PrimKind::Integer;
            switch (ik->width) {
                case BBQ::Width::W8:  p.width = bbq::cek::PrimWidth::W8;  break;
                case BBQ::Width::W16: p.width = bbq::cek::PrimWidth::W16; break;
                case BBQ::Width::W32: p.width = bbq::cek::PrimWidth::W32; break;
                case BBQ::Width::W64: p.width = bbq::cek::PrimWidth::W64; break;
            }
            p.sign = (ik->sign == BBQ::Signedness::Signed)
                ? bbq::cek::PrimSign::Signed : bbq::cek::PrimSign::Unsigned;
            switch (ik->endian) {
                case BBQ::Endianness::Little:  p.endian = bbq::cek::PrimEndian::Little; break;
                case BBQ::Endianness::Big:     p.endian = bbq::cek::PrimEndian::Big; break;
                case BBQ::Endianness::Default: p.endian = bbq::cek::PrimEndian::Native; break;
            }
            switch (ik->encoding) {
                case BBQ::Encoding::Fixed: p.encoding = bbq::cek::PrimEncoding::Fixed; break;
                case BBQ::Encoding::Uleb:  p.encoding = bbq::cek::PrimEncoding::Uleb;  break;
                case BBQ::Encoding::Sleb:  p.encoding = bbq::cek::PrimEncoding::Sleb;  break;
            }
        } else if (auto* fk = dynamic_cast<BBQ::FloatKind*>(kind)) {
            p.kind = bbq::cek::PrimKind::Float;
            p.width = (fk->width == BBQ::Width::W32) ? bbq::cek::PrimWidth::W32 : bbq::cek::PrimWidth::W64;
            switch (fk->endian) {
                case BBQ::Endianness::Little:  p.endian = bbq::cek::PrimEndian::Little; break;
                case BBQ::Endianness::Big:     p.endian = bbq::cek::PrimEndian::Big; break;
                case BBQ::Endianness::Default: p.endian = bbq::cek::PrimEndian::Native; break;
            }
        } else if (dynamic_cast<BBQ::BoolKind*>(kind)) {
            p.kind = bbq::cek::PrimKind::Bool;
            p.width = bbq::cek::PrimWidth::W8;
        }
        return p;
    }

    bool endian_to_bool(BBQ::Endianness e) {
        return e == BBQ::Endianness::Little;
    }

    bbq::cek::StaticKont*
    compile_array(BBQ::TypeExpr* element,
                  BBQ::ArraySpec* spec,
                  BBQ::Interval* element_interval,
                  bool resync,
                  ::bbq::rho_t r,
                  bbq::cek::StaticKont* Lnext) {
        // Determine mode + count/until exprs from the AST spec.
        bbq::cek::ArrayMode mode = bbq::cek::ArrayMode::EOF_;
        bbq::cek::StaticKont* count_expr = nullptr;
        bbq::cek::StaticKont* until_expr = nullptr;

        if (auto* fc = dynamic_cast<BBQ::FixedCount*>(spec)) {
            mode = bbq::cek::ArrayMode::FixedCount;
            count_expr = compile_expr(fc->count, r, ::bbq::ac(),
                                      ::bbq::jump(Lnext), Lnext);
        } else if (auto* st = dynamic_cast<BBQ::SepTerm*>(spec)) {
            if (dynamic_cast<BBQ::EofTerm*>(st->term)) {
                mode = bbq::cek::ArrayMode::EOF_;
            } else if (auto* count_term = dynamic_cast<BBQ::CountTerm*>(st->term)) {
                mode = bbq::cek::ArrayMode::Count;
                count_expr = compile_expr(count_term->count, r, ::bbq::ac(),
                                          ::bbq::jump(Lnext), Lnext);
            } else if (auto* until_term = dynamic_cast<BBQ::UntilTerm*>(st->term)) {
                mode = bbq::cek::ArrayMode::Until;
                until_expr = compile_expr(until_term->condition, r, ::bbq::ac(),
                                          ::bbq::jump(Lnext), Lnext);
            }
        }

        // EndArray pops the LoopFrame (and the resync Savepoint, if
        // any) and chains into Lnext.
        bbq::cek::StaticKont* end_kont = make_end_array(resync, Lnext);

        // Allocate ArrayNext with body_entry=null; patch after body
        // compilation to break the cycle. ArrayNext refreshes the
        // resync savepoint (if any) per iteration.
        auto* array_next = arena_->alloc<bbq::cek::ArrayNextNode>();
        array_next->mode = mode;
        array_next->count_expr = count_expr;
        array_next->until_expr = until_expr;
        array_next->end_node = end_kont;
        array_next->body_entry = nullptr;
        array_next->resync = resync;

        // resync_target — allocated up front when in resync mode so
        // both the runtime Savepoint and the compile-time
        // in_array_elem.skip can carry the same ResyncKont.
        // body_entry is patched after element compile (cycle break,
        // same pattern as ArrayNext.body_entry).
        bbq::cek::ResyncKont* resync_kont = nullptr;
        if (resync) {
            resync_kont = arena_->alloc<bbq::cek::ResyncKont>();
            resync_kont->body_entry = nullptr;
            resync_kont->end_node = end_kont;
        }

        // Compile element body with ρ pushed for the array element
        // scope. in_array_elem is a name barrier (elements are
        // anonymous), and in resync mode it carries the ResyncKont
        // so where-checks inside the element body dispatch to it via
        // on_false — the same target the runtime Savepoint uses.
        std::string array_name = intern_field_or_anon(r);
        ::bbq::rho_t elem_rho = in_array_elem(resync_kont, r);
        bbq::cek::StaticKont* body_head;
        if (element_interval) {
            // Per-element `@[start,end]` random access (e.g. elf64's section
            // headers at e_shoff + i*entsize). The interval references @index, which
            // is live inside the loop body, so seek+bound is re-evaluated each
            // iteration. The body chains to a Pop, which then advances the loop.
            auto* pop = make_pop_interval(false, array_next);
            auto* elem_body = compile_type_expr(
                element, elem_rho, ::bbq::effect(), ::bbq::jump(pop), pop);
            body_head = interval_entry(element_interval, elem_rho, elem_body);
        } else {
            body_head = compile_type_expr(
                element, elem_rho, ::bbq::effect(),
                ::bbq::jump(array_next), array_next);
        }
        // Separator (a PEG/CSV bolt-on, not in IPG — IPG arrays are counted
        // `for` loops): parsed between elements and treated as `_` for arrays —
        // compiled under the name `_`, so it binds in E (a `uint8 where _ == 0x2C`
        // delimiter check resolves `_`) but skips Capture, never landing in the
        // array. It precedes every element after the first, so it lives on the
        // loop-back entry (array_next/resync), never on begin_array's first element.
        bbq::cek::StaticKont* loop_entry = body_head;
        if (auto* st = dynamic_cast<BBQ::SepTerm*>(spec)) {
            if (auto* ts = dynamic_cast<BBQ::TypeSep*>(st->sep)) {
                loop_entry = compile_type_expr(ts->sep_type,
                                               in_field("_", elem_rho),
                                               ::bbq::effect(),
                                               ::bbq::jump(body_head), body_head);
            }
        }
        array_next->body_entry = loop_entry;
        if (resync_kont) resync_kont->body_entry = loop_entry;

        return make_begin_array(array_name, mode,
                                count_expr, until_expr, end_kont,
                                resync_kont, body_head);
    }

    // One choice arm: a BeginVariant(name, tag) scope wrapping the variant body,
    // closed by EndStruct → success_cont. Both union variants and (A|B)
    // alternatives are tagged unions in the output (`tag` + `u.<name>`), so both
    // route through here — only the names differ (variant names vs alt_0/alt_1).
    // A RuleRef body becomes a bare InvokeRule capturing into the variant scope
    // (the sub-rule owns its where-checks and fails softly); any other body is
    // compiled so its captures land directly in the scope (no extra wrapper).
    bbq::cek::StaticKont*
    build_variant_arm(const std::string& name, BBQ::TypeExpr* body, int tag,
                      ::bbq::rho_t arm_rho, bbq::cek::StaticKont* success_cont) {
        bbq::cek::StaticKont* end_st = make_end_struct(success_cont);
        bbq::cek::StaticKont* inner;
        if (auto* rr = dynamic_cast<BBQ::RuleRef*>(body)) {
            inner = make_invoke_rule(rr->name, find_backtrack_target(arm_rho), end_st);
        } else {
            inner = compile_type_expr(body, arm_rho, ::bbq::effect(),
                                      ::bbq::jump(end_st), end_st);
        }
        return make_begin_variant(name, tag, inner);
    }

    // Build the backtracking choice spine over named arms (the shared core of
    // unions and alternatives). Each non-last arm's success threads through
    // CommitChoice (pops the Savepoint, chains to Lnext); the last arm chains
    // to Lnext directly — the "exhausted" OnFailKont pops the Savepoint and
    // fails if it too fails. Arms compile right-to-left so each OnFailKont link
    // knows the next arm's entry; the same link is both the runtime
    // Savepoint.on_fail_target (byte-fails) and the static in_alt.next_arm
    // (where-fails via on_false).
    bbq::cek::StaticKont*
    compile_choice(std::vector<std::string> names,
                   std::vector<BBQ::TypeExpr*> bodies,
                   ::bbq::rho_t r, bbq::cek::StaticKont* Lnext) {
        if (bodies.empty()) return Lnext;
        if (bodies.size() == 1) {
            // Single arm — still a tagged union (tag 0, u.<name>), no backtracking.
            return build_variant_arm(names[0], bodies[0], 0, r, Lnext);
        }
        auto* commit = make_commit_choice(Lnext);
        bbq::cek::StaticKont* exhausted =
            make_on_fail(nullptr, nullptr, /*pop_frame=*/true);
        int last = static_cast<int>(bodies.size()) - 1;
        bbq::cek::StaticKont* last_entry =
            build_variant_arm(names[last], bodies[last], last, r, Lnext);
        bbq::cek::StaticKont* next_link = exhausted;
        bbq::cek::StaticKont* next_target = last_entry;
        for (int i = last - 1; i >= 1; --i) {
            bbq::cek::StaticKont* link =
                make_on_fail(next_target, next_link, /*pop_frame=*/false);
            ::bbq::rho_t arm_rho = in_alt(link, r);
            bbq::cek::StaticKont* arm =
                build_variant_arm(names[i], bodies[i], i, arm_rho, commit);
            next_link = link;
            next_target = arm;
        }
        bbq::cek::StaticKont* head_link =
            make_on_fail(next_target, next_link, /*pop_frame=*/false);
        ::bbq::rho_t arm0_rho = in_alt(head_link, r);
        bbq::cek::StaticKont* first =
            build_variant_arm(names[0], bodies[0], 0, arm0_rho, commit);
        return make_begin_choice(head_link, first);
    }

    bbq::cek::StaticKont*
    compile_alternatives(std::vector<BBQ::TypeExpr*> alts,
                         ::bbq::rho_t r,
                         bbq::cek::StaticKont* Lnext) {
        // `(A | B)` alternatives are an anonymous tagged union: positional
        // variant names alt_0, alt_1, ... (matching the C type layout).
        std::vector<std::string> names;
        names.reserve(alts.size());
        for (size_t i = 0; i < alts.size(); ++i)
            names.push_back("alt_" + std::to_string(i));
        return compile_choice(names, alts, r, Lnext);
    }

    bbq::cek::StaticKont*
    compile_union(std::vector<BBQ::Variant*> variants,
                  ::bbq::rho_t r,
                  bbq::cek::StaticKont* Lnext) {
        std::vector<std::string> names;
        std::vector<BBQ::TypeExpr*> bodies;
        names.reserve(variants.size());
        bodies.reserve(variants.size());
        for (auto* v : variants) { names.push_back(v->name); bodies.push_back(v->body); }
        return compile_choice(names, bodies, r, Lnext);
    }

    bbq::cek::StaticKont*
    compile_primitive(BBQ::PrimitiveKind* kind,
                      std::optional<BBQ::Expr*> constraint,
                      std::optional<BBQ::Interval*> interval,
                      ::bbq::rho_t r,
                      bbq::cek::StaticKont* Lnext) {
        // Emit the constraint check first (it's the LAST thing to run
        // after the primitive read), wrapped around Lnext.
        bbq::cek::StaticKont* tail = Lnext;
        if (constraint.has_value() && constraint.value()) {
            auto* expr_ir = compile_expr(constraint.value(), r,
                                         ::bbq::ac(), ::bbq::jump(Lnext), Lnext);
            // on_false is the static failure target for this where-
            // check, resolved from ρ at compile time. find_backtrack_
            // target walks ρ to the innermost in_alt / in_optional /
            // in_array_elem(skip!=null) and returns that scope's
            // failure handler. If ρ bottoms out at root with no
            // backtrackable frame in scope, AbortRuleKont takes over
            // and crosses the rule boundary into the caller's chain.
            bbq::cek::StaticKont* on_false = find_backtrack_target(r);
            if (!on_false) on_false = make_abort_rule();
            tail = make_eval_constraint(expr_ir, on_false, Lnext);
        }

        // Bytes/String → MatchBytes with the interval-derived length.
        if (dynamic_cast<BBQ::BytesKind*>(kind) != nullptr ||
            dynamic_cast<BBQ::StringKind*>(kind) != nullptr) {
            bool is_string = (dynamic_cast<BBQ::StringKind*>(kind) != nullptr);
            // Interval must be Length(expr) for bytes/string with
            // variable length.
            bbq::cek::StaticKont* length_expr = nullptr;
            if (interval.has_value()) {
                if (auto* len = dynamic_cast<BBQ::Length*>(interval.value())) {
                    length_expr = compile_expr(len->length, r,
                                               ::bbq::ac(),
                                               ::bbq::jump(tail), tail);
                }
            }
            if (length_expr == nullptr) {
                // No interval / not Length — emit a literal 0-length;
                // runtime will produce an empty bytes capture. Sema
                // catches missing-length-on-bytes earlier so this is
                // a defensive default.
                length_expr = make_int_lit(0);
            }
            std::string bnm = intern_field_or_anon(r);
            return make_match_bytes(length_expr, is_string, field_dest(bnm, tail));
        }

        // Other primitives → MatchPrimitive.
        bbq::cek::PrimitiveInfo prim = to_prim_info(kind);
        std::string nm = intern_field_or_anon(r);
        return make_match_primitive(prim, field_dest(nm, tail));
    }

    // Walk ρ to the innermost in_field, returning its name.
    // in_alt and in_optional are transparent — a where-fail inside
    // an alternative arm or optional inner still wants the enclosing
    // field's name for its capture. in_array_elem is a name barrier:
    // array elements are anonymous regardless of the enclosing array's
    // name, so the walk stops there and returns empty. Empty when no
    // in_field is in scope (rule body level, anonymous capture).
    std::string intern_field_or_anon(::bbq::rho_t r) {
        const ::bbq::rho_t* p = &r;
        while (p) {
            switch (p->tag) {
                case ::bbq::RhoTag::InField:
                    return p->name ? std::string(p->name) : std::string();
                case ::bbq::RhoTag::InArrayElem:
                case ::bbq::RhoTag::Root:
                    return std::string();
                case ::bbq::RhoTag::InAlt:
                case ::bbq::RhoTag::InOptional:
                    p = p->parent;
                    continue;
            }
        }
        return std::string();
    }

    // Walk ρ to find the static failure target for the innermost
    // backtrackable scope. Returns nullptr when ρ bottoms out at root
    // with no backtrack frame in scope — caller substitutes
    // AbortRuleKont so the failure crosses the rule boundary into the
    // caller's nearest scope (via ReturnFrame::rule_fail_target).
    //
    // in_field is transparent (a where-check inside a named field
    // still backtracks to whatever the surrounding scope provides).
    // in_array_elem is transparent unless `skip` is set — non-null
    // skip means resync mode, so element-fail goes to the resync
    // handler; null skip means the array doesn't recover from element
    // failure and the walk continues outward.
    bbq::cek::StaticKont* find_backtrack_target(::bbq::rho_t r) {
        const ::bbq::rho_t* p = &r;
        while (p) {
            switch (p->tag) {
                case ::bbq::RhoTag::Root:
                    return nullptr;
                case ::bbq::RhoTag::InAlt:
                    return p->fail_target;
                case ::bbq::RhoTag::InOptional:
                    return p->fail_target;
                case ::bbq::RhoTag::InArrayElem:
                    if (p->fail_target) return p->fail_target;
                    p = p->parent;
                    continue;
                case ::bbq::RhoTag::InField:
                    p = p->parent;
                    continue;
            }
        }
        return nullptr;
    }

    // A bare identifier is ALWAYS a field reference. Context builtins are reached
    // only via the `@` sigil (ast.Builtin -> make_builtin), so a spec field may be
    // named `pos`, `i`, `buffer`, etc. without colliding.
    bbq::cek::StaticKont* make_ref_or_builtin(const std::string& n,
                                              const std::optional<std::string>& rp,
                                              const std::optional<std::string>& rpar,
                                              int64_t rd) {
        // Carry Sema's cross-rule resolution onto the node for the static emitter
        // (scope cast). The CEK resolves by name at runtime and ignores these; a
        // same-scope reference leaves them null/0.
        auto* k = arena_->alloc<bbq::cek::RefKont>();
        k->name = strings_->intern(n);
        k->resolved_path = rp.has_value() ? strings_->intern(rp.value()) : nullptr;
        k->resolved_parent = rpar.has_value() ? strings_->intern(rpar.value()) : nullptr;
        k->resolved_depth = static_cast<int>(rd);
        return k;
    }

    // ── Helper implementations ────────────────────────
    //
    // These are MEMBER methods that the rule bodies call. They take
    // AST nodes/lists by value (matching what ddcgc passes through
    // the auto-generated dispatch) and return either an IR sub-tree
    // or a list of IR shapes. They recursively call compile_expr /
    // compile_type_expr (the auto-generated dispatch entries) which
    // ddcgc declares on this class.

    std::vector<bbq::cek::StaticKont*>
    compile_call_args(std::vector<BBQ::Expr*> args, ::bbq::rho_t r,
                      bbq::cek::StaticKont* Lnext) {
        std::vector<bbq::cek::StaticKont*> out;
        out.reserve(args.size());
        for (auto* a : args) {
            out.push_back(compile_expr(a, r, ::bbq::ac(), ::bbq::jump(Lnext), Lnext));
        }
        return out;
    }

    // Wrap `Lnext` with a struct-level `where` check, if present. The check runs
    // after all fields are parsed (after EndStruct), so it sees every field in the
    // environment — e.g. a header checksum. Mirrors compile_primitive's constraint
    // handling: failure routes to the ρ-resolved backtrack target, or AbortRule at
    // the rule boundary when no backtrackable frame is in scope.
    bbq::cek::StaticKont*
    wrap_struct_where(std::optional<BBQ::Expr*> constraint,
                      ::bbq::rho_t r, bbq::cek::StaticKont* Lnext) {
        if (!(constraint.has_value() && constraint.value()))
            return Lnext;
        auto* expr_ir = compile_expr(constraint.value(), r,
                                     ::bbq::ac(), ::bbq::jump(Lnext), Lnext);
        bbq::cek::StaticKont* on_false = find_backtrack_target(r);
        if (!on_false) on_false = make_abort_rule();
        return make_eval_constraint(expr_ir, on_false, Lnext);
    }

    bbq::cek::StaticKont*
    compile_fields(std::vector<BBQ::Field*> fields, ::bbq::rho_t r,
                   bbq::cek::StaticKont* tail) {
        // Compile fields in reverse so each field's `next` chains to
        // the already-compiled tail. Each field body sees its own ρ
        // frame in_field(name, parent=r); the parent link preserves any
        // backtrack frame visible at struct entry.
        //
        // A field marked @rest declares its value as the byte length of the
        // remainder of the struct: the fields after it parse inside a window
        // [pos, pos + value] that the struct must consume exactly. The window
        // opens (relative PushInterval, confined to the parent by
        // PushIntervalApply) right after the size field reads; the matching
        // checked PopInterval sits at struct end, so it wraps the initial tail.
        bool has_rest = false;
        for (auto* f : fields) if (f->scopes_rest) { has_rest = true; break; }
        bbq::cek::StaticKont* chain = has_rest ? make_pop_interval(true, tail) : tail;
        for (auto it = fields.rbegin(); it != fields.rend(); ++it) {
            BBQ::Field* f = *it;
            if (f->scopes_rest) {
                auto* push = make_push_interval(true, make_ref(f->name), chain);
                chain = compile_type_expr(
                    f->body, in_field(f->name, r),
                    ::bbq::effect(), ::bbq::jump(push), push);
                continue;
            }
            // The interval may be on the field (struct/union body) or on the body
            // node (Primitive/RuleRef/Array @[...]). A body-node Length on a
            // bytes/string primitive is sized by compile_primitive, so only wrap a
            // body-node interval when it's a StartEnd random access.
            BBQ::Interval* iv = nullptr;
            if (f->interval.has_value() && f->interval.value()) {
                iv = f->interval.value();
            } else if (auto* bi = interval_of(f->body)) {
                if (dynamic_cast<BBQ::StartEnd*>(bi)) iv = bi;
            }
            if (iv) {
                // seek+bound around the body, popping when the body completes.
                auto* pop = make_pop_interval(false, chain);
                auto* body = compile_type_expr(
                    f->body, in_field(f->name, r),
                    ::bbq::effect(), ::bbq::jump(pop), pop);
                chain = interval_entry(iv, r, body);
            } else {
                chain = compile_type_expr(
                    f->body, in_field(f->name, r),
                    ::bbq::effect(), ::bbq::jump(chain), chain);
            }
        }
        return chain;
    }


    bbq::cek::StaticKont*
    compile_switch_default(std::optional<BBQ::SwitchDefault*> dflt, ::bbq::rho_t r,
                           bbq::cek::StaticKont* Lnext) {
        if (!dflt.has_value() || !dflt.value()) return nullptr;
        // `default: reject` has no target — caller (compile_switch)
        // emits a fail node directly. Returning nullptr here triggers
        // that path uniformly with the no-default case.
        if (dflt.value()->is_reject || !dflt.value()->target.has_value())
            return nullptr;
        return compile_type_expr(*dflt.value()->target, r, ::bbq::effect(),
                                 ::bbq::jump(Lnext), Lnext);
    }

    bool switch_default_is_reject(std::optional<BBQ::SwitchDefault*> dflt) {
        return dflt.has_value() && dflt.value() && dflt.value()->is_reject;
    }

    std::vector<bbq::cek::switch_case>
    compile_switch_cases(std::vector<BBQ::SwitchCase*> cases, ::bbq::rho_t r,
                         bbq::cek::StaticKont* Lnext) {
        std::vector<bbq::cek::switch_case> out;
        out.reserve(cases.size());
        for (size_t ci = 0; ci < cases.size(); ci++) {
            BBQ::SwitchCase* c = cases[ci];
            bbq::cek::StaticKont* target =
                compile_type_expr(c->target, r, ::bbq::effect(),
                                  ::bbq::jump(Lnext), Lnext);
            if (auto* rv = dynamic_cast<BBQ::RangeValue*>(c->value)) {
                // An inclusive range is one variant matched by several discriminants:
                // emit one entry per value, all sharing the single compiled target
                // AND the one case ordinal (mirrors the C/C++ backends expanding a
                // range into case labels under one union arm).
                for (int64_t v = rv->lo; v <= rv->hi; v++) {
                    bbq::cek::switch_case sc{};
                    auto* mv = arena_->alloc<bbq::cek::IntValue>();
                    mv->v = v;
                    sc.match_value = mv;
                    sc.target = target;
                    sc.ordinal = static_cast<int>(ci);
                    out.push_back(sc);
                }
                continue;
            }
            bbq::cek::switch_case sc{};
            sc.match_value = case_value_to_value(c->value);
            sc.target = target;
            sc.ordinal = static_cast<int>(ci);
            out.push_back(sc);
        }
        return out;
    }

    // Convert a BBQ AST case_value variant into a typed Value.
    // Cases are int or string at the AST level; runtime SwitchSelect
    // matches by tag + interned-pointer or scalar comparison.
    bbq::cek::Value* case_value_to_value(BBQ::CaseValue* cv) {
        if (auto* iv = dynamic_cast<BBQ::IntValue*>(cv)) {
            auto* v = arena_->alloc<bbq::cek::IntValue>();
            v->v = iv->value;
            return v;
        }
        if (auto* sv = dynamic_cast<BBQ::StrValue*>(cv)) {
            auto* v = arena_->alloc<bbq::cek::StringValue>();
            v->v = strings_->intern(sv->value);
            return v;
        }
        if (auto* iv = dynamic_cast<BBQ::IdentValue*>(cv)) {
            // IdentValue's payload is `name` (identifier), not `value`.
            auto* v = arena_->alloc<bbq::cek::StringValue>();
            v->v = strings_->intern(iv->name);
            return v;
        }
        return nullptr;
    }

    // Path navigation: walk a RefPath (Simple / FieldAcc / IndexAcc)
    // outward-in, building a chain of path-nav konts. The outermost
    // call wraps with CaptureValue when then_capture is true.
    bbq::cek::StaticKont*
    compile_ref_path(BBQ::RefPath* path, const std::string& field, bool then_capture) {
        if (auto* simple = dynamic_cast<BBQ::Simple*>(path)) {
            auto* base = make_path_start(simple->name);
            auto* fa = make_field_access(field, base);
            return then_capture ? make_capture_value(fa) : fa;
        }
        if (auto* fa = dynamic_cast<BBQ::FieldAcc*>(path)) {
            auto* base = compile_ref_path(fa->base, fa->field, false);
            auto* step = make_field_access(field, base);
            return then_capture ? make_capture_value(step) : step;
        }
        if (auto* ia = dynamic_cast<BBQ::IndexAcc*>(path)) {
            // Index expressions are pure value-producers — no
            // backtrackable scope to inherit. Compile with ρ=root.
            ::bbq::rho_t r = root();
            auto* idx = compile_expr(ia->index, r, ::bbq::ac(),
                                     ::bbq::jump(nullptr), nullptr);
            auto* base = compile_ref_path(ia->base, "", false);
            auto* step = make_index_access(idx, base);
            auto* fa_step = make_field_access(field, step);
            return then_capture ? make_capture_value(fa_step) : fa_step;
        }
        return nullptr;
    }

    bbq::cek::StaticKont*
    compile_ref_index_path(BBQ::RefPath* base_path, bbq::cek::StaticKont* idx, bool then_capture) {
        auto* base = compile_ref_path(base_path, "", false);
        auto* step = make_index_access(idx, base);
        return then_capture ? make_capture_value(step) : step;
    }
    // ─── End PRIVATE ────────────────────────────
protected:
    // ─── action-language funs ───────────────────
    // Internal helpers; consumer (subclass) calls
    // these from rule bodies and other funs, not
    // from external code.

    // fun cg_jump
    bbq_ir::StaticKont* cg_jump(gamma_t g, bbq_ir::StaticKont* Lnext) {
        return ([&]() -> bbq_ir::StaticKont* {
            auto _m = g;
            switch (_m.tag) {
            case GammaTag::Jump: {
                auto L = _m.L;
                return ((L == Lnext) ? Lnext : panic_unreachable());
            }
            }
            return {};
        })();
    }

    // fun cg_deliver
    bbq_ir::StaticKont* cg_deliver(bbq_ir::StaticKont* value, delta_t d, gamma_t g, bbq_ir::StaticKont* Lnext) {
        return ([&]() -> bbq_ir::StaticKont* {
            auto _m = g;
            switch (_m.tag) {
            case GammaTag::Jump: {
                auto L = _m.L;
                return ((L == Lnext) ? value : panic_unreachable());
            }
            }
            return {};
        })();
    }
private:

    // Dispatcher for ast.expr
    bbq_ir::StaticKont* compile_expr(BBQ::Expr* node, rho_t rho, delta_t delta, gamma_t gamma, bbq_ir::StaticKont* Lnext = {}) {
        (void)delta; (void)gamma; (void)Lnext;
        (void)rho;
        current_loc = node->loc;
        if (auto* _n0 = dynamic_cast<BBQ::IntLit*>(node)) {
            auto n = _n0->value;
            return cg_deliver(make_int_lit(n), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::BoolLit*>(node)) {
            auto b = _n0->value;
            return cg_deliver(make_bool_lit(b), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::FloatLit*>(node)) {
            auto f = _n0->value;
            return cg_deliver(make_float_lit(f), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::StrLit*>(node)) {
            auto s = _n0->value;
            return cg_deliver(make_str_lit(s), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::EOI*>(node)) {
            return cg_deliver(make_eoi(), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::Builtin*>(node)) {
            auto n = _n0->name;
            return cg_deliver(make_builtin(n), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::Ref*>(node)) {
            if (auto* _n1 = dynamic_cast<BBQ::Simple*>(_n0->path)) {
                auto n = _n1->name;
                auto rp = _n1->resolved_path;
                auto rpar = _n1->resolved_parent;
                auto rd = _n1->resolved_depth;
                return cg_deliver(make_ref_or_builtin(n, rp, rpar, rd), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::Ref*>(node)) {
            if (auto* _n1 = dynamic_cast<BBQ::FieldAcc*>(_n0->path)) {
                auto b = _n1->base;
                auto f = _n1->field;
                bbq_ir::StaticKont* path_node = compile_ref_path(b, f, false);
                return cg_deliver(make_capture_value(path_node), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::Ref*>(node)) {
            if (auto* _n1 = dynamic_cast<BBQ::IndexAcc*>(_n0->path)) {
                auto b = _n1->base;
                auto i = _n1->index;
                bbq_ir::StaticKont* idx = compile_expr(i, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* path_node = compile_ref_index_path(b, idx, false);
                return cg_deliver(make_capture_value(path_node), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::Add)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_add(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::Sub)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_sub(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::Mul)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_mul(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::Div)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_div(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::Mod)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_mod(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::BitAnd)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_bit_and(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::BitOr)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_bit_or(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::BitXor)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_bit_xor(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::Shl)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_shl(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::Shr)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_shr(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::Eq)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_eq(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::Ne)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_ne(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::Lt)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_lt(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::Le)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_le(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::Gt)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_gt(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::Ge)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_ge(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::And)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_logical_and(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::BinOp*>(node)) {
            auto l = _n0->left;
            auto r = _n0->right;
            if ((_n0->op == BBQ::Binop::Or)) {
                bbq_ir::StaticKont* lv = compile_expr(l, rho, ac(), jump(Lnext), Lnext);
                bbq_ir::StaticKont* rv = compile_expr(r, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_logical_or(lv, rv), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::UnaryOp*>(node)) {
            auto e = _n0->operand;
            if ((_n0->op == BBQ::Unaryop::Neg)) {
                bbq_ir::StaticKont* ev = compile_expr(e, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_neg(ev), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::UnaryOp*>(node)) {
            auto e = _n0->operand;
            if ((_n0->op == BBQ::Unaryop::BitNot)) {
                bbq_ir::StaticKont* ev = compile_expr(e, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_bit_not(ev), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::UnaryOp*>(node)) {
            auto e = _n0->operand;
            if ((_n0->op == BBQ::Unaryop::Not)) {
                bbq_ir::StaticKont* ev = compile_expr(e, rho, ac(), jump(Lnext), Lnext);
                return cg_deliver(make_not(ev), delta, gamma, Lnext);
            }
        }
        if (auto* _n0 = dynamic_cast<BBQ::Ternary*>(node)) {
            auto c = _n0->cond;
            auto t = _n0->then_branch;
            auto el = _n0->else_branch;
            bbq_ir::StaticKont* cv = compile_expr(c, rho, ac(), jump(Lnext), Lnext);
            bbq_ir::StaticKont* tv = compile_expr(t, rho, ac(), jump(Lnext), Lnext);
            bbq_ir::StaticKont* ev = compile_expr(el, rho, ac(), jump(Lnext), Lnext);
            return cg_deliver(make_ternary(cv, tv, ev), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::EndianLit*>(node)) {
            auto v = _n0->value;
            return cg_deliver(make_bool_lit(endian_to_bool(v)), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::Call*>(node)) {
            auto f = _n0->func;
            auto as = _n0->args;
            std::vector<bbq_ir::StaticKont*> arg_irs = compile_call_args(as, rho, Lnext);
            return cg_deliver(make_call(f, arg_irs), delta, gamma, Lnext);
        }
        return {};
    }

    // Dispatcher for ast.rule
    bbq_ir::StaticKont* compile_rule(BBQ::Rule* node, rho_t rho, delta_t delta, gamma_t gamma, bbq_ir::StaticKont* Lnext = {}) {
        (void)delta; (void)gamma; (void)Lnext;
        (void)rho;
        current_loc = node->loc;
        if (auto* _n0 = dynamic_cast<BBQ::Rule*>(node)) {
            auto n = _n0->name;
            auto b = _n0->body;
            return compile_type_expr(b, rho, delta, gamma, Lnext);
        }
        return {};
    }

    // Dispatcher for ast.type_expr
    bbq_ir::StaticKont* compile_type_expr(BBQ::TypeExpr* node, rho_t rho, delta_t delta, gamma_t gamma, bbq_ir::StaticKont* Lnext = {}) {
        (void)delta; (void)gamma; (void)Lnext;
        (void)rho;
        current_loc = node->loc;
        if (auto* _n0 = dynamic_cast<BBQ::Struct*>(node)) {
            auto fs = _n0->fields;
            auto cn = _n0->constraint.has_value() ? *_n0->constraint : nullptr;
            bbq_ir::StaticKont* end_kont = make_end_struct(Lnext);
            bbq_ir::StaticKont* checked = wrap_struct_where(cn, rho, end_kont);
            bbq_ir::StaticKont* fields_chain = compile_fields(fs, rho, checked);
            return cg_deliver(make_begin_struct(intern_field_or_anon(rho), fields_chain), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::Primitive*>(node)) {
            auto k = _n0->kind;
            auto cn = _n0->constraint.has_value() ? *_n0->constraint : nullptr;
            auto iv = _n0->interval.has_value() ? *_n0->interval : nullptr;
            return cg_deliver(compile_primitive(k, cn, iv, rho, Lnext), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::RuleRef*>(node)) {
            auto n = _n0->name;
            bbq_ir::StaticKont* end_st = make_end_struct(Lnext);
            bbq_ir::StaticKont* invoke = make_invoke_rule(n, find_backtrack_target(rho), end_st);
            return cg_deliver(make_begin_struct(intern_field_or_anon(rho), invoke), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::Compute*>(node)) {
            auto e = _n0->expression;
            bbq_ir::StaticKont* expr_ir = compile_expr(e, rho, ac(), jump(Lnext), Lnext);
            return cg_deliver(make_bind_compute(expr_ir, field_dest(intern_field_or_anon(rho), Lnext)), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::Extern*>(node)) {
            auto f = _n0->func_name;
            auto w = _n0->write_func;
            return cg_deliver(make_external_call(f, w, field_dest(intern_field_or_anon(rho), Lnext)), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::EndianSwitch*>(node)) {
            auto e = _n0->endian_expr;
            bbq_ir::StaticKont* expr_ir = compile_expr(e, rho, ac(), jump(Lnext), Lnext);
            return cg_deliver(make_set_endian(expr_ir, Lnext), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::Bitfield*>(node)) {
            auto c = _n0->container;
            auto es = _n0->entries;
            auto prim = to_prim_info(c);
            bbq_ir::StaticKont* end_st = make_end_struct(Lnext);
            bbq_ir::StaticKont* inner = compile_bitfield(prim, es, rho, end_st);
            return cg_deliver(make_begin_struct(intern_field_or_anon(rho), inner), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::Optional*>(node)) {
            auto e = _n0->element;
            auto cn = _n0->constraint.has_value() ? *_n0->constraint : nullptr;
            return cg_deliver(compile_optional(e, cn, rho, Lnext), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::Switch*>(node)) {
            auto d = _n0->discriminator;
            auto cs = _n0->cases;
            auto dflt = _n0->default_.has_value() ? *_n0->default_ : nullptr;
            std::vector<bbq_ir::switch_case> cs_list = compile_switch_cases(cs, rho, Lnext);
            bbq_ir::StaticKont* disc = compile_expr(d, rho, ac(), jump(Lnext), Lnext);
            bbq_ir::StaticKont* default_target = compile_switch_default(dflt, rho, Lnext);
            bool is_reject = switch_default_is_reject(dflt);
            return cg_deliver(make_switch_dispatch(disc, cs_list, default_target, is_reject), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::Alternatives*>(node)) {
            auto a = _n0->alts;
            return cg_deliver(compile_alternatives(a, rho, Lnext), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::Union*>(node)) {
            auto vs = _n0->variants;
            return cg_deliver(compile_union(vs, rho, Lnext), delta, gamma, Lnext);
        }
        if (auto* _n0 = dynamic_cast<BBQ::Array*>(node)) {
            auto e = _n0->element;
            auto s = _n0->spec;
            auto ei = _n0->element_interval.has_value() ? *_n0->element_interval : nullptr;
            auto rs = _n0->resync;
            return cg_deliver(compile_array(e, s, ei, rs, rho, Lnext), delta, gamma, Lnext);
        }
        return {};
    }
};

} // namespace bbq
