// ddcgc — type checker for parsed .ddcg files.
//
// Performs:
//   - pattern type-check  (constructor + field lookup against source schema,
//                          field bindings get the schema-declared type)
//   - expression types    (literals, idents, BinOp, UnaryOp, calls, gen,
//                          list/tuple literals, dest patterns) — all inferred
//                          against the rule's binding env, errors emitted on
//                          type mismatch
//   - aux/pred arity      (CallExpr with N args must match declared arity)
//   - destinations        (exactly one data_dest + one ctrl_dest required;
//                          gen-call's δ and γ slots typed against them)
//   - coverage            (every constructor of the *first import* — by
//                          convention the source AST — has at least one
//                          rule head, unless listed in
//                          desugared_by_normalization)
//   - overlap             (warn when two rules share the same
//                          ConstructorPat head with non-trivially-
//                          disjoint guards)
//   - duplicate           (error on two rules with same head and same
//                          guard expression text)

#pragma once

#include "ddcg_ast.h"
#include "schema.h"

#include <map>
#include <string>
#include <vector>

namespace ddcgc {

// ── Type representation ─────────────────────────────────────

enum class TypeKind {
    Unknown,        // pre-inference or genuinely opaque (runtime-supplied)
    Void,           // statement-only context
    Int,
    String,
    Bool,
    Ident,          // asdl `identifier` — std::string at the C++ level,
                    // distinct so we keep the semantic intent
    Label,          // generated by `label NAME;` statements
    NilLit,         // type of the `nil` literal — assignable to any Schema
    Schema,         // a sum or constructor from a loaded schema (pointer-typed)
    Dest,           // a user-declared data_dest or ctrl_dest tagged union
    List,           // list<T>
    Tuple,          // tuple<T1, T2, ...>
};

struct Type {
    TypeKind kind = TypeKind::Unknown;

    // For Schema: which import + which sum/ctor name
    std::string schema_import;
    std::string name;

    // For Dest: the user-declared destination name (e.g., "gamma")
    // For Schema: the sum/ctor name
    // For Unknown (with name): a runtime-supplied type identifier

    // For List: 1-element vector with the element type
    // For Tuple: N-element vector
    std::vector<Type> elems;

    // ── Constructors ──
    static Type unknown()                  { return {}; }
    static Type unknown_named(std::string n) { Type t; t.name = std::move(n); return t; }
    static Type voidty() { Type t; t.kind = TypeKind::Void; return t; }
    static Type int_()  { Type t; t.kind = TypeKind::Int;  return t; }
    static Type str()   { Type t; t.kind = TypeKind::String; return t; }
    static Type bool_() { Type t; t.kind = TypeKind::Bool; return t; }
    static Type ident() { Type t; t.kind = TypeKind::Ident; return t; }
    static Type label() { Type t; t.kind = TypeKind::Label; return t; }
    static Type nil_()  { Type t; t.kind = TypeKind::NilLit; return t; }
    static Type schema(std::string imp, std::string n) {
        Type t; t.kind = TypeKind::Schema;
        t.schema_import = std::move(imp); t.name = std::move(n);
        return t;
    }
    static Type dest(std::string n) {
        Type t; t.kind = TypeKind::Dest; t.name = std::move(n);
        return t;
    }
    static Type list_(Type elem) {
        Type t; t.kind = TypeKind::List; t.elems.push_back(std::move(elem));
        return t;
    }
    static Type tuple_(std::vector<Type> es) {
        Type t; t.kind = TypeKind::Tuple; t.elems = std::move(es);
        return t;
    }

    bool is(TypeKind k) const { return kind == k; }
    bool is_unknown() const   { return kind == TypeKind::Unknown; }

    // Equality: structural.
    bool operator==(const Type& o) const;
    bool operator!=(const Type& o) const { return !(*this == o); }

    // Human-readable form for error messages: "int", "kont*", "list<int>", etc.
    std::string display() const;
};

// True if `value_t` can be assigned to a binding/parameter of `expected_t`.
// Lenient: Unknown matches anything; nil matches any Schema; same kind &
// payload otherwise. When `schemas` is non-null, also recognises the
// constructor → parent-sum subtyping baked into the asdl schema (e.g.
// `target.Imm` is assignable to `target.value`).
bool assignable(const Type& expected, const Type& value,
                 const std::map<std::string, Schema>* schemas = nullptr);

// ── Diagnostics ─────────────────────────────────────────────

struct Diagnostic {
    DdcgAst::SourceLoc loc;
    std::string message;
};

struct CheckResult {
    std::vector<Diagnostic> errors;
    std::vector<Diagnostic> warnings;

    // Side-table populated by check_file() during type inference.
    // Codegen consumes this to resolve gen-call dispatch targets,
    // list element types, dest-variant types, etc.
    std::map<const DdcgAst::Expr*, Type> expr_types;

    bool ok() const { return errors.empty(); }
};

// Type-check + type-infer a parsed .ddcg file against its imported schemas.
// Caller (CLI driver) populates `schemas` from the IMPORTS section's
// `name = "path"` entries.
CheckResult check_file(const DdcgAst::File* file,
                        const std::map<std::string, Schema>& schemas);

} // namespace ddcgc
